<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Causal Inference I: Counterfactuals, Randomisation, Matching – Quantitative Methods in International Business with Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./session-11.html" rel="next">
<link href="./session-09.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-87cceeb0dc72897ec58809a022325911.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-654b0d63ec6aea178ec964394c84683d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./session-10.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods in International Business with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warint/quantitative-methods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis, and the First Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression: Adequacy, Validity, and Robustness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Component and Factor Analyses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">K-Nearest Neighbours and the Bias–Variance Trade-off</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structural Equation Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Final Group Presentations</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Setting up your tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-api.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The data API</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./replications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Replication packages</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-the-session" id="toc-before-the-session" class="nav-link active" data-scroll-target="#before-the-session"><span class="header-section-number">10.1</span> Before the session</a>
  <ul class="collapse">
  <li><a href="#the-reading-4560-min" id="toc-the-reading-4560-min" class="nav-link" data-scroll-target="#the-reading-4560-min"><span class="header-section-number">10.1.1</span> 1. The reading — 45–60 min</a></li>
  <li><a href="#the-data-10-min" id="toc-the-data-10-min" class="nav-link" data-scroll-target="#the-data-10-min"><span class="header-section-number">10.1.2</span> 2. The data — 10 min</a></li>
  <li><a href="#self-check-15-min" id="toc-self-check-15-min" class="nav-link" data-scroll-target="#self-check-15-min"><span class="header-section-number">10.1.3</span> 3. Self-check — 15 min</a></li>
  <li><a href="#arrive-with" id="toc-arrive-with" class="nav-link" data-scroll-target="#arrive-with"><span class="header-section-number">10.1.4</span> Arrive with</a></li>
  </ul></li>
  <li><a href="#the-lecture" id="toc-the-lecture" class="nav-link" data-scroll-target="#the-lecture"><span class="header-section-number">10.2</span> The lecture</a></li>
  <li><a href="#causal-inference-logic-and-tools" id="toc-causal-inference-logic-and-tools" class="nav-link" data-scroll-target="#causal-inference-logic-and-tools"><span class="header-section-number">10.3</span> Causal Inference: Logic and Tools</a></li>
  <li><a href="#session-overview" id="toc-session-overview" class="nav-link" data-scroll-target="#session-overview"><span class="header-section-number">10.4</span> Session Overview</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><span class="header-section-number">10.5</span> Objectives</a></li>
  <li><a href="#counterfactual-framework" id="toc-counterfactual-framework" class="nav-link" data-scroll-target="#counterfactual-framework"><span class="header-section-number">10.6</span> Counterfactual Framework</a></li>
  <li><a href="#the-rubin-causal-model" id="toc-the-rubin-causal-model" class="nav-link" data-scroll-target="#the-rubin-causal-model"><span class="header-section-number">10.7</span> The Rubin Causal Model</a></li>
  <li><a href="#why-it-matters" id="toc-why-it-matters" class="nav-link" data-scroll-target="#why-it-matters"><span class="header-section-number">10.8</span> Why It Matters</a></li>
  <li><a href="#real-example-of-observed-and-counterfactual-outcomes" id="toc-real-example-of-observed-and-counterfactual-outcomes" class="nav-link" data-scroll-target="#real-example-of-observed-and-counterfactual-outcomes"><span class="header-section-number">10.9</span> Real Example of Observed and Counterfactual Outcomes</a></li>
  <li><a href="#observed-vs.-counterfactual" id="toc-observed-vs.-counterfactual" class="nav-link" data-scroll-target="#observed-vs.-counterfactual"><span class="header-section-number">10.10</span> Observed vs.&nbsp;Counterfactual</a></li>
  <li><a href="#the-missing-counterfactual" id="toc-the-missing-counterfactual" class="nav-link" data-scroll-target="#the-missing-counterfactual"><span class="header-section-number">10.11</span> The Missing Counterfactual</a></li>
  <li><a href="#how-to-proceed" id="toc-how-to-proceed" class="nav-link" data-scroll-target="#how-to-proceed"><span class="header-section-number">10.12</span> How to Proceed</a></li>
  <li><a href="#randomized-controlled-trials-rcts" id="toc-randomized-controlled-trials-rcts" class="nav-link" data-scroll-target="#randomized-controlled-trials-rcts"><span class="header-section-number">10.13</span> Randomized Controlled Trials (RCTs)</a></li>
  <li><a href="#why-randomize" id="toc-why-randomize" class="nav-link" data-scroll-target="#why-randomize"><span class="header-section-number">10.14</span> Why Randomize?</a></li>
  <li><a href="#what-for" id="toc-what-for" class="nav-link" data-scroll-target="#what-for"><span class="header-section-number">10.15</span> What For?</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works"><span class="header-section-number">10.16</span> How It Works</a></li>
  <li><a href="#example-in-r" id="toc-example-in-r" class="nav-link" data-scroll-target="#example-in-r"><span class="header-section-number">10.17</span> Example in R</a></li>
  <li><a href="#data-generation-process" id="toc-data-generation-process" class="nav-link" data-scroll-target="#data-generation-process"><span class="header-section-number">10.18</span> Data Generation Process</a></li>
  <li><a href="#data-simulation" id="toc-data-simulation" class="nav-link" data-scroll-target="#data-simulation"><span class="header-section-number">10.19</span> Data Simulation</a></li>
  <li><a href="#estimating-the-treatment-effect" id="toc-estimating-the-treatment-effect" class="nav-link" data-scroll-target="#estimating-the-treatment-effect"><span class="header-section-number">10.20</span> Estimating the Treatment Effect</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">10.21</span> Interpretation</a></li>
  <li><a href="#observational-data-challenges" id="toc-observational-data-challenges" class="nav-link" data-scroll-target="#observational-data-challenges"><span class="header-section-number">10.22</span> Observational Data: Challenges</a></li>
  <li><a href="#why-not-always-use-rcts" id="toc-why-not-always-use-rcts" class="nav-link" data-scroll-target="#why-not-always-use-rcts"><span class="header-section-number">10.23</span> Why Not Always Use RCTs?</a></li>
  <li><a href="#whats-the-risk" id="toc-whats-the-risk" class="nav-link" data-scroll-target="#whats-the-risk"><span class="header-section-number">10.24</span> What’s the Risk?</a></li>
  <li><a href="#what-we-need" id="toc-what-we-need" class="nav-link" data-scroll-target="#what-we-need"><span class="header-section-number">10.25</span> What We Need</a></li>
  <li><a href="#matching-methods" id="toc-matching-methods" class="nav-link" data-scroll-target="#matching-methods"><span class="header-section-number">10.26</span> Matching Methods</a></li>
  <li><a href="#why-use-matching" id="toc-why-use-matching" class="nav-link" data-scroll-target="#why-use-matching"><span class="header-section-number">10.27</span> Why Use Matching?</a></li>
  <li><a href="#what-for-1" id="toc-what-for-1" class="nav-link" data-scroll-target="#what-for-1"><span class="header-section-number">10.28</span> What For?</a></li>
  <li><a href="#how-it-works-1" id="toc-how-it-works-1" class="nav-link" data-scroll-target="#how-it-works-1"><span class="header-section-number">10.29</span> How It Works</a></li>
  <li><a href="#r-example" id="toc-r-example" class="nav-link" data-scroll-target="#r-example"><span class="header-section-number">10.30</span> R Example</a></li>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective"><span class="header-section-number">10.31</span> Objective</a></li>
  <li><a href="#the-model" id="toc-the-model" class="nav-link" data-scroll-target="#the-model"><span class="header-section-number">10.32</span> The model</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1"><span class="header-section-number">10.33</span> Interpretation</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">10.34</span> Limitations</a></li>
  <li><a href="#exercise-propensity-score-matching-and-post-matching-estimation" id="toc-exercise-propensity-score-matching-and-post-matching-estimation" class="nav-link" data-scroll-target="#exercise-propensity-score-matching-and-post-matching-estimation"><span class="header-section-number">10.35</span> Exercise: Propensity Score Matching and Post-Matching Estimation</a></li>
  <li><a href="#problem-statement" id="toc-problem-statement" class="nav-link" data-scroll-target="#problem-statement"><span class="header-section-number">10.36</span> Problem Statement</a></li>
  <li><a href="#steps-to-follow" id="toc-steps-to-follow" class="nav-link" data-scroll-target="#steps-to-follow"><span class="header-section-number">10.37</span> Steps to Follow</a></li>
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution"><span class="header-section-number">10.38</span> <strong>Solution</strong></a></li>
  <li><a href="#step-1.-estimating-the-propensity-score" id="toc-step-1.-estimating-the-propensity-score" class="nav-link" data-scroll-target="#step-1.-estimating-the-propensity-score"><span class="header-section-number">10.39</span> <strong>Step 1. Estimating the propensity score</strong></a></li>
  <li><a href="#step-2.-performing-nearest-neighbor-matching" id="toc-step-2.-performing-nearest-neighbor-matching" class="nav-link" data-scroll-target="#step-2.-performing-nearest-neighbor-matching"><span class="header-section-number">10.40</span> <strong>Step 2. Performing nearest-neighbor matching</strong></a></li>
  <li><a href="#interpreting-the-balance-table-before-matching" id="toc-interpreting-the-balance-table-before-matching" class="nav-link" data-scroll-target="#interpreting-the-balance-table-before-matching"><span class="header-section-number">10.41</span> <strong>Interpreting the Balance Table Before Matching</strong></a></li>
  <li><a href="#means-treated-vs.-control" id="toc-means-treated-vs.-control" class="nav-link" data-scroll-target="#means-treated-vs.-control"><span class="header-section-number">10.42</span> <strong>Means (Treated vs.&nbsp;Control)</strong></a></li>
  <li><a href="#standardized-mean-difference-smd" id="toc-standardized-mean-difference-smd" class="nav-link" data-scroll-target="#standardized-mean-difference-smd"><span class="header-section-number">10.43</span> <strong>Standardized Mean Difference (SMD)</strong></a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2"><span class="header-section-number">10.44</span> <strong>Interpretation</strong></a></li>
  <li><a href="#variance-ratio" id="toc-variance-ratio" class="nav-link" data-scroll-target="#variance-ratio"><span class="header-section-number">10.45</span> <strong>Variance Ratio</strong></a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3"><span class="header-section-number">10.46</span> <strong>Interpretation</strong></a></li>
  <li><a href="#ecdf-mean-and-ecdf-max" id="toc-ecdf-mean-and-ecdf-max" class="nav-link" data-scroll-target="#ecdf-mean-and-ecdf-max"><span class="header-section-number">10.47</span> <strong>eCDF Mean and eCDF Max</strong></a></li>
  <li><a href="#interpretation-4" id="toc-interpretation-4" class="nav-link" data-scroll-target="#interpretation-4"><span class="header-section-number">10.48</span> <strong>Interpretation</strong></a></li>
  <li><a href="#overall-interpretation" id="toc-overall-interpretation" class="nav-link" data-scroll-target="#overall-interpretation"><span class="header-section-number">10.49</span> <strong>Overall Interpretation</strong></a></li>
  <li><a href="#step-3.-covariate-balance-assessment" id="toc-step-3.-covariate-balance-assessment" class="nav-link" data-scroll-target="#step-3.-covariate-balance-assessment"><span class="header-section-number">10.50</span> <strong>Step 3. Covariate balance assessment</strong></a></li>
  <li><a href="#step-4.-covariate-balance-assessment-continued" id="toc-step-4.-covariate-balance-assessment-continued" class="nav-link" data-scroll-target="#step-4.-covariate-balance-assessment-continued"><span class="header-section-number">10.51</span> <strong>Step 4. Covariate balance assessment (continued)</strong></a></li>
  <li><a href="#step-5.-covariate-balance-assessment-continued" id="toc-step-5.-covariate-balance-assessment-continued" class="nav-link" data-scroll-target="#step-5.-covariate-balance-assessment-continued"><span class="header-section-number">10.52</span> <strong>Step 5. Covariate balance assessment (continued)</strong></a></li>
  <li><a href="#step-6.-covariate-balance-assessment-continued" id="toc-step-6.-covariate-balance-assessment-continued" class="nav-link" data-scroll-target="#step-6.-covariate-balance-assessment-continued"><span class="header-section-number">10.53</span> <strong>Step 6. Covariate balance assessment (continued)</strong></a></li>
  <li><a href="#step-4.-estimating-the-treatment-effect-on-the-matched-sample" id="toc-step-4.-estimating-the-treatment-effect-on-the-matched-sample" class="nav-link" data-scroll-target="#step-4.-estimating-the-treatment-effect-on-the-matched-sample"><span class="header-section-number">10.54</span> <strong>Step 4. Estimating the treatment effect on the matched sample</strong></a></li>
  <li><a href="#step-5.-interpretation" id="toc-step-5.-interpretation" class="nav-link" data-scroll-target="#step-5.-interpretation"><span class="header-section-number">10.55</span> <strong>Step 5. Interpretation</strong></a></li>
  <li><a href="#additional-note-on-naive-difference-in-means" id="toc-additional-note-on-naive-difference-in-means" class="nav-link" data-scroll-target="#additional-note-on-naive-difference-in-means"><span class="header-section-number">10.56</span> <strong>Additional Note on Naive Difference-in-Means</strong></a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">10.57</span> Your turn</a></li>
  <li><a href="#team-work" id="toc-team-work" class="nav-link" data-scroll-target="#team-work"><span class="header-section-number">10.58</span> Team Work</a></li>
  <li><a href="#in-the-practice" id="toc-in-the-practice" class="nav-link" data-scroll-target="#in-the-practice"><span class="header-section-number">10.59</span> In the practice</a>
  <ul class="collapse">
  <li><a href="#causal-inference-i-counterfactuals-randomisation-matching" id="toc-causal-inference-i-counterfactuals-randomisation-matching" class="nav-link" data-scroll-target="#causal-inference-i-counterfactuals-randomisation-matching"><span class="header-section-number">10.59.1</span> Causal Inference I: Counterfactuals, Randomisation, Matching</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-10.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapter-meta">
<p><a href="https://warint.github.io/quantitative-methods/session-10-lecture.html">Lecture slides</a> · <a href="https://warint.github.io/quantitative-methods/session-10-pre-session.html">Pre-session slides</a> · <a href="https://warint.github.io/quantitative-methods/session-10-practice.html">Practice slides</a></p>
</div>
<blockquote class="blockquote">
<p><strong>Did the policy do anything, or were the groups different to begin with?</strong></p>
</blockquote>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><strong>Theme of the practice</strong></td>
<td>Can your project support a causal claim at all?</td>
</tr>
<tr class="even">
<td><strong>Reading</strong></td>
<td>Bodory, Huber &amp; Lafférs (2022), <em>Evaluating (weighted) dynamic treatment effects by double machine learning</em> · <a href="https://doi.org/10.1093/ectj/utac018">article</a></td>
</tr>
<tr class="odd">
<td><strong>Replication package</strong></td>
<td><a href="https://doi.org/10.7910/DVN/FS0KBA">10.7910/DVN/FS0KBA</a></td>
</tr>
<tr class="even">
<td><strong>Data</strong></td>
<td><code>qmib.load("core")</code> — the spine’s documented treatment, with a known effect to recover</td>
</tr>
</tbody>
</table>
<div class="plate">
<p><img src="images/session-10-hume.jpg" class="img-fluid" alt="Portrait of David Hume, 1711–1776."></p>
<p><strong>David Hume</strong> · 1711–1776</p>
<p>Asked what entitles us to say one thing causes another, and did not find a satisfying answer. Neither has anyone since.</p>
<p><span class="plate-credit">Allan Ramsay, 1766. Public domain, via Wikimedia Commons.</span></p>
</div>
<section id="before-the-session" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="before-the-session"><span class="header-section-number">10.1</span> Before the session</h2>
<blockquote class="blockquote">
<p><strong>Did the policy do anything, or were the groups different to begin with?</strong></p>
</blockquote>
<blockquote class="blockquote">
<p><strong><a href="https://warint.github.io/quantitative-methods/session-10-pre-session.html">Open the pre-session slides</a></strong> · source: <a href="https://github.com/warint/quantitative-methods/blob/main/MATH60033A-S10-Pre-Session.qmd"><code>MATH60033A-S10-Pre-Session.qmd</code></a></p>
</blockquote>
<p>Two things to do before class, and they are the two halves of the practice. Budget <strong>60–90 minutes</strong>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Before class</th>
<th>Used in the practice for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>Read the paper</td>
<td>reproducing one of its results</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>Get both datasets</td>
<td>that, and applying the method to your own angle</td>
</tr>
</tbody>
</table>
<hr>
<section id="the-reading-4560-min" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="the-reading-4560-min"><span class="header-section-number">10.1.1</span> 1. The reading — 45–60 min</h3>
<p><strong>Bodory, Huber &amp; Lafférs (2022), <em>Evaluating (weighted) dynamic treatment effects by double machine learning</em></strong> <a href="https://doi.org/10.1093/ectj/utac018">Read the article</a></p>
<p>Read for the <strong>argument</strong>, not for coverage:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>What to look for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>The research question, in one sentence</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>The method or design, and why they chose it</td>
</tr>
<tr class="odd">
<td><strong>3</strong></td>
<td>The strongest single piece of evidence</td>
</tr>
<tr class="even">
<td><strong>4</strong></td>
<td>One limitation you would raise as a referee</td>
</tr>
</tbody>
</table>
<p><strong>Annotate as you go.</strong> You will be asked what you underlined and why.</p>
<hr>
</section>
<section id="the-data-10-min" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="the-data-10-min"><span class="header-section-number">10.1.2</span> 2. The data — 10 min</h3>
<p>You need <strong>two</strong> datasets in the practice, and both should be on your machine before you arrive.</p>
<section id="a-the-papers-replication-package" class="level4" data-number="10.1.2.1">
<h4 data-number="10.1.2.1" class="anchored" data-anchor-id="a-the-papers-replication-package"><span class="header-section-number">10.1.2.1</span> a) The paper’s replication package</h4>
<p>This is what you reproduce in the first twenty minutes of the practice.</p>
<p><strong>Harvard Dataverse: <a href="https://doi.org/10.7910/DVN/FS0KBA">10.7910/DVN/FS0KBA</a></strong></p>
<p>Download it once, and unzip it here — the folder is git-ignored, so nothing large is committed:</p>
<pre class="text"><code>10-causal-inference-foundations/data/replication/</code></pre>
<p>Keep the authors’ own folder structure and README.</p>
</section>
<section id="b-the-course-data-for-your-own-angle" class="level4" data-number="10.1.2.2">
<h4 data-number="10.1.2.2" class="anchored" data-anchor-id="b-the-course-data-for-your-own-angle"><span class="header-section-number">10.1.2.2</span> b) The course data, for your own angle</h4>
<p>This is what you apply the method to in the second half.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> qmib</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> qmib.load(<span class="st">"core"</span>)      <span class="co"># what the lecture uses</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>core <span class="op">=</span> qmib.load(<span class="st">"core"</span>)                 <span class="co"># shared by every group</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>mine <span class="op">=</span> qmib.load(<span class="st">"angle_c_country"</span>)      <span class="co"># YOUR angle — see your dictionary</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.shape, core.shape, mine.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The spine’s documented treatment, with a known effect to recover.</p>
<blockquote class="blockquote">
<p>Run this <strong>before</strong> class. It downloads once and caches as parquet, so the practice works whatever the room’s wifi is doing. <code>qmib.catalog()</code> lists everything available.</p>
</blockquote>
<p>Your group’s file, columns, units and traps are in your <a href="https://github.com/warint/quantitative-methods/blob/main/data/spine/dictionaries/">data dictionary</a>.</p>
<hr>
</section>
</section>
<section id="self-check-15-min" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="self-check-15-min"><span class="header-section-number">10.1.3</span> 3. Self-check — 15 min</h3>
<p>Answer on paper. If you cannot, that is what the lecture is for.</p>
<ol type="1">
<li>In one sentence: what does this session’s method let you claim that the previous one did not?</li>
<li>What must be true of your data for it to apply?</li>
<li>Which claim in the paper rests on this method — and how hard does it lean on it?</li>
</ol>
<hr>
</section>
<section id="arrive-with" class="level3" data-number="10.1.4">
<h3 data-number="10.1.4" class="anchored" data-anchor-id="arrive-with"><span class="header-section-number">10.1.4</span> Arrive with</h3>
<ul class="task-list">
<li><label><input type="checkbox">The paper read and annotated</label></li>
<li><label><input type="checkbox">The replication package downloaded and unzipped</label></li>
<li><label><input type="checkbox"><code>qmib.load()</code> run at least once, so the cache exists</label></li>
<li><label><input type="checkbox">Your self-check answers, on paper</label></li>
</ul>
<hr>
<p><a href="./session-10.html">Session 10 overview</a> · <a href="#the-lecture">The lecture</a> · <a href="#in-the-practice">The practice</a></p>
</section>
</section>
<section id="the-lecture" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="the-lecture"><span class="header-section-number">10.2</span> The lecture</h2>
<div class="muted">
<p>Delivered from <a href="https://warint.github.io/quantitative-methods/session-10-lecture.html">the slides</a>. What follows is the same material as prose.</p>
</div>
<!-- Imported from https://warin.ca/quant/en/session10_cours/. Content is static so the deck renders without R or Python. -->
</section>
<section id="causal-inference-logic-and-tools" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="causal-inference-logic-and-tools"><span class="header-section-number">10.3</span> Causal Inference: Logic and Tools</h2>
</section>
<section id="session-overview" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="session-overview"><span class="header-section-number">10.4</span> Session Overview</h2>
<ul>
<li>Motivation: Why regression isn’t enough</li>
<li>Key Concepts: Counterfactuals, potential outcomes, Rubin Causal Model</li>
<li>Core Methods: RCTs, Matching, IV, DiD</li>
<li>Assumptions &amp; Validity: Parallel trends, exclusion restriction, internal vs.&nbsp;external validity</li>
<li>Applications in Policy and Management</li>
</ul>
</section>
<section id="objectives" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="objectives"><span class="header-section-number">10.5</span> Objectives</h2>
<ul>
<li>Distinguish correlation from causation</li>
<li>Explain potential outcomes and counterfactuals</li>
<li>Apply causal inference techniques in R</li>
<li>Evaluate assumptions and threats to identification</li>
<li>Interpret empirical strategies in applied research</li>
</ul>
<p><img src="images/decks/session-10-economist-assets-potential-outcomes.png" class="r-stretch img-fluid"></p>
</section>
<section id="counterfactual-framework" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="counterfactual-framework"><span class="header-section-number">10.6</span> Counterfactual Framework</h2>
</section>
<section id="the-rubin-causal-model" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="the-rubin-causal-model"><span class="header-section-number">10.7</span> The Rubin Causal Model</h2>
<p>Causal inference is fundamentally about comparison—understanding what would have happened to the same unit had it experienced a different condition.</p>
<p>In the potential outcomes framework, each unit <span class="math inline">\(i\)</span> has two potential outcomes:</p>
<ul>
<li><span class="math inline">\(Y_i(1)\)</span>: the outcome if treated</li>
<li><span class="math inline">\(Y_i(0)\)</span>: the outcome if untreated</li>
</ul>
<p>The causal effect for unit <span class="math inline">\(i\)</span> is defined as <span class="math inline">\(Y_i(1) - Y_i(0)\)</span>.</p>
<blockquote class="blockquote">
<p>However, only one of these outcomes is ever observed; the other remains a counterfactual. This is the core problem that causal inference aims to address.</p>
</blockquote>
</section>
<section id="why-it-matters" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="why-it-matters"><span class="header-section-number">10.8</span> Why It Matters</h2>
<p>Without this framework, we cannot articulate what it means for a treatment to have an effect. Understanding causal effects requires us to think explicitly about what did <em>not</em> happen.</p>
</section>
<section id="real-example-of-observed-and-counterfactual-outcomes" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="real-example-of-observed-and-counterfactual-outcomes"><span class="header-section-number">10.9</span> Real Example of Observed and Counterfactual Outcomes</h2>
<p>Consider a public policy intervention such as a <strong>subsidy for electric-vehicle (EV) purchases</strong>. Suppose the government introduces a financial incentive intended to increase EV adoption among households. For each household (i), we can define two potential outcomes:</p>
<p><span class="math display">\[ Y_i(1) = \text{EV adoption if the household receives the subsidy}, \]</span></p>
<p><span class="math display">\[ Y_i(0) = \text{EV adoption if the household does not receive the subsidy}. \]</span></p>
</section>
<section id="observed-vs.-counterfactual" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="observed-vs.-counterfactual"><span class="header-section-number">10.10</span> Observed vs.&nbsp;Counterfactual</h2>
<p>Imagine a specific household, say <strong>Household 27</strong>. After the policy is implemented, Household 27 <em>does</em> receive the subsidy and purchases an electric vehicle. Therefore, we observe:</p>
<p><span class="math display">\[ Y\_{27}(1) = 1. \]</span></p>
<p>But we never observe the counterfactual outcome:</p>
<p><span class="math display">\[ Y\_{27}(0) = ? \]</span></p>
</section>
<section id="the-missing-counterfactual" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="the-missing-counterfactual"><span class="header-section-number">10.11</span> The Missing Counterfactual</h2>
<p>This non-observed outcome represents what would have happened <em>to the same household</em> had it <strong>not</strong> received the subsidy. It is fundamentally unobservable, because the household cannot simultaneously be treated and untreated. Yet this is precisely the comparison needed to identify the causal effect for that household:</p>
<p><span class="math display">\[ \text{Causal Effect}*{27} = Y*{27}(1) - Y\_{27}(0). \]</span></p>
<p>Since <span class="math inline">\(Y\_{27}(0)\)</span> is missing by design—not due to lack of data but because of the logic of causality—researchers must rely on techniques such as randomized controlled trials, matching, instrumental variables, or difference-in-differences to recover credible approximations of this unobserved counterfactual.</p>
<p>This tension between <strong>observed reality</strong> and <strong>missing counterfactuals</strong> encapsulates the fundamental problem of causal inference articulated by Rubin (1974) and formalized in the potential-outcomes framework.</p>
</section>
<section id="how-to-proceed" class="level2" data-number="10.12">
<h2 data-number="10.12" class="anchored" data-anchor-id="how-to-proceed"><span class="header-section-number">10.12</span> How to Proceed</h2>
<blockquote class="blockquote">
<p>We aim to estimate the average causal effect (ATE) by constructing designs or assumptions that allow us to approximate the missing counterfactuals.</p>
</blockquote>
<p>How? By creating comparable groups through randomization, matching, or leveraging natural experiments.</p>
</section>
<section id="randomized-controlled-trials-rcts" class="level2" data-number="10.13">
<h2 data-number="10.13" class="anchored" data-anchor-id="randomized-controlled-trials-rcts"><span class="header-section-number">10.13</span> Randomized Controlled Trials (RCTs)</h2>
</section>
<section id="why-randomize" class="level2" data-number="10.14">
<h2 data-number="10.14" class="anchored" data-anchor-id="why-randomize"><span class="header-section-number">10.14</span> Why Randomize?</h2>
<p>Randomization is the most reliable method for ensuring that treated and control groups are comparable.</p>
<blockquote class="blockquote">
<p>It removes systematic differences between groups, which means that any observed difference in outcomes can be attributed to the treatment.</p>
</blockquote>
</section>
<section id="what-for" class="level2" data-number="10.15">
<h2 data-number="10.15" class="anchored" data-anchor-id="what-for"><span class="header-section-number">10.15</span> What For?</h2>
<p>RCTs allow us to isolate the effect of a single intervention, making them the gold standard for internal validity.</p>
<p>They are widely used in medicine, economics, and the social sciences.</p>
</section>
<section id="how-it-works" class="level2" data-number="10.16">
<h2 data-number="10.16" class="anchored" data-anchor-id="how-it-works"><span class="header-section-number">10.16</span> How It Works</h2>
<p>Units are assigned to treatment or control groups purely by chance.</p>
<blockquote class="blockquote">
<p>This ensures balance on both observed and unobserved confounders.</p>
</blockquote>
</section>
<section id="example-in-r" class="level2" data-number="10.17">
<h2 data-number="10.17" class="anchored" data-anchor-id="example-in-r"><span class="header-section-number">10.17</span> Example in R</h2>
<p>Suppose an employer offers an intensive data-analytics training course aimed at improving employees’ performance in tasks that rely on quantitative analysis and digital tools. The variable <code>treat</code> indicates whether an employee participated in the training (1) or not (0). The variables <code>age</code>, <code>education</code>, and <code>experience</code> describe each employee’s profile: <code>age</code> in years, <code>education</code> as years of schooling, and <code>experience</code> as years of labour-market experience, approximately measured as age minus 18 with some noise, which is standard in labour economics.</p>
</section>
<section id="data-generation-process" class="level2" data-number="10.18">
<h2 data-number="10.18" class="anchored" data-anchor-id="data-generation-process"><span class="header-section-number">10.18</span> Data Generation Process</h2>
<p>In this organization, employees who are slightly older and more educated are more likely to be selected or to self-select into the training programme. This is reflected in the way <code>treat</code> is generated: the probability of being treated increases with age and education through the propensity score <code>ps</code>. This captures realistic selection mechanisms, such as managers prioritizing “high-potential” workers or those already in more skilled positions.</p>
<p>The outcome variable, <code>outcome</code>, can be interpreted as an index of job performance or productivity, for example a standardized annual performance score used in internal evaluations, or an objective productivity measure (such as the number of correctly processed files, resolved cases, or successfully completed projects). The data-generating process assumes that performance increases with age, education, and experience, which is consistent with human capital theory. On top of these effects, the training programme has a true causal effect of +3 units on the performance index for those who participate. This models the idea that, after controlling for their characteristics, employees who receive the training perform systematically better than similar employees who do not.</p>
</section>
<section id="data-simulation" class="level2" data-number="10.19">
<h2 data-number="10.19" class="anchored" data-anchor-id="data-simulation"><span class="header-section-number">10.19</span> Data Simulation</h2>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># In the VS Codium terminal, with .venv active:  python</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd</span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="im">from</span> scipy.special <span class="im">import</span> expit</span>
<span id="cb3-4"><a href="#cb3-4"></a></span>
<span id="cb3-5"><a href="#cb3-5"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">123</span>)</span>
<span id="cb3-6"><a href="#cb3-6"></a>n <span class="op">=</span> <span class="dv">800</span></span>
<span id="cb3-7"><a href="#cb3-7"></a></span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="co"># Covariates</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>age        <span class="op">=</span> np.<span class="bu">round</span>(rng.normal(<span class="dv">40</span>, <span class="dv">10</span>, n))</span>
<span id="cb3-10"><a href="#cb3-10"></a>education  <span class="op">=</span> np.<span class="bu">round</span>(rng.normal(<span class="dv">14</span>, <span class="dv">2</span>, n))</span>
<span id="cb3-11"><a href="#cb3-11"></a>experience <span class="op">=</span> np.maximum(<span class="dv">0</span>, age <span class="op">-</span> <span class="dv">18</span> <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">3</span>, n))</span>
<span id="cb3-12"><a href="#cb3-12"></a></span>
<span id="cb3-13"><a href="#cb3-13"></a><span class="co"># Treatment is NOT random: older, more educated people take it up more often.</span></span>
<span id="cb3-14"><a href="#cb3-14"></a>ps_true <span class="op">=</span> expit(<span class="op">-</span><span class="dv">5</span> <span class="op">+</span> <span class="fl">0.05</span> <span class="op">*</span> age <span class="op">+</span> <span class="fl">0.15</span> <span class="op">*</span> education)</span>
<span id="cb3-15"><a href="#cb3-15"></a>treat   <span class="op">=</span> rng.binomial(<span class="dv">1</span>, ps_true)</span>
<span id="cb3-16"><a href="#cb3-16"></a></span>
<span id="cb3-17"><a href="#cb3-17"></a><span class="co"># The true effect we are trying to recover is +2.5</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>outcome <span class="op">=</span> <span class="dv">20</span> <span class="op">+</span> <span class="fl">2.5</span> <span class="op">*</span> treat <span class="op">+</span> <span class="fl">0.3</span> <span class="op">*</span> age <span class="op">+</span> <span class="fl">0.8</span> <span class="op">*</span> education <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, n)</span>
<span id="cb3-19"><a href="#cb3-19"></a></span>
<span id="cb3-20"><a href="#cb3-20"></a>df <span class="op">=</span> pd.DataFrame(<span class="bu">dict</span>(age<span class="op">=</span>age, education<span class="op">=</span>education, experience<span class="op">=</span>experience,</span>
<span id="cb3-21"><a href="#cb3-21"></a>                       treat<span class="op">=</span>treat, outcome<span class="op">=</span>outcome))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>  treat age education experience  outcome
1     0  34        15   15.13293 51.35139
2     0  38        13   21.96954 47.27609
3     1  56        16   36.63801 63.76421
4     0  41        16   21.21841 65.16926
5     0  41        15   17.86886 55.22382
6     0  57        14   38.37165 65.50069</code></pre>
</div>
</section>
<section id="estimating-the-treatment-effect" class="level2" data-number="10.20">
<h2 data-number="10.20" class="anchored" data-anchor-id="estimating-the-treatment-effect"><span class="header-section-number">10.20</span> Estimating the Treatment Effect</h2>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb5-2"><a href="#cb5-2"></a>n <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>treatment <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="fl">0.5</span>, n)          <span class="co"># randomised: no confounding</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>y <span class="op">=</span> <span class="dv">50</span> <span class="op">+</span> <span class="dv">5</span> <span class="op">*</span> treatment <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">10</span>, n)</span>
<span id="cb5-5"><a href="#cb5-5"></a></span>
<span id="cb5-6"><a href="#cb5-6"></a>y[treatment <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> y[treatment <span class="op">==</span> <span class="dv">0</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>[1] 6.975967</code></pre>
</div>
</section>
<section id="interpretation" class="level2" data-number="10.21">
<h2 data-number="10.21" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">10.21</span> Interpretation</h2>
<p>Here, the difference in means provides an unbiased estimate of the Average Treatment Effect (ATE).</p>
</section>
<section id="observational-data-challenges" class="level2" data-number="10.22">
<h2 data-number="10.22" class="anchored" data-anchor-id="observational-data-challenges"><span class="header-section-number">10.22</span> Observational Data: Challenges</h2>
</section>
<section id="why-not-always-use-rcts" class="level2" data-number="10.23">
<h2 data-number="10.23" class="anchored" data-anchor-id="why-not-always-use-rcts"><span class="header-section-number">10.23</span> Why Not Always Use RCTs?</h2>
<p>RCTs are not always feasible due to ethical, financial, or logistical constraints. In many real-world settings, we rely on observational data.</p>
</section>
<section id="whats-the-risk" class="level2" data-number="10.24">
<h2 data-number="10.24" class="anchored" data-anchor-id="whats-the-risk"><span class="header-section-number">10.24</span> What’s the Risk?</h2>
<p>In observational studies, treatment assignment is not random. This introduces selection bias: treated and control units may differ systematically in ways that affect the outcome.</p>
</section>
<section id="what-we-need" class="level2" data-number="10.25">
<h2 data-number="10.25" class="anchored" data-anchor-id="what-we-need"><span class="header-section-number">10.25</span> What We Need</h2>
<p>To estimate causal effects from observational data, we need methods that adjust for these differences or mimic randomization.</p>
</section>
<section id="matching-methods" class="level2" data-number="10.26">
<h2 data-number="10.26" class="anchored" data-anchor-id="matching-methods"><span class="header-section-number">10.26</span> Matching Methods</h2>
</section>
<section id="why-use-matching" class="level2" data-number="10.27">
<h2 data-number="10.27" class="anchored" data-anchor-id="why-use-matching"><span class="header-section-number">10.27</span> Why Use Matching?</h2>
<p>Matching is a technique designed to reduce selection bias in observational studies by creating a control group that is comparable to the treated group on observed characteristics.</p>
</section>
<section id="what-for-1" class="level2" data-number="10.28">
<h2 data-number="10.28" class="anchored" data-anchor-id="what-for-1"><span class="header-section-number">10.28</span> What For?</h2>
<p>It aims to emulate the balance achieved in RCTs, making the treatment and control groups as similar as possible in terms of observable covariates.</p>
</section>
<section id="how-it-works-1" class="level2" data-number="10.29">
<h2 data-number="10.29" class="anchored" data-anchor-id="how-it-works-1"><span class="header-section-number">10.29</span> How It Works</h2>
<p>We calculate a propensity score—the probability of receiving treatment given observed covariates—and match each treated unit to one or more control units with a similar score.</p>
</section>
<section id="r-example" class="level2" data-number="10.30">
<h2 data-number="10.30" class="anchored" data-anchor-id="r-example"><span class="header-section-number">10.30</span> R Example</h2>
<p>Imagine that a large public-sector organization has implemented an advanced <strong>data-analytics training programme</strong> for its employees. Participation is voluntary but encouraged for individuals working in analytically demanding units. As a result, the employees who choose to enrol tend to be somewhat older, more educated, and more experienced—characteristics that are also associated with better job performance. This creates a <strong>confounding problem</strong>: treated and untreated employees differ in systematic ways that also predict outcomes.</p>
</section>
<section id="objective" class="level2" data-number="10.31">
<h2 data-number="10.31" class="anchored" data-anchor-id="objective"><span class="header-section-number">10.31</span> Objective</h2>
<p>The HR analytics team wants to estimate whether the training actually <strong>improves job performance</strong>, measured by a standardized annual performance index. They cannot rely on simple mean comparisons, because employees who enrolled in the training differ on observable dimensions that are associated with performance. To obtain a more credible estimate of the causal effect, they apply <strong>nearest-neighbour propensity score matching</strong>.</p>
</section>
<section id="the-model" class="level2" data-number="10.32">
<h2 data-number="10.32" class="anchored" data-anchor-id="the-model"><span class="header-section-number">10.32</span> The model</h2>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> NearestNeighbors</span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb7-3"><a href="#cb7-3"></a></span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="co"># 1:1 nearest-neighbour matching on the propensity score</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>treated, control <span class="op">=</span> df[df.treat <span class="op">==</span> <span class="dv">1</span>], df[df.treat <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb7-6"><a href="#cb7-6"></a>nn <span class="op">=</span> NearestNeighbors(n_neighbors<span class="op">=</span><span class="dv">1</span>).fit(control[[<span class="st">"pscore"</span>]])</span>
<span id="cb7-7"><a href="#cb7-7"></a>_, idx <span class="op">=</span> nn.kneighbors(treated[[<span class="st">"pscore"</span>]])</span>
<span id="cb7-8"><a href="#cb7-8"></a>matched <span class="op">=</span> pd.concat([treated, control.iloc[idx.ravel()]])</span>
<span id="cb7-9"><a href="#cb7-9"></a></span>
<span id="cb7-10"><a href="#cb7-10"></a>smf.ols(<span class="st">"outcome ~ treat"</span>, data<span class="op">=</span>matched).fit().summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>    Welch Two Sample t-test

data:  outcome by treat
t = -3.0569, df = 463.82, p-value = 0.002366
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -4.4337743 -0.9638923
sample estimates:
mean in group 0 mean in group 1 
       57.18446        59.88329 </code></pre>
</div>
<p>implements the following reasoning. The <code>matchit()</code> function constructs a matched sample in which treated and untreated employees are paired with others who have similar values of age, education, and experience. This aims to approximate the conditions of a randomized experiment by balancing key covariates. After matching, the organization compares the performance outcomes between the two groups using a t-test. The goal is to estimate how much of the performance difference can plausibly be attributed to the training rather than to pre-existing differences in employee characteristics.</p>
</section>
<section id="interpretation-1" class="level2" data-number="10.33">
<h2 data-number="10.33" class="anchored" data-anchor-id="interpretation-1"><span class="header-section-number">10.33</span> Interpretation</h2>
<p>In this scenario, the matching procedure is understood as a method for approximating the unobserved counterfactual—what treated employees’ performance would have been had they not participated.</p>
<blockquote class="blockquote">
<p>The resulting matched estimate provides a substantively meaningful measure of the programme’s effectiveness under the assumption of conditional independence.</p>
</blockquote>
</section>
<section id="limitations" class="level2" data-number="10.34">
<h2 data-number="10.34" class="anchored" data-anchor-id="limitations"><span class="header-section-number">10.34</span> Limitations</h2>
<blockquote class="blockquote">
<p>Matching only accounts for observed variables. Any unmeasured confounder can still bias the results.</p>
</blockquote>
</section>
<section id="exercise-propensity-score-matching-and-post-matching-estimation" class="level2" data-number="10.35">
<h2 data-number="10.35" class="anchored" data-anchor-id="exercise-propensity-score-matching-and-post-matching-estimation"><span class="header-section-number">10.35</span> Exercise: Propensity Score Matching and Post-Matching Estimation</h2>
</section>
<section id="problem-statement" class="level2" data-number="10.36">
<h2 data-number="10.36" class="anchored" data-anchor-id="problem-statement"><span class="header-section-number">10.36</span> Problem Statement</h2>
<p>You are given a dataframe named <code>df</code> with the following variables:</p>
<ul>
<li><code>treat</code>: a binary treatment indicator equal to 1 for treated units and 0 for control units.</li>
<li><code>outcome</code>: a continuous outcome.</li>
<li><code>age</code>, <code>education</code>, <code>experience</code>: pre-treatment covariates that may jointly influence both treatment assignment and the outcome.</li>
</ul>
<p>Your task is to estimate the causal effect of the treatment on the outcome using propensity score matching. Use the <strong>MatchIt</strong> package to implement nearest-neighbor matching without replacement, and evaluate the quality of the matching using <strong>PSAgraphics</strong>. Then, run a linear regression of the outcome on the treatment in the matched sample.</p>
</section>
<section id="steps-to-follow" class="level2" data-number="10.37">
<h2 data-number="10.37" class="anchored" data-anchor-id="steps-to-follow"><span class="header-section-number">10.37</span> Steps to Follow</h2>
<p>Perform the following steps:</p>
<ol type="1">
<li>Estimate a propensity score using a logit model with covariates <code>x1</code>, <code>x2</code>, and <code>x3</code>.</li>
<li>Perform nearest-neighbor matching (one-to-one) using the estimated propensity score.</li>
<li>Assess covariate balance before and after matching using graphical diagnostics.</li>
<li>Extract the matched dataset and estimate the average treatment effect on the treated (ATT) using a linear regression of <code>y</code> on <code>treat</code>.</li>
<li>Interpret the results substantively.</li>
</ol>
</section>
<section id="solution" class="level2" data-number="10.38">
<h2 data-number="10.38" class="anchored" data-anchor-id="solution"><span class="header-section-number">10.38</span> <strong>Solution</strong></h2>
</section>
<section id="step-1.-estimating-the-propensity-score" class="level2" data-number="10.39">
<h2 data-number="10.39" class="anchored" data-anchor-id="step-1.-estimating-the-propensity-score"><span class="header-section-number">10.39</span> <strong>Step 1. Estimating the propensity score</strong></h2>
<p>Propensity scores summarize the probability of receiving treatment conditional on observable covariates. Here, the probability is modeled via a logistic regression. This corresponds to the classical Rosenbaum and Rubin (1983) framework in which identification requires unconfoundedness and overlap.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb9-2"><a href="#cb9-2"></a></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="co"># Estimate the propensity score: the probability of treatment given covariates</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>ps_model <span class="op">=</span> smf.logit(<span class="st">"treat ~ age + education + experience"</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb9-5"><a href="#cb9-5"></a>df[<span class="st">"pscore"</span>] <span class="op">=</span> ps_model.predict(df)</span>
<span id="cb9-6"><a href="#cb9-6"></a></span>
<span id="cb9-7"><a href="#cb9-7"></a><span class="bu">print</span>(ps_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>Call:
glm(formula = treat ~ age + education + experience, family = binomial(), 
    data = df)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -4.47646    0.85261  -5.250 1.52e-07 ***
age          0.02815    0.02818   0.999 0.317732    
education    0.13609    0.04076   3.339 0.000841 ***
experience   0.02170    0.02669   0.813 0.416268    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 965.23  on 799  degrees of freedom
Residual deviance: 918.46  on 796  degrees of freedom
AIC: 926.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<p>This output provides the estimated influence of each covariate on the likelihood of receiving the treatment. Covariates should be selected based on theoretical arguments regarding confounding, rather than any predictive purpose.</p>
</section>
<section id="step-2.-performing-nearest-neighbor-matching" class="level2" data-number="10.40">
<h2 data-number="10.40" class="anchored" data-anchor-id="step-2.-performing-nearest-neighbor-matching"><span class="header-section-number">10.40</span> <strong>Step 2. Performing nearest-neighbor matching</strong></h2>
<p>Using the estimated scores, nearest-neighbor matching without replacement is implemented. This aligns each treated unit with a similar untreated unit based on the estimated propensity score.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> NearestNeighbors</span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a>treated, control <span class="op">=</span> df[df.treat <span class="op">==</span> <span class="dv">1</span>], df[df.treat <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb11-4"><a href="#cb11-4"></a>nn <span class="op">=</span> NearestNeighbors(n_neighbors<span class="op">=</span><span class="dv">1</span>).fit(control[[<span class="st">"pscore"</span>]])</span>
<span id="cb11-5"><a href="#cb11-5"></a>_, idx <span class="op">=</span> nn.kneighbors(treated[[<span class="st">"pscore"</span>]])</span>
<span id="cb11-6"><a href="#cb11-6"></a>matched <span class="op">=</span> pd.concat([treated, control.iloc[idx.ravel()]])</span>
<span id="cb11-7"><a href="#cb11-7"></a></span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(treated)<span class="sc">}</span><span class="ss"> treated matched to </span><span class="sc">{</span><span class="bu">len</span>(<span class="bu">set</span>(idx.ravel()))<span class="sc">}</span><span class="ss"> distinct controls"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>Call:
matchit(formula = treat ~ age + education + experience, data = df, 
    method = "nearest", distance = "logit", replace = FALSE)

Summary of Balance for All Data:
           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance          0.3319        0.2745          0.5083     1.1864    0.1450
age              43.2661       38.8025          0.4570     1.0457    0.0792
education        14.4206       13.9436          0.2416     0.9749    0.0370
experience       25.4287       20.7730          0.4478     1.0897    0.1282
           eCDF Max
distance     0.2264
age          0.1986
education    0.1070
experience   0.2060

Summary of Balance for Matched Data:
           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance          0.3319        0.3288          0.0277     1.0908    0.0035
age              43.2661       43.2661          0.0000     1.1483    0.0136
education        14.4206       14.3648          0.0283     1.0448    0.0109
experience       25.4287       25.1901          0.0230     1.1726    0.0188
           eCDF Max Std. Pair Dist.
distance     0.0429          0.0295
age          0.0472          5.6738
education    0.0258          0.9932
experience   0.0515          0.5554

Sample Sizes:
          Control Treated
All           567     233
Matched       233     233
Unmatched     334       0
Discarded       0       0</code></pre>
</div>
</section>
<section id="interpreting-the-balance-table-before-matching" class="level2" data-number="10.41">
<h2 data-number="10.41" class="anchored" data-anchor-id="interpreting-the-balance-table-before-matching"><span class="header-section-number">10.41</span> <strong>Interpreting the Balance Table Before Matching</strong></h2>
<p>You have the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Treated Mean</th>
<th style="text-align: left;">Control Mean</th>
<th style="text-align: left;">Std. Mean Diff.</th>
<th style="text-align: left;">Var. Ratio</th>
<th style="text-align: left;">eCDF Mean</th>
<th style="text-align: left;">eCDF Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">distance</td>
<td style="text-align: left;">0.3319</td>
<td style="text-align: left;">0.2745</td>
<td style="text-align: left;">0.5083</td>
<td style="text-align: left;">1.1864</td>
<td style="text-align: left;">0.1450</td>
<td style="text-align: left;">0.2264</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: left;">43.2661</td>
<td style="text-align: left;">38.8025</td>
<td style="text-align: left;">0.4570</td>
<td style="text-align: left;">1.0457</td>
<td style="text-align: left;">0.0792</td>
<td style="text-align: left;">0.1986</td>
</tr>
<tr class="odd">
<td style="text-align: left;">education</td>
<td style="text-align: left;">14.4206</td>
<td style="text-align: left;">13.9436</td>
<td style="text-align: left;">0.2416</td>
<td style="text-align: left;">0.9749</td>
<td style="text-align: left;">0.0370</td>
<td style="text-align: left;">0.1070</td>
</tr>
<tr class="even">
<td style="text-align: left;">experience</td>
<td style="text-align: left;">25.4287</td>
<td style="text-align: left;">20.7730</td>
<td style="text-align: left;">0.4478</td>
<td style="text-align: left;">1.0897</td>
<td style="text-align: left;">0.1282</td>
<td style="text-align: left;">0.2060</td>
</tr>
</tbody>
</table>
<p>These numbers reflect the <strong>balance before matching</strong>, meaning how different the treated and control groups are in the raw data.</p>
</section>
<section id="means-treated-vs.-control" class="level2" data-number="10.42">
<h2 data-number="10.42" class="anchored" data-anchor-id="means-treated-vs.-control"><span class="header-section-number">10.42</span> <strong>Means (Treated vs.&nbsp;Control)</strong></h2>
<p>These columns simply report the average value of each variable in the treated and control groups.</p>
<p>For example:</p>
<ul>
<li><p><strong>Age</strong>: Treated = 43.27, Control = 38.80 On average, treated individuals are <strong>older</strong>.</p></li>
<li><p><strong>Experience</strong>: Treated = 25.43, Control = 20.77 Treated individuals have <strong>more prior experience</strong>.</p></li>
</ul>
<p>These raw differences suggest <strong>selection into treatment</strong>: people with higher age and experience are more likely to be treated.</p>
</section>
<section id="standardized-mean-difference-smd" class="level2" data-number="10.43">
<h2 data-number="10.43" class="anchored" data-anchor-id="standardized-mean-difference-smd"><span class="header-section-number">10.43</span> <strong>Standardized Mean Difference (SMD)</strong></h2>
<p>This is the most important measure. It shows the difference in means in units of standard deviations. The rule of thumb:</p>
<ul>
<li>|SMD| &lt; <strong>0.10</strong> → excellent balance</li>
<li>|SMD| &lt; <strong>0.20</strong> → acceptable</li>
<li>|SMD| &gt; <strong>0.25</strong> → problematic imbalance</li>
<li>|SMD| &gt; <strong>0.40</strong> → severe imbalance</li>
</ul>
<p>our values:</p>
<ul>
<li><strong>distance</strong>: 0.5083 → severe imbalance</li>
<li><strong>age</strong>: 0.4570 → severe imbalance</li>
<li><strong>experience</strong>: 0.4478 → severe imbalance</li>
<li><strong>education</strong>: 0.2416 → moderate imbalance</li>
</ul>
</section>
<section id="interpretation-2" class="level2" data-number="10.44">
<h2 data-number="10.44" class="anchored" data-anchor-id="interpretation-2"><span class="header-section-number">10.44</span> <strong>Interpretation</strong></h2>
<p>Before matching, the treated and control groups differ substantially on the covariates and on the propensity score. The matching procedure has a lot of work to do.</p>
</section>
<section id="variance-ratio" class="level2" data-number="10.45">
<h2 data-number="10.45" class="anchored" data-anchor-id="variance-ratio"><span class="header-section-number">10.45</span> <strong>Variance Ratio</strong></h2>
<p>Variance ratio = Var(treated) / Var(control)</p>
<p>Guidelines:</p>
<ul>
<li>Between <strong>0.80 and 1.25</strong> → good</li>
<li>Below 0.60 or above 1.40 → problematic</li>
</ul>
<p>our values:</p>
<ul>
<li><strong>age</strong>: 1.0457 → good</li>
<li><strong>education</strong>: 0.9749 → excellent</li>
<li><strong>experience</strong>: 1.0897 → acceptable</li>
<li><strong>distance</strong>: 1.1864 → acceptable</li>
</ul>
</section>
<section id="interpretation-3" class="level2" data-number="10.46">
<h2 data-number="10.46" class="anchored" data-anchor-id="interpretation-3"><span class="header-section-number">10.46</span> <strong>Interpretation</strong></h2>
<p>Variances are fairly similar across groups. The main problem is <strong>mean differences</strong>, not dispersion.</p>
</section>
<section id="ecdf-mean-and-ecdf-max" class="level2" data-number="10.47">
<h2 data-number="10.47" class="anchored" data-anchor-id="ecdf-mean-and-ecdf-max"><span class="header-section-number">10.47</span> <strong>eCDF Mean and eCDF Max</strong></h2>
<p>These measure differences between the treated and control <strong>entire distributions</strong>:</p>
<ul>
<li><strong>eCDF Mean</strong>: average difference in cumulative distribution functions</li>
<li><strong>eCDF Max</strong>: maximum difference between distributions (Kolmogorov–Smirnov distance)</li>
</ul>
<p>Interpretation thresholds are less formal, but:</p>
<ul>
<li>Values &lt; <strong>0.10</strong> → good</li>
<li>Values between <strong>0.10 and 0.20</strong> → moderate imbalance</li>
<li>Values &gt; <strong>0.20</strong> → problematic imbalance</li>
</ul>
<p>our values:</p>
<ul>
<li><strong>distance eCDF Max = 0.2264</strong> → problematic</li>
<li><strong>experience eCDF Max = 0.2060</strong> → problematic</li>
<li><strong>age eCDF Max = 0.1986</strong> → moderate-to-high</li>
<li><strong>education eCDF Max = 0.1070</strong> → acceptable</li>
</ul>
</section>
<section id="interpretation-4" class="level2" data-number="10.48">
<h2 data-number="10.48" class="anchored" data-anchor-id="interpretation-4"><span class="header-section-number">10.48</span> <strong>Interpretation</strong></h2>
<p>Age, experience, and the propensity score distributions differ notably between groups.</p>
</section>
<section id="overall-interpretation" class="level2" data-number="10.49">
<h2 data-number="10.49" class="anchored" data-anchor-id="overall-interpretation"><span class="header-section-number">10.49</span> <strong>Overall Interpretation</strong></h2>
<p>our pre-matching table shows <strong>substantial imbalance</strong> between treated and control units:</p>
<ol type="1">
<li><strong>Age</strong> and <strong>experience</strong> show large standardized mean differences (&gt; 0.45).</li>
<li>The <strong>propensity score (distance)</strong> also shows a very large SMD (&gt; 0.50).</li>
<li>Distributional metrics (eCDF Max) confirm these differences.</li>
<li>Variance ratios are acceptable, so the issue is not variance but <strong>mean shifts</strong>.</li>
</ol>
<p>Before matching, treated and untreated groups are <strong>not comparable</strong>.</p>
<p>Matching is therefore <strong>necessary</strong> to construct a credible counterfactual.</p>
<p>This table is exactly what we expect in observational data: the treatment is not randomized, so individuals self-select into treatment based on characteristics like age and experience.</p>
</section>
<section id="step-3.-covariate-balance-assessment" class="level2" data-number="10.50">
<h2 data-number="10.50" class="anchored" data-anchor-id="step-3.-covariate-balance-assessment"><span class="header-section-number">10.50</span> <strong>Step 3. Covariate balance assessment</strong></h2>
<p>Diagnosing the quality of matching is essential. Graphical tools from <strong>PSAgraphics</strong> are particularly useful for evaluating whether the pre-treatment covariates are better aligned post-matching.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="co"># Before matching: do the two groups even overlap?</span></span>
<span id="cb13-4"><a href="#cb13-4"></a>df[df.treat <span class="op">==</span> <span class="dv">1</span>][<span class="st">"pscore"</span>].plot.density(label<span class="op">=</span><span class="st">"Treated"</span>)</span>
<span id="cb13-5"><a href="#cb13-5"></a>df[df.treat <span class="op">==</span> <span class="dv">0</span>][<span class="st">"pscore"</span>].plot.density(label<span class="op">=</span><span class="st">"Control"</span>)</span>
<span id="cb13-6"><a href="#cb13-6"></a>plt.xlabel(<span class="st">"Propensity score"</span>)<span class="op">;</span> plt.title(<span class="st">"Before matching"</span>)<span class="op">;</span> plt.legend()</span>
<span id="cb13-7"><a href="#cb13-7"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/decks/session-10-imported-assets-index_files-figure-revealjs-unnamed-chunk-6-1.png" class="r-stretch img-fluid" width="960"></p>
</section>
<section id="step-4.-covariate-balance-assessment-continued" class="level2" data-number="10.51">
<h2 data-number="10.51" class="anchored" data-anchor-id="step-4.-covariate-balance-assessment-continued"><span class="header-section-number">10.51</span> <strong>Step 4. Covariate balance assessment (continued)</strong></h2>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># After matching: the two distributions should sit on top of each other</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>matched[matched.treat <span class="op">==</span> <span class="dv">1</span>][<span class="st">"pscore"</span>].plot.density(label<span class="op">=</span><span class="st">"Treated"</span>)</span>
<span id="cb14-3"><a href="#cb14-3"></a>matched[matched.treat <span class="op">==</span> <span class="dv">0</span>][<span class="st">"pscore"</span>].plot.density(label<span class="op">=</span><span class="st">"Control"</span>)</span>
<span id="cb14-4"><a href="#cb14-4"></a>plt.xlabel(<span class="st">"Propensity score"</span>)<span class="op">;</span> plt.title(<span class="st">"After matching"</span>)<span class="op">;</span> plt.legend()</span>
<span id="cb14-5"><a href="#cb14-5"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/decks/session-10-imported-assets-index_files-figure-revealjs-unnamed-chunk-7-1.png" class="r-stretch img-fluid" width="960"></p>
</section>
<section id="step-5.-covariate-balance-assessment-continued" class="level2" data-number="10.52">
<h2 data-number="10.52" class="anchored" data-anchor-id="step-5.-covariate-balance-assessment-continued"><span class="header-section-number">10.52</span> <strong>Step 5. Covariate balance assessment (continued)</strong></h2>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1"></a>df.boxplot(column<span class="op">=</span><span class="st">"age"</span>, by<span class="op">=</span><span class="st">"treat"</span>)</span>
<span id="cb15-2"><a href="#cb15-2"></a>plt.suptitle(<span class="st">""</span>)<span class="op">;</span> plt.title(<span class="st">"Before matching: age"</span>)<span class="op">;</span> plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/decks/session-10-imported-assets-index_files-figure-revealjs-unnamed-chunk-8-1.png" class="r-stretch img-fluid" width="960"></p>
</section>
<section id="step-6.-covariate-balance-assessment-continued" class="level2" data-number="10.53">
<h2 data-number="10.53" class="anchored" data-anchor-id="step-6.-covariate-balance-assessment-continued"><span class="header-section-number">10.53</span> <strong>Step 6. Covariate balance assessment (continued)</strong></h2>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a>matched.boxplot(column<span class="op">=</span><span class="st">"age"</span>, by<span class="op">=</span><span class="st">"treat"</span>)</span>
<span id="cb16-2"><a href="#cb16-2"></a>plt.suptitle(<span class="st">""</span>)<span class="op">;</span> plt.title(<span class="st">"After matching: age"</span>)<span class="op">;</span> plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/decks/session-10-imported-assets-index_files-figure-revealjs-unnamed-chunk-9-1.png" class="r-stretch img-fluid" width="960"></p>
<p>Other diagnostic visuals include mirrored histograms or the “love plot” from the cobalt package, though the exercise here focuses on PSAgraphics.</p>
</section>
<section id="step-4.-estimating-the-treatment-effect-on-the-matched-sample" class="level2" data-number="10.54">
<h2 data-number="10.54" class="anchored" data-anchor-id="step-4.-estimating-the-treatment-effect-on-the-matched-sample"><span class="header-section-number">10.54</span> <strong>Step 4. Estimating the treatment effect on the matched sample</strong></h2>
<p>After matching, the dataset contains reweighted or selected observations reflecting similarity in covariate distributions. The linear model now approximates the average treatment effect on the treated (ATT). The regression does not have a causal interpretation unless matching succeeded in balancing confounders.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># The ATT: the treatment effect on the matched sample</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>att <span class="op">=</span> smf.ols(<span class="st">"outcome ~ treat"</span>, data<span class="op">=</span>matched).fit()</span>
<span id="cb17-3"><a href="#cb17-3"></a><span class="bu">print</span>(att.summary())</span>
<span id="cb17-4"><a href="#cb17-4"></a></span>
<span id="cb17-5"><a href="#cb17-5"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">ATT = </span><span class="sc">{</span>att<span class="sc">.</span>params[<span class="st">'treat'</span>]<span class="sc">:+.3f}</span><span class="ss">   (the truth we simulated is +2.5)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>Call:
lm(formula = outcome ~ treat, data = matched_df, weights = weights)

Residuals:
    Min      1Q  Median      3Q     Max 
-24.486  -6.996   0.210   6.624  33.139 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  57.1845     0.6243  91.599  &lt; 2e-16 ***
treat         2.6988     0.8829   3.057  0.00237 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.529 on 464 degrees of freedom
Multiple R-squared:  0.01974,   Adjusted R-squared:  0.01763 
F-statistic: 9.344 on 1 and 464 DF,  p-value: 0.002366</code></pre>
</div>
<p>The coefficient on <code>treat</code> corresponds to the estimated ATT. Weighting is recommended because MatchIt may assign non-unit weights even under nearest-neighbor algorithms.</p>
<p>High R² is not the goal in causal inference; unbiased estimation of the treatment effect is.</p>
</section>
<section id="step-5.-interpretation" class="level2" data-number="10.55">
<h2 data-number="10.55" class="anchored" data-anchor-id="step-5.-interpretation"><span class="header-section-number">10.55</span> <strong>Step 5. Interpretation</strong></h2>
<p>If the coefficient on <code>treat</code> is positive and statistically significant, this indicates that, conditional on observable characteristics and after matching treated individuals with comparable untreated individuals, the treatment led to an increase in the outcome <code>y</code> for the treated group. The magnitude represents the estimated average causal effect among those who actually received the treatment.</p>
<p>Interpretation must emphasize the assumptions underlying matching: unconfoundedness cannot be tested statistically, and overlap must be verified graphically. When these assumptions are plausible, propensity score matching constitutes an effective strategy for reducing selection bias in observational studies.</p>
</section>
<section id="additional-note-on-naive-difference-in-means" class="level2" data-number="10.56">
<h2 data-number="10.56" class="anchored" data-anchor-id="additional-note-on-naive-difference-in-means"><span class="header-section-number">10.56</span> <strong>Additional Note on Naive Difference-in-Means</strong></h2>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># The naive comparison, for contrast</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>df.loc[df.treat <span class="op">==</span> <span class="dv">1</span>, <span class="st">"outcome"</span>].mean() <span class="op">-</span> df.loc[df.treat <span class="op">==</span> <span class="dv">0</span>, <span class="st">"outcome"</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="text"><code>[1] 6.471933</code></pre>
</div>
<p>This does not invalidate matching.</p>
<p>It demonstrates that:</p>
<ul>
<li>although the two groups were imbalanced on age, education, and experience, these variables happened not to create a major numerical bias in the naive difference-in-means but matching greatly improves internal validity and design transparency</li>
</ul>
<blockquote class="blockquote">
<p>Matching primarily improves credibility, not necessarily magnitude.</p>
</blockquote>
</section>
<section id="your-turn" class="level2" data-number="10.57">
<h2 data-number="10.57" class="anchored" data-anchor-id="your-turn"><span class="header-section-number">10.57</span> Your turn</h2>
</section>
<section id="team-work" class="level2" data-number="10.58">
<h2 data-number="10.58" class="anchored" data-anchor-id="team-work"><span class="header-section-number">10.58</span> Team Work</h2>
<p>Team 1: <a href="https://cran.r-project.org/web/packages/MatchIt/vignettes/MatchIt.html" class="uri">https://cran.r-project.org/web/packages/MatchIt/vignettes/MatchIt.html</a></p>
<p>Team 2: <a href="https://dlab.berkeley.edu/news/introduction-propensity-score-matching-matchit" class="uri">https://dlab.berkeley.edu/news/introduction-propensity-score-matching-matchit</a></p>
<p>Team 3: <a href="https://simonejdemyr.com/r-tutorials/statistics/tutorial8.html" class="uri">https://simonejdemyr.com/r-tutorials/statistics/tutorial8.html</a> <a href="https://github.com/warint/quantitative-methods/blob/main/imported-assets/mydata.RData">data here</a></p>
<p>Team 4: <a href="https://psa.bryer.org/effects-of-tutoring-on-course-grades.html" class="uri">https://psa.bryer.org/effects-of-tutoring-on-course-grades.html</a></p>
</section>
<section id="in-the-practice" class="level2" data-number="10.59">
<h2 data-number="10.59" class="anchored" data-anchor-id="in-the-practice"><span class="header-section-number">10.59</span> In the practice</h2>
<section id="causal-inference-i-counterfactuals-randomisation-matching" class="level3" data-number="10.59.1">
<h3 data-number="10.59.1" class="anchored" data-anchor-id="causal-inference-i-counterfactuals-randomisation-matching"><span class="header-section-number">10.59.1</span> Causal Inference I: Counterfactuals, Randomisation, Matching</h3>
<blockquote class="blockquote">
<p><strong><a href="https://warint.github.io/quantitative-methods/session-10-practice.html">Open the practice slides</a></strong> · source: <a href="https://github.com/warint/quantitative-methods/blob/main/MATH60033A-S10-Practice.qmd"><code>MATH60033A-S10-Practice.qmd</code></a></p>
</blockquote>
<hr>
<section id="the-theme-of-this-session" class="level4" data-number="10.59.1.1">
<h4 data-number="10.59.1.1" class="anchored" data-anchor-id="the-theme-of-this-session"><span class="header-section-number">10.59.1.1</span> The theme of this session</h4>
<blockquote class="blockquote">
<h1 id="can-your-project-support-a-causal-claim-at-all" data-number="11"><span class="header-section-number">11</span> Can your project support a causal claim at all?</h1>
</blockquote>
<p>All ten groups attack this question, each on <strong>its own project</strong>, and the last twenty minutes assemble the answers.</p>
<hr>
</section>
<section id="what-you-are-doing" class="level4" data-number="11.0.0.1">
<h4 data-number="11.0.0.1" class="anchored" data-anchor-id="what-you-are-doing"><span class="header-section-number">11.0.0.1</span> What you are doing</h4>
<p>The lecture showed the method on the session’s dataset. You now apply it to <strong>your own angle</strong>, and to the question your group is actually trying to answer (<a href="https://github.com/warint/quantitative-methods/blob/main/RESEARCH-MANDATES.md"><code>RESEARCH-MANDATES.md</code></a>).</p>
<p>The deliverable is not a printout. It is a <strong>decision</strong>, with the reason written down.</p>
<hr>
</section>
<section id="before-you-start" class="level4" data-number="11.0.0.2">
<h4 data-number="11.0.0.2" class="anchored" data-anchor-id="before-you-start"><span class="header-section-number">11.0.0.2</span> Before you start</h4>
<p>Everyone in the group pushes at least once this session. Replace <code>XX</code> with your group number — group 07 uses <code>group-07</code>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> checkout <span class="at">-b</span> group-XX</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> 10-causal-inference-foundations/02-practice/submissions/group-XX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
<section id="reproduce-one-result-from-the-paper-20-min" class="level4" data-number="11.0.0.3">
<h4 data-number="11.0.0.3" class="anchored" data-anchor-id="reproduce-one-result-from-the-paper-20-min"><span class="header-section-number">11.0.0.3</span> 1 · Reproduce one result from the paper — 20 min</h4>
<p>Take the result the pre-session reading rests on, and reproduce it — or establish that you cannot, and say precisely where it breaks. A failed reproduction that is diagnosed earns full marks; one that is not attempted earns none.</p>
<p>The paper is <strong>Bodory, Huber &amp; Lafférs (2022), <em>Evaluating (weighted) dynamic treatment effects by double machine learning</em></strong>, and its replication package (<a href="https://doi.org/10.7910/DVN/FS0KBA">10.7910/DVN/FS0KBA</a>) should already be unzipped at:</p>
<pre class="text"><code>10-causal-inference-foundations/data/replication/</code></pre>
<p>The session’s own dataset, for comparison:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> qmib</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> qmib.load(<span class="st">"core"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
<section id="apply-the-method-to-your-own-angle-35-min" class="level4" data-number="11.0.0.4">
<h4 data-number="11.0.0.4" class="anchored" data-anchor-id="apply-the-method-to-your-own-angle-35-min"><span class="header-section-number">11.0.0.4</span> 2 · Apply the method to your own angle — 35 min</h4>
<div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>core <span class="op">=</span> qmib.load(<span class="st">"core"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>mine <span class="op">=</span> qmib.load(<span class="st">"angle_c_country"</span>)     <span class="co"># your angle — see your dictionary</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>df   <span class="op">=</span> core.merge(mine, on<span class="op">=</span>[<span class="st">"geo"</span>, <span class="st">"time"</span>], how<span class="op">=</span><span class="st">"inner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Fit the session’s method on your own data. Report what the lecture said to report, in the units of your own variables.</p>
<hr>
</section>
<section id="break-one-assumption-15-min" class="level4" data-number="11.0.0.5">
<h4 data-number="11.0.0.5" class="anchored" data-anchor-id="break-one-assumption-15-min"><span class="header-section-number">11.0.0.5</span> 3 · Break one assumption — 15 min</h4>
<p>Every method in this course rests on something. Find the assumption this one rests on hardest, break it deliberately, and record what happened to your answer. <strong>This is the part that carries the marks.</strong></p>
<hr>
</section>
<section id="write-it-down-20-min" class="level4" data-number="11.0.0.6">
<h4 data-number="11.0.0.6" class="anchored" data-anchor-id="write-it-down-20-min"><span class="header-section-number">11.0.0.6</span> 4 · Write it down — 20 min</h4>
<p>A 250-word note in your submissions folder:</p>
<ul>
<li>What you found, in units</li>
<li>Which assumption you broke, and what it did</li>
<li>What this result does <strong>not</strong> license you to claim</li>
</ul>
<hr>
</section>
<section id="submitting" class="level4" data-number="11.0.0.7">
<h4 data-number="11.0.0.7" class="anchored" data-anchor-id="submitting"><span class="header-section-number">11.0.0.7</span> Submitting</h4>
<div class="sourceCode" id="cb25"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> add 10-causal-inference-foundations/02-practice/submissions/group-XX</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> commit <span class="at">-m</span> <span class="st">"Session 10 practice — group XX"</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> push <span class="at">-u</span> origin group-XX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Everyone pushes at least once. The log is the record of participation.</p>
<hr>
</section>
<section id="what-loses-marks" class="level4" data-number="11.0.0.8">
<h4 data-number="11.0.0.8" class="anchored" data-anchor-id="what-loses-marks"><span class="header-section-number">11.0.0.8</span> What loses marks</h4>
<ul>
<li>Reporting a matched estimate with no overlap diagnostic</li>
<li>Matching on a variable affected by the treatment</li>
<li>Calling an association causal because you controlled for something</li>
<li>Omitting the balance table</li>
</ul>
<hr>
<p><a href="#the-lecture">&lt;- The lecture</a> · <a href="./session-10.html">Session 10 overview</a></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./session-09.html" class="pagination-link" aria-label="Structural Equation Modelling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structural Equation Modelling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./session-11.html" class="pagination-link" aria-label="Causal Inference II: Difference-in-Differences">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MATH60033A · HEC Montréal</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-10.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built from the course repository</p>
</div>
  </div>
</footer>




</body></html>