<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Regression: Advanced Considerations – Quantitative Methods in International Business with Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./session-07.html" rel="next">
<link href="./session-05.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-87cceeb0dc72897ec58809a022325911.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-654b0d63ec6aea178ec964394c84683d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./session-06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods in International Business with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warint/quantitative-methods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis, and the First Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression: Adequacy, Validity, and Robustness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Component and Factor Analyses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">K-Nearest Neighbours and the Bias–Variance Trade-off</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structural Equation Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Setting up your tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-api.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The data API</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./replications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Replication packages</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#one-relationship-or-thirty" id="toc-one-relationship-or-thirty" class="nav-link active" data-scroll-target="#one-relationship-or-thirty"><span class="header-section-number">6.1</span> One relationship, or thirty?</a></li>
  <li><a href="#where-the-variation-lives" id="toc-where-the-variation-lives" class="nav-link" data-scroll-target="#where-the-variation-lives"><span class="header-section-number">6.2</span> Where the variation lives</a></li>
  <li><a href="#fixed-effects-the-within-transformation" id="toc-fixed-effects-the-within-transformation" class="nav-link" data-scroll-target="#fixed-effects-the-within-transformation"><span class="header-section-number">6.3</span> Fixed effects: the within transformation</a></li>
  <li><a href="#what-fixed-effects-throws-away-and-what-it-cannot-fix" id="toc-what-fixed-effects-throws-away-and-what-it-cannot-fix" class="nav-link" data-scroll-target="#what-fixed-effects-throws-away-and-what-it-cannot-fix"><span class="header-section-number">6.4</span> What fixed effects throws away, and what it cannot fix</a></li>
  <li><a href="#two-countries-worth-of-dummies-and-a-puzzle" id="toc-two-countries-worth-of-dummies-and-a-puzzle" class="nav-link" data-scroll-target="#two-countries-worth-of-dummies-and-a-puzzle"><span class="header-section-number">6.5</span> Two countries’ worth of dummies, and a puzzle</a></li>
  <li><a href="#random-effects-and-why-the-choice-is-testable" id="toc-random-effects-and-why-the-choice-is-testable" class="nav-link" data-scroll-target="#random-effects-and-why-the-choice-is-testable"><span class="header-section-number">6.6</span> Random effects, and why the choice is testable</a></li>
  <li><a href="#clustered-standard-errors-properly-this-time" id="toc-clustered-standard-errors-properly-this-time" class="nav-link" data-scroll-target="#clustered-standard-errors-properly-this-time"><span class="header-section-number">6.7</span> Clustered standard errors, properly this time</a></li>
  <li><a href="#does-the-slope-differ-by-group-ask-it-directly" id="toc-does-the-slope-differ-by-group-ask-it-directly" class="nav-link" data-scroll-target="#does-the-slope-differ-by-group-ask-it-directly"><span class="header-section-number">6.8</span> Does the slope differ by group? Ask it directly</a></li>
  <li><a href="#yules-warning-which-predates-all-of-this" id="toc-yules-warning-which-predates-all-of-this" class="nav-link" data-scroll-target="#yules-warning-which-predates-all-of-this"><span class="header-section-number">6.9</span> Yule’s warning, which predates all of this</a></li>
  <li><a href="#get-the-functional-form-right-first" id="toc-get-the-functional-form-right-first" class="nav-link" data-scroll-target="#get-the-functional-form-right-first"><span class="header-section-number">6.10</span> Get the functional form right first</a></li>
  <li><a href="#a-short-review-of-the-literature" id="toc-a-short-review-of-the-literature" class="nav-link" data-scroll-target="#a-short-review-of-the-literature"><span class="header-section-number">6.11</span> A short review of the literature</a></li>
  <li><a href="#what-to-report" id="toc-what-to-report" class="nav-link" data-scroll-target="#what-to-report"><span class="header-section-number">6.12</span> What to report</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-06.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="one-relationship-or-thirty" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="one-relationship-or-thirty"><span class="header-section-number">6.1</span> One relationship, or thirty?</h2>
<p>Chapters 2 and 3 fitted a single line to thirty countries observed over fifteen years, and reported one slope. That slope was an answer to a question nobody had asked precisely: <em>whose</em> relationship is it? The relationship between productivity and income across countries at a moment in time, or the relationship within a country as it changes over time, are different questions with different answers, and pooling them produces a number that is neither.</p>
<p>Start by asking whether there is one relationship at all.</p>
<div id="cell-fig-heterogeneity" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys, warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>, <span class="st">"../slides"</span>)<span class="op">;</span> sys.path.insert(<span class="dv">0</span>, <span class="st">".."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotstyle <span class="im">import</span> setup, CL</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>plt <span class="op">=</span> setup()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd, statsmodels.api <span class="im">as</span> sm, qmib</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>core <span class="op">=</span> (qmib.load(<span class="st">"core"</span>).dropna(subset<span class="op">=</span>[<span class="st">"gdp_pc_eur"</span>, <span class="st">"productivity_idx"</span>])</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        .reset_index(drop<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>y, x <span class="op">=</span> <span class="st">"gdp_pc_eur"</span>, <span class="st">"productivity_idx"</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>pooled <span class="op">=</span> sm.OLS(core[y], sm.add_constant(core[[x]])).fit()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.2</span>, <span class="fl">4.8</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>slopes <span class="op">=</span> {}</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> geo, g <span class="kw">in</span> core.groupby(<span class="st">"geo"</span>):</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(g) <span class="op">&lt;</span> <span class="dv">4</span>:</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.polyfit(g[x], g[y], <span class="dv">1</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    slopes[geo] <span class="op">=</span> b[<span class="dv">0</span>]</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    gx <span class="op">=</span> np.linspace(g[x].<span class="bu">min</span>(), g[x].<span class="bu">max</span>(), <span class="dv">20</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    ax.plot(gx, np.polyval(b, gx), lw<span class="op">=</span><span class="fl">1.0</span>, color<span class="op">=</span>CL.muted, alpha<span class="op">=</span><span class="fl">0.55</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>gx <span class="op">=</span> np.linspace(core[x].<span class="bu">min</span>(), core[x].<span class="bu">max</span>(), <span class="dv">50</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>ax.plot(gx, pooled.params.iloc[<span class="dv">0</span>] <span class="op">+</span> pooled.params.iloc[<span class="dv">1</span>] <span class="op">*</span> gx,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        lw<span class="op">=</span><span class="fl">2.6</span>, color<span class="op">=</span>CL.warn, zorder<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span><span class="st">"pooled"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>ax.scatter(core[x], core[y], s<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>CL.accent, alpha<span class="op">=</span><span class="fl">0.30</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>           edgecolor<span class="op">=</span><span class="st">"none"</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"productivity index"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"GDP per capita (EUR)"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> pd.Series(slopes)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"pooled slope        </span><span class="sc">{</span>pooled<span class="sc">.</span>params<span class="sc">.</span>iloc[<span class="dv">1</span>]<span class="sc">:&gt;10,.0f}</span><span class="ss">"</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"country slopes: min </span><span class="sc">{</span>s<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:&gt;10,.0f}</span><span class="ss">   median </span><span class="sc">{</span>s<span class="sc">.</span>median()<span class="sc">:&gt;10,.0f}</span><span class="ss">   max </span><span class="sc">{</span>s<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:&gt;10,.0f}</span><span class="ss">"</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"negative in </span><span class="sc">{</span>(s <span class="op">&lt;</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(s)<span class="sc">}</span><span class="ss"> countries"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>pooled slope             1,111
country slopes: min       -975   median        219   max      3,247
negative in 8 of 30 countries</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-heterogeneity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heterogeneity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="session-06_files/figure-html/fig-heterogeneity-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heterogeneity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: One line per country, fitted separately, against the single pooled line in red. The pooled slope is not a summary of the country slopes — it is mostly a comparison between countries.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The picture is the chapter. A single steep line rises through a cloud of much flatter, and in eight cases <em>downward-sloping</em>, country lines. The pooled slope is not an average of the country slopes; it is dominated by the fact that countries with high productivity are countries with high income — a comparison <em>between</em> countries, not a description of what happens <em>within</em> one.</p>
<p>Whether that is the quantity you want depends entirely on the claim you intend to make. If the claim is “countries with higher productivity are richer”, the pooled estimate is the right object. If the claim is “raising productivity raises income”, it is close to useless, because the second claim is about movement within a country and the first estimate contains almost none of it.</p>
</section>
<section id="where-the-variation-lives" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="where-the-variation-lives"><span class="header-section-number">6.2</span> Where the variation lives</h2>
<p>The reason is arithmetic, and it can be inspected before any model is fitted. Total variation in a panel variable splits into variation <em>between</em> units and variation <em>within</em> them, and a regression uses whichever is left after the controls have absorbed the rest.</p>
<div id="check-decomposition" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Run it: between and within variation</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>core[<span class="st">"log_gdp"</span>] <span class="op">=</span> np.log(core[y])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'variable'</span><span class="sc">:20}{</span><span class="st">'total var'</span><span class="sc">:&gt;12}{</span><span class="st">'within'</span><span class="sc">:&gt;10}{</span><span class="st">'between'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> [x, <span class="st">"log_gdp"</span>]:</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    tot <span class="op">=</span> core[c].var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    within <span class="op">=</span> (core[c] <span class="op">-</span> core.groupby(<span class="st">"geo"</span>)[c].transform(<span class="st">"mean"</span>)).var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:20}{</span>tot<span class="sc">:12.4f}{</span>within<span class="op">/</span>tot<span class="sc">:9.1%}{</span><span class="dv">1</span> <span class="op">-</span> within<span class="op">/</span>tot<span class="sc">:10.1%}</span><span class="ss">"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">mean annual drift:"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> [x, <span class="st">"log_gdp"</span>]:</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>c<span class="sc">:20}{</span>np<span class="sc">.</span>polyfit(core[<span class="st">'time'</span>], core[c], <span class="dv">1</span>)[<span class="dv">0</span>]<span class="sc">:+10.4f}</span><span class="ss"> per year"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>variable               total var    within   between
productivity_idx        119.5167    29.6%     70.4%
log_gdp                   0.2484    13.9%     86.1%

mean annual drift:
  productivity_idx       +0.9671 per year
  log_gdp                -0.0076 per year</code></pre>
</div>
</div>
<p>Two facts from that output govern everything below. The great majority of the variation in both variables is <em>between</em> countries — 70% for productivity, 86% for log income — so a pooled regression is overwhelmingly a cross-sectional comparison wearing panel clothing. And productivity drifts upward by about one index point a year while log income does not drift at all, which means the within-country variation in the predictor is substantially a common trend that the outcome does not share.</p>
</section>
<section id="fixed-effects-the-within-transformation" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="fixed-effects-the-within-transformation"><span class="header-section-number">6.3</span> Fixed effects: the within transformation</h2>
<p>The standard response is to give each country its own intercept:</p>
<p><span class="math display">\[
y_{it} \;=\; \alpha_i + \beta x_{it} + \varepsilon_{it} .
\]</span></p>
<p>The <span class="math inline">\(\alpha_i\)</span> absorb everything about a country that does not change over the sample — institutions, geography, legal tradition, whatever is durable — whether or not you can measure it or even name it. That is the appeal, and it is a large one: an unmeasured confounder that is constant within a country cannot bias <span class="math inline">\(\hat\beta\)</span>, because it has been differenced away.</p>
<p>There are three equivalent ways to compute it, and their equivalence is Frisch–Waugh–Lovell from chapter 2 in a new costume. Include a dummy for each country. Or subtract each country’s mean from each variable and regress the demeaned outcome on the demeaned predictor. Or partial the dummies out of both sides and regress residual on residual. All three are the same estimator.</p>
<div id="check-within" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Run it: fixed effects, three ways, one number</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) demeaning — the "within" transformation</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dm <span class="op">=</span> core.copy()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> [y, x]:</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    dm[c <span class="op">+</span> <span class="st">"_w"</span>] <span class="op">=</span> dm[c] <span class="op">-</span> dm.groupby(<span class="st">"geo"</span>)[c].transform(<span class="st">"mean"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>within <span class="op">=</span> sm.OLS(dm[y <span class="op">+</span> <span class="st">"_w"</span>], dm[[x <span class="op">+</span> <span class="st">"_w"</span>]]).fit()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) a dummy for every country</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>geo_d <span class="op">=</span> pd.get_dummies(core[<span class="st">"geo"</span>], drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>dummies <span class="op">=</span> sm.OLS(core[y], sm.add_constant(pd.concat([core[[x]], geo_d], axis<span class="op">=</span><span class="dv">1</span>))).fit()</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) a purpose-built panel estimator</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> linearmodels.panel <span class="im">import</span> PanelOLS</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> core.set_index([<span class="st">"geo"</span>, <span class="st">"time"</span>])</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>fe <span class="op">=</span> PanelOLS(panel[y], sm.add_constant(panel[[x]]), entity_effects<span class="op">=</span><span class="va">True</span>).fit()</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"pooled                        </span><span class="sc">{</span>pooled<span class="sc">.</span>params<span class="sc">.</span>iloc[<span class="dv">1</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"within, by demeaning          </span><span class="sc">{</span>within<span class="sc">.</span>params<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"within, by country dummies    </span><span class="sc">{</span>dummies<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"within, by PanelOLS           </span><span class="sc">{</span>fe<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">the pooled slope is </span><span class="sc">{</span>pooled<span class="sc">.</span>params<span class="sc">.</span>iloc[<span class="dv">1</span>]<span class="op">/</span>fe<span class="sc">.</span>params[x]<span class="sc">:.1f}</span><span class="ss">x the within slope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>pooled                            1,111.26
within, by demeaning                274.59
within, by country dummies          274.59
within, by PanelOLS                 274.59

the pooled slope is 4.0x the within slope</code></pre>
</div>
</div>
<p>The three agree exactly, and the pooled slope is four times the within slope. That gap is the quantitative version of the picture above: three quarters of the pooled estimate was between-country comparison, and it disappears the moment each country is allowed its own level.</p>
</section>
<section id="what-fixed-effects-throws-away-and-what-it-cannot-fix" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="what-fixed-effects-throws-away-and-what-it-cannot-fix"><span class="header-section-number">6.4</span> What fixed effects throws away, and what it cannot fix</h2>
<p>Fixed effects are not free, and the costs are systematically undersold.</p>
<p><strong>Anything constant within a unit becomes inestimable.</strong> A country’s legal origin, its language, its distance from the equator — all absorbed, none estimable. If the effect you care about is a time-invariant characteristic, fixed effects delete your research question rather than answering it.</p>
<p><strong>The estimator uses only within variation, so precision falls.</strong> Here that is 70% of the variation in the predictor discarded. If the within variation is small or badly measured, fixed effects trade bias for a great deal of variance — and measurement error is <em>amplified</em> by demeaning, because differencing removes signal while leaving noise.</p>
<p><strong>Time-varying confounders survive untouched.</strong> The reassurance that “fixed effects control for unobserved heterogeneity” holds only for heterogeneity that does not move. Anything that changes within a country over the sample period — a reform, a business cycle, a shock — passes straight through.</p>
</section>
<section id="two-countries-worth-of-dummies-and-a-puzzle" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="two-countries-worth-of-dummies-and-a-puzzle"><span class="header-section-number">6.5</span> Two countries’ worth of dummies, and a puzzle</h2>
<p>Time shocks are the obvious example of a confounder that fixed effects do not remove. A recession that hits every country at once creates common movement in both variables that has nothing to do with the relationship of interest. The remedy is a second set of dummies, one per year:</p>
<p><span class="math display">\[
y_{it} \;=\; \alpha_i + \gamma_t + \beta x_{it} + \varepsilon_{it} .
\]</span></p>
<p>The identifying variation is now what remains after both country means and year means have been removed — the purely idiosyncratic part of each observation.</p>
<div id="check-twoway" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Run it: add year effects, and look at what happens</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>two <span class="op">=</span> PanelOLS(panel[y], sm.add_constant(panel[[x]]),</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>               entity_effects<span class="op">=</span><span class="va">True</span>, time_effects<span class="op">=</span><span class="va">True</span>).fit()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'specification'</span><span class="sc">:32}{</span><span class="st">'slope'</span><span class="sc">:&gt;12}</span><span class="ss">"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'pooled'</span><span class="sc">:32}{</span>pooled<span class="sc">.</span>params<span class="sc">.</span>iloc[<span class="dv">1</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'country effects'</span><span class="sc">:32}{</span>fe<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'country + year effects'</span><span class="sc">:32}{</span>two<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>specification                          slope
pooled                              1,111.26
country effects                       274.59
country + year effects              1,149.28</code></pre>
</div>
</div>
<p>That is not a typographical error, and it is not a bug — a design matrix built by hand with 45 columns of full rank returns the same number. Adding year effects moves the slope from 275 back up past the pooled estimate, to about 1,149. Three defensible specifications give answers spanning a factor of four, and a reader shown any one of them alone would draw a different conclusion.</p>
<p>The explanation is available here in a way it almost never is in real work, because these are fixtures and the generator is in the repository. Productivity was constructed with a deterministic trend of <span class="math inline">\(+1.15\)</span> index points per year; income was not given one. So the within-country variation in the predictor is dominated by a common upward drift that the outcome does not share — variation in <span class="math inline">\(x\)</span> with no matching variation in <span class="math inline">\(y\)</span>, which attenuates the slope toward zero. That is the 275. Year effects remove precisely that common drift, along with the COVID shock the generator applied to both. What is left is idiosyncratic country-year movement, in which the same latent factor drives both variables strongly — and the slope comes back up.</p>
<p>The general lesson survives the specific example. <strong>Each specification identifies <span class="math inline">\(\beta\)</span> from a different slice of the variation, and if the slices carry different signal-to-noise ratios the estimates will differ — not because one is wrong, but because they are answering different questions.</strong> Reporting a specification without saying which variation identifies it is reporting half a result. This is also why the modern literature is careful about two-way fixed effects when effects are heterogeneous: the estimator is a weighted average of many comparisons, and the weights are not always the ones you would choose <span class="citation" data-cites="dechaisemartin2020">(<a href="#ref-dechaisemartin2020" role="doc-biblioref">Chaisemartin and D’Haultfœuille 2020</a>)</span>.</p>
</section>
<section id="random-effects-and-why-the-choice-is-testable" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="random-effects-and-why-the-choice-is-testable"><span class="header-section-number">6.6</span> Random effects, and why the choice is testable</h2>
<p>The alternative treats the unit effects as draws from a distribution rather than as parameters:</p>
<p><span class="math display">\[
y_{it} \;=\; \mu + \beta x_{it} + u_i + \varepsilon_{it},
\qquad u_i \sim (0, \sigma_u^2) .
\]</span></p>
<p>This is more efficient when it is true, because it uses between as well as within variation, and it keeps time-invariant regressors estimable. It buys that with a strong assumption: <span class="math inline">\(u_i\)</span> must be uncorrelated with the regressors. If countries with high unobserved capacity also have high productivity — which is exactly what the fixture’s four country types encode — the assumption fails and random effects are biased.</p>
<p>The comparison is testable, because fixed effects are consistent whether or not the assumption holds while random effects are consistent only if it does. A systematic difference between the two therefore indicts the assumption <span class="citation" data-cites="hausman1978">(<a href="#ref-hausman1978" role="doc-biblioref">Hausman 1978</a>)</span>. Mundlak’s reformulation is the more illuminating one: include each unit’s <em>mean</em> of the regressors alongside the regressors themselves, and the coefficient on the mean tests exactly the correlation at issue — turning the specification test into a coefficient you can look at <span class="citation" data-cites="mundlak1978">(<a href="#ref-mundlak1978" role="doc-biblioref">Mundlak 1978</a>)</span>.</p>
<div id="check-mundlak" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Run it: Mundlak’s version of the specification test</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> linearmodels.panel <span class="im">import</span> RandomEffects</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>re_fit <span class="op">=</span> RandomEffects(panel[y], sm.add_constant(panel[[x]])).fit()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"random effects slope   </span><span class="sc">{</span>re_fit<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fixed effects slope    </span><span class="sc">{</span>fe<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mundlak: add the country mean of x to a pooled regression.</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>aug <span class="op">=</span> core.copy()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>aug[<span class="st">"x_mean"</span>] <span class="op">=</span> aug.groupby(<span class="st">"geo"</span>)[x].transform(<span class="st">"mean"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>mund <span class="op">=</span> sm.OLS(aug[y], sm.add_constant(aug[[x, <span class="st">"x_mean"</span>]])).fit(</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    cov_type<span class="op">=</span><span class="st">"cluster"</span>, cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: aug[<span class="st">"geo"</span>]})</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Mundlak regression (clustered by country):"</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  within coefficient on </span><span class="sc">{</span>x<span class="sc">:18}</span><span class="ss"> </span><span class="sc">{</span>mund<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  coefficient on the country mean          </span><span class="sc">{</span>mund<span class="sc">.</span>params[<span class="st">'x_mean'</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   p = </span><span class="sc">{</span>mund<span class="sc">.</span>pvalues[<span class="st">'x_mean'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">A country mean that matters is a unit effect correlated with the"</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"regressor — which is the random-effects assumption failing."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>random effects slope         817.47
fixed effects slope          274.59

Mundlak regression (clustered by country):
  within coefficient on productivity_idx         274.59
  coefficient on the country mean              1,187.89   p = 0.0000

A country mean that matters is a unit effect correlated with the
regressor — which is the random-effects assumption failing.</code></pre>
</div>
</div>
</section>
<section id="clustered-standard-errors-properly-this-time" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="clustered-standard-errors-properly-this-time"><span class="header-section-number">6.7</span> Clustered standard errors, properly this time</h2>
<p>Chapter 3 showed that clustering by country raised the standard error on the pooled slope by about three quarters, and deferred the explanation. Here it is.</p>
<p>The classical formula assumes each of the 428 rows contributes independent information. It does not: residuals within a country are strongly correlated, so thirty countries observed fifteen times carry far less information than 450 independent observations would. The cluster-robust estimator replaces the independence assumption with independence <em>between</em> clusters, allowing arbitrary correlation within:</p>
<p><span class="math display">\[
\widehat{\operatorname{Var}}(\hat\beta)
= (X^\top X)^{-1}
\Big( \sum_{g=1}^{G} X_g^\top e_g e_g^\top X_g \Big)
(X^\top X)^{-1} .
\]</span></p>
<p>The sandwich is the same shape as chapter 3’s White estimator; only the middle changes, from a sum over observations to a sum over groups.</p>
<div id="check-clustering" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Run it: the same coefficient, five uncertainties</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'standard errors'</span><span class="sc">:34}{</span><span class="st">'SE'</span><span class="sc">:&gt;10}{</span><span class="st">'t'</span><span class="sc">:&gt;8}{</span><span class="st">'95% CI half-width'</span><span class="sc">:&gt;20}</span><span class="ss">"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>variants <span class="op">=</span> [</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"classical"</span>, <span class="bu">dict</span>()),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"HC3 (heteroscedasticity only)"</span>, <span class="bu">dict</span>(cov_type<span class="op">=</span><span class="st">"HC3"</span>)),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"clustered by country (30)"</span>, <span class="bu">dict</span>(cov_type<span class="op">=</span><span class="st">"cluster"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                                       cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: core[<span class="st">"geo"</span>]})),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"clustered by year (15)"</span>, <span class="bu">dict</span>(cov_type<span class="op">=</span><span class="st">"cluster"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                                    cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: core[<span class="st">"time"</span>]})),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># statsmodels needs numeric group codes for two-way clustering.</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"two-way clustered"</span>, <span class="bu">dict</span>(cov_type<span class="op">=</span><span class="st">"cluster"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                               cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: np.column_stack([</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                                   pd.factorize(core[<span class="st">"geo"</span>])[<span class="dv">0</span>],</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                                   pd.factorize(core[<span class="st">"time"</span>])[<span class="dv">0</span>]])})),</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, kw <span class="kw">in</span> variants:</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> sm.OLS(core[y], sm.add_constant(core[[x]])).fit(<span class="op">**</span>kw)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    b, se <span class="op">=</span> f.params.iloc[<span class="dv">1</span>], f.bse.iloc[<span class="dv">1</span>]</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">:34}{</span>se<span class="sc">:10.2f}{</span>b<span class="op">/</span>se<span class="sc">:8.2f}{</span><span class="fl">1.96</span><span class="op">*</span>se<span class="sc">:20,.0f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>standard errors                           SE       t   95% CI half-width
classical                              41.50   26.77                  81
HC3 (heteroscedasticity only)          43.24   25.70                  85
clustered by country (30)              72.30   15.37                 142
clustered by year (15)                 74.28   14.96                 146
two-way clustered                      94.34   11.78                 185</code></pre>
</div>
</div>
<p>Three points of discipline. <strong>Cluster at the level at which shocks arrive</strong>, not at the level that gives the answer you prefer — and if you are unsure, the question is about the sampling process rather than the data <span class="citation" data-cites="abadie2022">(<a href="#ref-abadie2022" role="doc-biblioref">Abadie et al. 2022</a>)</span>. <strong>The number of clusters is what matters, not the number of observations</strong>: with thirty countries the asymptotics are thin, and with fewer than about forty clusters the cluster-robust estimator understates uncertainty and a bootstrap is the better tool. And <strong>clustering is not a fix for a misspecified model</strong> — it widens the interval around whatever the specification estimates, correct or not.</p>
</section>
<section id="does-the-slope-differ-by-group-ask-it-directly" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="does-the-slope-differ-by-group-ask-it-directly"><span class="header-section-number">6.8</span> Does the slope differ by group? Ask it directly</h2>
<p>Heterogeneity can be modelled rather than absorbed. An interaction lets the slope itself vary:</p>
<p><span class="math display">\[
y_{it} \;=\; \alpha_i + \beta x_{it} + \delta\,(x_{it} \times g_i) + \varepsilon_{it},
\]</span></p>
<p>where <span class="math inline">\(g_i\)</span> marks a group. The coefficient <span class="math inline">\(\delta\)</span> <em>is</em> the difference in slopes, so its standard error is the test — which is the right way to compare two groups, rather than fitting separately and eyeballing whether intervals overlap, an error chapter 2 warned about.</p>
<div id="check-interaction" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Run it: is the relationship the same in high- and low-income countries?</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>med <span class="op">=</span> core.groupby(<span class="st">"geo"</span>)[y].mean().median()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>core[<span class="st">"rich"</span>] <span class="op">=</span> (core.groupby(<span class="st">"geo"</span>)[y].transform(<span class="st">"mean"</span>) <span class="op">&gt;</span> med).astype(<span class="bu">float</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>core[<span class="st">"x_rich"</span>] <span class="op">=</span> core[x] <span class="op">*</span> core[<span class="st">"rich"</span>]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>inter <span class="op">=</span> sm.OLS(core[y], sm.add_constant(core[[x, <span class="st">"rich"</span>, <span class="st">"x_rich"</span>]])).fit(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    cov_type<span class="op">=</span><span class="st">"cluster"</span>, cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: core[<span class="st">"geo"</span>]})</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"slope in lower-income countries      </span><span class="sc">{</span>inter<span class="sc">.</span>params[x]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"difference in slope (interaction)    </span><span class="sc">{</span>inter<span class="sc">.</span>params[<span class="st">'x_rich'</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   p = </span><span class="sc">{</span>inter<span class="sc">.</span>pvalues[<span class="st">'x_rich'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"slope in higher-income countries     "</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>inter<span class="sc">.</span>params[x] <span class="op">+</span> inter<span class="sc">.</span>params[<span class="st">'x_rich'</span>]<span class="sc">:&gt;12,.2f}</span><span class="ss">"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">The interaction coefficient is the difference, so its p-value tests"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"the difference — which is the comparison you actually wanted."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>slope in lower-income countries            450.95
difference in slope (interaction)          789.93   p = 0.0000
slope in higher-income countries         1,240.88

The interaction coefficient is the difference, so its p-value tests
the difference — which is the comparison you actually wanted.</code></pre>
</div>
</div>
</section>
<section id="yules-warning-which-predates-all-of-this" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="yules-warning-which-predates-all-of-this"><span class="header-section-number">6.9</span> Yule’s warning, which predates all of this</h2>
<div class="archive">
<p><span class="archive-label">From the archive · Yule, 1903</span></p>
<p>Long before panel data existed, George Udny Yule showed that an association present in every subgroup of a table can vanish or reverse when the subgroups are combined, purely as an artefact of how the groups differ in size and composition <span class="citation" data-cites="yule1903">(<a href="#ref-yule1903" role="doc-biblioref">Yule 1903</a>)</span>. Simpson revisited it half a century later, and the phenomenon carries his name in most textbooks and Yule’s in the careful ones <span class="citation" data-cites="simpson1951">(<a href="#ref-simpson1951" role="doc-biblioref">Simpson 1951</a>)</span>.</p>
<p>The eight countries with negative slopes in the opening figure are the same phenomenon in continuous form. A relationship that is negative within most units and strongly positive across them is not a contradiction and not a paradox — it is two different quantities, and the aggregate one is a weighted comparison between units that happens to run the other way.</p>
<p>The lesson is not that the aggregate is wrong. It is that <strong>the direction of an association is a property of the level of aggregation, not of the world</strong>, and that reporting one level without naming it is how the same data support opposite policy conclusions.</p>
</div>
</section>
<section id="get-the-functional-form-right-first" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="get-the-functional-form-right-first"><span class="header-section-number">6.10</span> Get the functional form right first</h2>
<p>One more result belongs here, because it is a chapter 3 loose end and a warning against reaching for panel machinery too early.</p>
<p>Chapter 3 found curvature in the residuals of the level-on-level regression and reported it as a specification failure. It was. The generator writes income as <em>exponential</em> in the latent factor and productivity as <em>linear</em> in it, so the true relationship between the two is log-linear, and no amount of fixed effects or clustering repairs a model fitted on the wrong scale.</p>
<div id="check-logform" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Run it: the same panel, on the right scale</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.nonparametric.smoothers_lowess <span class="im">import</span> lowess</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'specification'</span><span class="sc">:28}{</span><span class="st">'R²'</span><span class="sc">:&gt;8}{</span><span class="st">'residual curvature'</span><span class="sc">:&gt;22}</span><span class="ss">"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, yv <span class="kw">in</span> [(<span class="st">"level of income"</span>, core[y]), (<span class="st">"log of income"</span>, core[<span class="st">"log_gdp"</span>])]:</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> sm.OLS(yv, sm.add_constant(core[[x]])).fit()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> m.resid <span class="op">/</span> m.resid.std()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    sm_line <span class="op">=</span> lowess(r, m.fittedvalues, frac<span class="op">=</span><span class="fl">0.5</span>, return_sorted<span class="op">=</span><span class="va">True</span>)[:, <span class="dv">1</span>]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">:28}{</span>m<span class="sc">.</span>rsquared<span class="sc">:8.4f}{</span>sm_line<span class="sc">.</span><span class="bu">max</span>() <span class="op">-</span> sm_line<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:22.3f}</span><span class="ss">"</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">(curvature = range of the smoother through the standardised residuals;"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">" smaller is flatter is better specified)"</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>log_fe <span class="op">=</span> PanelOLS(panel.assign(log_gdp<span class="op">=</span>np.log(panel[y]))[<span class="st">"log_gdp"</span>],</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>                  sm.add_constant(panel[[x]]), entity_effects<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>                  time_effects<span class="op">=</span><span class="va">True</span>).fit()</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">two-way FE on log income: </span><span class="sc">{</span>log_fe<span class="sc">.</span>params[x]<span class="sc">:+.5f}</span><span class="ss"> per index point"</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  = </span><span class="sc">{</span>(np.exp(log_fe.params[x]) <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.3f}</span><span class="ss">% per index point"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>specification                     R²    residual curvature
level of income               0.6273                 2.037
log of income                 0.7410                 1.404

(curvature = range of the smoother through the standardised residuals;
 smaller is flatter is better specified)

two-way FE on log income: +0.03441 per index point
  = +3.501% per index point</code></pre>
</div>
</div>
<p>On the log scale the coefficient also becomes interpretable in the way economists want: a semi-elasticity, readable as a percentage change per unit of the predictor. That is not a cosmetic gain. “Zero point six per cent per index point” is a sentence a reader can check against their own knowledge; “1,149 euros per index point” is one they cannot, because it depends on the level.</p>
</section>
<section id="a-short-review-of-the-literature" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="a-short-review-of-the-literature"><span class="header-section-number">6.11</span> A short review of the literature</h2>
<div class="lit">
<p>The pooling problem is old. <span class="citation" data-cites="yule1903">Yule (<a href="#ref-yule1903" role="doc-biblioref">1903</a>)</span> demonstrated that associations reverse under aggregation, and <span class="citation" data-cites="simpson1951">Simpson (<a href="#ref-simpson1951" role="doc-biblioref">1951</a>)</span> gave the phenomenon its modern textbook treatment and, unfairly, its name.</p>
<p>The fixed-versus-random choice was settled as a testable proposition by <span class="citation" data-cites="hausman1978">Hausman (<a href="#ref-hausman1978" role="doc-biblioref">1978</a>)</span>, whose test compares the two estimators on the logic that only one of them is consistent under the null. <span class="citation" data-cites="mundlak1978">Mundlak (<a href="#ref-mundlak1978" role="doc-biblioref">1978</a>)</span> reframed it more usefully: the random-effects estimator is a fixed-effects estimator with a restriction, and adding the unit means of the regressors makes the restriction a coefficient you can test directly. Mundlak’s formulation is easier to teach and harder to misapply, and it is the one used above.</p>
<p>Two literatures complicate the modern picture. On standard errors, <span class="citation" data-cites="abadie2022">Abadie et al. (<a href="#ref-abadie2022" role="doc-biblioref">2022</a>)</span> argues that clustering is a question about the sampling and assignment process rather than a default to be applied, and that clustering when it is not needed costs precision for nothing. On the estimator itself, <span class="citation" data-cites="dechaisemartin2020">Chaisemartin and D’Haultfœuille (<a href="#ref-dechaisemartin2020" role="doc-biblioref">2020</a>)</span> shows that two-way fixed effects with heterogeneous effects is a weighted average of comparisons whose weights can be negative, which is a substantive problem rather than a technicality and returns in chapter 11.</p>
<p><span class="citation" data-cites="nickell1981">Nickell (<a href="#ref-nickell1981" role="doc-biblioref">1981</a>)</span> is the classic result on what goes wrong when a lagged outcome is added to a fixed-effects model: the demeaning correlates the lag with the error, biasing the estimate by an amount that shrinks only as the number of periods grows. With fifteen years, that bias is not negligible.</p>
</div>
</section>
<section id="what-to-report" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="what-to-report"><span class="header-section-number">6.12</span> What to report</h2>
<ol type="1">
<li><strong>Which variation identifies the estimate.</strong> Between, within, or within-and-within. State it, because the estimates differ by factors here and a reader cannot infer it from the coefficient.</li>
<li><strong>More than one specification, side by side.</strong> Pooled, one-way, two-way. If they disagree, that disagreement is a finding and hiding it is a choice.</li>
<li><strong>What the fixed effects absorbed</strong>, and therefore what you can no longer estimate. If your question concerns a time-invariant characteristic, say that fixed effects cannot answer it.</li>
<li><strong>The clustering level, with the reason.</strong> How many clusters, why that level, and — below about forty — what you did about it.</li>
<li><strong>Heterogeneity tested, not assumed.</strong> An interaction coefficient with its standard error, not two subgroup regressions compared by eye.</li>
<li><strong>The functional form, checked before the panel machinery.</strong> Fixed effects on the wrong scale is a precise answer to the wrong question.</li>
<li><strong>What none of it identifies.</strong> Fixed effects remove time-invariant confounders and nothing else. Time-varying confounding, reverse causation and selection all survive, and chapters 10 and 11 are about what it takes to address them.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-abadie2022" class="csl-entry" role="listitem">
Abadie, Alberto, Susan Athey, Guido W Imbens, and Jeffrey M Wooldridge. 2022. <span>“<span>When</span> <span>Should</span> <span>You</span> <span>Adjust</span> <span>Standard</span> <span>Errors</span> for <span>Clustering</span>?”</span> <em><span>The</span> <span>Quarterly</span> <span>Journal</span> of <span>Economics</span></em> 138 (1): 1–35. <a href="https://doi.org/10.1093/qje/qjac038">https://doi.org/10.1093/qje/qjac038</a>.
</div>
<div id="ref-dechaisemartin2020" class="csl-entry" role="listitem">
Chaisemartin, Clément de, and Xavier D’Haultfœuille. 2020. <span>“<span>Two</span>-<span>Way</span> <span>Fixed</span> <span>Effects</span> <span>Estimators</span> with <span>Heterogeneous</span> <span>Treatment</span> <span>Effects</span>.”</span> <em><span>American</span> <span>Economic</span> <span>Review</span></em> 110 (9): 2964–96. <a href="https://doi.org/10.1257/aer.20181169">https://doi.org/10.1257/aer.20181169</a>.
</div>
<div id="ref-hausman1978" class="csl-entry" role="listitem">
Hausman, J. A. 1978. <span>“<span>Specification</span> <span>Tests</span> in <span>Econometrics</span>.”</span> <em><span>Econometrica</span></em> 46 (6): 1251. <a href="https://doi.org/10.2307/1913827">https://doi.org/10.2307/1913827</a>.
</div>
<div id="ref-mundlak1978" class="csl-entry" role="listitem">
Mundlak, Yair. 1978. <span>“<span>On</span> the <span>Pooling</span> of <span>Time</span> <span>Series</span> and <span>Cross</span> <span>Section</span> <span>Data</span>.”</span> <em><span>Econometrica</span></em> 46 (1): 69. <a href="https://doi.org/10.2307/1913646">https://doi.org/10.2307/1913646</a>.
</div>
<div id="ref-nickell1981" class="csl-entry" role="listitem">
Nickell, Stephen. 1981. <span>“<span>Biases</span> in <span>Dynamic</span> <span>Models</span> with <span>Fixed</span> <span>Effects</span>.”</span> <em><span>Econometrica</span></em> 49 (6): 1417. <a href="https://doi.org/10.2307/1911408">https://doi.org/10.2307/1911408</a>.
</div>
<div id="ref-simpson1951" class="csl-entry" role="listitem">
Simpson, E. H. 1951. <span>“<span>The</span> <span>Interpretation</span> of <span>Interaction</span> in <span>Contingency</span> <span>Tables</span>.”</span> <em><span>Journal</span> of the <span>Royal</span> <span>Statistical</span> <span>Society</span> <span>Series</span> B: <span>Statistical</span> <span>Methodology</span></em> 13 (2): 238–41. <a href="https://doi.org/10.1111/j.2517-6161.1951.tb00088.x">https://doi.org/10.1111/j.2517-6161.1951.tb00088.x</a>.
</div>
<div id="ref-yule1903" class="csl-entry" role="listitem">
Yule, G. UNDY. 1903. <span>“<span>NOTES</span> <span>ON</span> <span>THE</span> <span>THEORY</span> <span>OF</span> <span>ASSOCIATION</span> <span>OF</span> <span>ATTRIBUTES</span> <span>IN</span> <span>STATISTICS</span>.”</span> <em><span>Biometrika</span></em> 2 (2): 121–34. <a href="https://doi.org/10.1093/biomet/2.2.121">https://doi.org/10.1093/biomet/2.2.121</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./session-05.html" class="pagination-link" aria-label="Regularisation: Ridge, Lasso, and the Elastic Net">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./session-07.html" class="pagination-link" aria-label="Principal Component and Factor Analyses">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Component and Factor Analyses</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MATH60033A · HEC Montréal</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-06.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built from the course repository</p>
</div>
  </div>
</footer>




</body></html>