<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Logistic Regression: Binary, Ordinal, and Multinomial – Quantitative Methods in International Business with Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./session-05.html" rel="next">
<link href="./session-03.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-87cceeb0dc72897ec58809a022325911.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-654b0d63ec6aea178ec964394c84683d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./session-04.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods in International Business with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warint/quantitative-methods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis, and the First Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression: Adequacy, Validity, and Robustness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-04.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Component and Factor Analyses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">K-Nearest Neighbours and the Bias–Variance Trade-off</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structural Equation Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Setting up your tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-api.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The data API</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./replications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Replication packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./further-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Further reading</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#when-the-outcome-is-a-category" id="toc-when-the-outcome-is-a-category" class="nav-link active" data-scroll-target="#when-the-outcome-is-a-category"><span class="header-section-number">4.1</span> When the outcome is a category</a></li>
  <li><a href="#the-logistic-function-and-where-it-came-from" id="toc-the-logistic-function-and-where-it-came-from" class="nav-link" data-scroll-target="#the-logistic-function-and-where-it-came-from"><span class="header-section-number">4.2</span> The logistic function, and where it came from</a></li>
  <li><a href="#estimation-no-formula-and-why-that-is-fine" id="toc-estimation-no-formula-and-why-that-is-fine" class="nav-link" data-scroll-target="#estimation-no-formula-and-why-that-is-fine"><span class="header-section-number">4.3</span> Estimation: no formula, and why that is fine</a></li>
  <li><a href="#reading-the-coefficients" id="toc-reading-the-coefficients" class="nav-link" data-scroll-target="#reading-the-coefficients"><span class="header-section-number">4.4</span> Reading the coefficients</a></li>
  <li><a href="#comparing-models-the-likelihood-ratio-test" id="toc-comparing-models-the-likelihood-ratio-test" class="nav-link" data-scroll-target="#comparing-models-the-likelihood-ratio-test"><span class="header-section-number">4.5</span> Comparing models: the likelihood-ratio test</a></li>
  <li><a href="#does-the-model-discriminate-and-is-it-calibrated" id="toc-does-the-model-discriminate-and-is-it-calibrated" class="nav-link" data-scroll-target="#does-the-model-discriminate-and-is-it-calibrated"><span class="header-section-number">4.6</span> Does the model discriminate, and is it calibrated?</a></li>
  <li><a href="#when-the-outcome-is-ordered" id="toc-when-the-outcome-is-ordered" class="nav-link" data-scroll-target="#when-the-outcome-is-ordered"><span class="header-section-number">4.7</span> When the outcome is ordered</a></li>
  <li><a href="#when-the-categories-have-no-order" id="toc-when-the-categories-have-no-order" class="nav-link" data-scroll-target="#when-the-categories-have-no-order"><span class="header-section-number">4.8</span> When the categories have no order</a></li>
  <li><a href="#the-failure-mode-worth-knowing" id="toc-the-failure-mode-worth-knowing" class="nav-link" data-scroll-target="#the-failure-mode-worth-knowing"><span class="header-section-number">4.9</span> The failure mode worth knowing</a></li>
  <li><a href="#a-short-review-of-the-literature" id="toc-a-short-review-of-the-literature" class="nav-link" data-scroll-target="#a-short-review-of-the-literature"><span class="header-section-number">4.10</span> A short review of the literature</a></li>
  <li><a href="#what-to-report" id="toc-what-to-report" class="nav-link" data-scroll-target="#what-to-report"><span class="header-section-number">4.11</span> What to report</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-04.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="when-the-outcome-is-a-category" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="when-the-outcome-is-a-category"><span class="header-section-number">4.1</span> When the outcome is a category</h2>
<p>Everything so far has predicted a number. Most decisions are not numbers. Does this borrower default. Does this firm export. Does this country adopt the regulation. The outcome is a category, and the machinery of chapters 2 and 3 does not transfer intact.</p>
<p>The obvious move is to code the outcome as 0 and 1 and fit least squares to it anyway. That is the <em>linear probability model</em>, and it is not absurd — the fitted values estimate <span class="math inline">\(\operatorname{E}[y \mid x]\)</span>, which for a binary variable is exactly <span class="math inline">\(\Pr(y = 1 \mid x)\)</span>, and the coefficients read directly as changes in probability, which is what people want. It is used in serious applied work.</p>
<p>It also breaks in three specific ways, and being precise about which matters.</p>
<div id="check-lpm" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Run it: fit a probability with a straight line</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys, warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>, <span class="st">"../slides"</span>)<span class="op">;</span> sys.path.insert(<span class="dv">0</span>, <span class="st">".."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotstyle <span class="im">import</span> setup, CL</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>plt <span class="op">=</span> setup()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd, statsmodels.api <span class="im">as</span> sm, qmib</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>loans <span class="op">=</span> qmib.load(<span class="st">"loans"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> loans[<span class="st">"default"</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(loans[[<span class="st">"fico"</span>, <span class="st">"int_rate"</span>, <span class="st">"log_annual_inc"</span>, <span class="st">"dti"</span>]])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>lpm <span class="op">=</span> sm.OLS(y, X).fit()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> lpm.fittedvalues</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span><span class="bu">len</span>(loans)<span class="sc">:,}</span><span class="ss">   defaults = </span><span class="sc">{</span>y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,}</span><span class="ss">   base rate = </span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.2%}</span><span class="ss">"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">fitted probabilities from the linear model:"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  minimum </span><span class="sc">{</span>p_hat<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:+.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  maximum </span><span class="sc">{</span>p_hat<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:+.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>outside <span class="op">=</span> ((p_hat <span class="op">&lt;</span> <span class="dv">0</span>) <span class="op">|</span> (p_hat <span class="op">&gt;</span> <span class="dv">1</span>)).<span class="bu">sum</span>()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  outside [0, 1]: </span><span class="sc">{</span>outside<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(p_hat)<span class="sc">:,}</span><span class="ss"> (</span><span class="sc">{</span>outside<span class="op">/</span><span class="bu">len</span>(p_hat)<span class="sc">:.2%}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n = 9,578   defaults = 1,533   base rate = 16.01%

fitted probabilities from the linear model:
  minimum -0.0283
  maximum +0.3475
  outside [0, 1]: 7 of 9,578 (0.07%)</code></pre>
</div>
</div>
<p><strong>First, it can return probabilities that are not probabilities.</strong> Seven fitted values here are negative. That is a small number, and it is worth resisting the textbook temptation to treat it as devastating: at a base rate of 16% with predictors of modest strength, most fitted values land comfortably inside the interval. The failure becomes severe when the base rate is near 0 or 1, or when a predictor takes values outside the range it was fitted on — that is, exactly when you extrapolate.</p>
<p><strong>Second, the error variance cannot be constant.</strong> If <span class="math inline">\(y_i\)</span> is Bernoulli with probability <span class="math inline">\(p_i\)</span>, then <span class="math inline">\(\operatorname{Var}(y_i) = p_i(1 - p_i)\)</span> by construction. The variance is a <em>function of the mean</em>, largest at <span class="math inline">\(p = 0.5\)</span> and vanishing at either end. Heteroscedasticity is not a defect of the data here; it is a property of binary outcomes, and no amount of clean data removes it. The coefficients remain unbiased — chapter 3’s table applies — but the classical standard errors are wrong, always, and robust standard errors are mandatory rather than optional.</p>
<p><strong>Third, and most importantly, the functional form is wrong at the ends.</strong> A straight line says a fixed change in a predictor moves the probability by a fixed amount, whether you start at 0.02 or at 0.50. That is not how probabilities behave. Moving from near-certain-not to slightly-possible is a large change in the underlying propensity; moving from 0.50 to 0.55 is a small one. The line has no way to express that.</p>
</section>
<section id="the-logistic-function-and-where-it-came-from" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="the-logistic-function-and-where-it-came-from"><span class="header-section-number">4.2</span> The logistic function, and where it came from</h2>
<div class="plate">
<p><img src="images/session-04-verhulst.jpg" class="img-fluid" alt="Portrait of Pierre François Verhulst, 1804–1849."></p>
<p><strong>Pierre François Verhulst</strong> · 1804–1849</p>
<p>Named the logistic curve in 1845, modelling how populations stop growing.</p>
<p><span class="plate-credit">Flameng, Léopold, 1850. Public domain, via Wikimedia Commons.</span></p>
</div>
<div class="archive">
<p><span class="archive-label">From the archive · Verhulst, 1845</span></p>
<p>Malthus had argued that population grows geometrically while subsistence grows arithmetically, so that catastrophe is arithmetic. Pierre François Verhulst, a Belgian mathematician, thought the premise wrong: unchecked exponential growth describes no actual population, because growth slows as a population approaches what its territory can support.</p>
<p>He wrote down the correction. If growth is proportional both to the current population and to the <em>remaining room</em>, the result is a curve that rises exponentially, inflects, and flattens toward a ceiling. He named it the <em>logistic</em> curve in 1845.</p>
<p>It arrived in statistics by a different road. Berkson proposed it in the 1940s as the natural transformation for dose-response data — the <em>logit</em> — arguing against the then-dominant probit on grounds of tractability and interpretation <span class="citation" data-cites="berkson1944">(<a href="#ref-berkson1944" role="doc-biblioref">Berkson 1944</a>)</span>. Cox gave the regression treatment its modern form <span class="citation" data-cites="cox1958">(<a href="#ref-cox1958" role="doc-biblioref">Cox 1958</a>)</span>. The function Verhulst wrote to describe populations pressing against a limit is now the standard way to model any bounded probability, which is the same mathematical situation: something that cannot exceed a ceiling and slows as it approaches one.</p>
<div id="cell-fig-logistic" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">400</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>z))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">9.4</span>, <span class="fl">3.9</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ax1.plot(z, K <span class="op">*</span> sigma, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span>CL.accent)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>ax1.axhline(K, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, color<span class="op">=</span>CL.muted)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>ax1.text(<span class="op">-</span><span class="fl">5.6</span>, K <span class="op">*</span> <span class="fl">1.03</span>, <span class="st">"carrying capacity $K$"</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>CL.muted)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">"time"</span>)<span class="op">;</span> ax1.set_ylabel(<span class="st">"population"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">"Verhulst, 1845"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>ax2.plot(z, sigma, lw<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span>CL.accent)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lev <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">1</span>):</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    ax2.axhline(lev, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, color<span class="op">=</span>CL.muted)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ax2.plot([<span class="dv">0</span>], [<span class="fl">0.5</span>], marker<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">7</span>, mfc<span class="op">=</span><span class="st">"none"</span>, mec<span class="op">=</span>CL.warn, mew<span class="op">=</span><span class="fl">1.8</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>ax2.annotate(<span class="st">"steepest at $p=0.5$"</span>, (<span class="dv">0</span>, <span class="fl">0.5</span>), textcoords<span class="op">=</span><span class="st">"offset points"</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>             xytext<span class="op">=</span>(<span class="dv">12</span>, <span class="op">-</span><span class="dv">6</span>), fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>CL.warn)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="vs">r"linear index </span><span class="dv">$</span><span class="vs">x</span><span class="dv">^</span><span class="ch">\t</span><span class="vs">op</span><span class="dv">\b</span><span class="vs">eta</span><span class="dv">$</span><span class="vs">"</span>)<span class="op">;</span> ax2.set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">Pr</span><span class="kw">(</span><span class="vs">y=1</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">"the same curve, as a probability"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-logistic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="session-04_files/figure-html/fig-logistic-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: The logistic function. Left: as Verhulst wrote it, population against time approaching a carrying capacity. Right: as statistics uses it, a probability against a linear index — the same curve, relabelled.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>The model replaces the straight line with that curve. Write the linear index as <span class="math inline">\(\eta_i = x_i^\top \beta\)</span> and set</p>
<p><span class="math display">\[
\Pr(y_i = 1 \mid x_i) \;=\; \sigma(\eta_i) \;=\; \frac{1}{1 + e^{-\eta_i}}
\;=\; \frac{e^{\eta_i}}{1 + e^{\eta_i}} .
\]</span></p>
<p>The function is bounded strictly between 0 and 1, so the first failure is gone by construction. It is symmetric about <span class="math inline">\(\eta = 0\)</span>, where <span class="math inline">\(p = 0.5\)</span> and the slope is steepest, and it flattens in both tails, so the third failure is gone too: the same change in <span class="math inline">\(\eta\)</span> moves the probability a great deal in the middle and hardly at all at the extremes.</p>
<p>Inverting it gives the form that explains the model’s vocabulary:</p>
<p><span class="math display">\[
\log \underbrace{\frac{p_i}{1 - p_i}}_{\text{odds}} \;=\; x_i^\top \beta .
\]</span></p>
<p>The model is linear — in the log-odds. That is the whole trick, and it is why coefficients are not probabilities.</p>
</section>
<section id="estimation-no-formula-and-why-that-is-fine" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="estimation-no-formula-and-why-that-is-fine"><span class="header-section-number">4.3</span> Estimation: no formula, and why that is fine</h2>
<p>Least squares had a closed form. This does not. The log-likelihood is</p>
<p><span class="math display">\[
\ell(\beta) \;=\; \sum_i \Big[\, y_i \log \sigma(\eta_i) + (1 - y_i)\log\big(1 - \sigma(\eta_i)\big) \Big],
\]</span></p>
<p>and setting its derivative to zero gives <span class="math inline">\(X^\top(y - \sigma(X\beta)) = 0\)</span>, which has no algebraic solution because <span class="math inline">\(\sigma\)</span> is nonlinear in <span class="math inline">\(\beta\)</span>. The estimate is found numerically, by Newton–Raphson — equivalently, by iteratively reweighted least squares, which is the same computation dressed as a sequence of weighted regressions.</p>
<p>This is less alarming than it sounds. The log-likelihood for logistic regression is globally concave, so there is one maximum and any sensible optimiser finds it. The exception matters and is covered below.</p>
<div id="check-loglik" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Run it: the log-likelihood, and the score at the optimum</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>logit <span class="op">=</span> sm.Logit(y, X).fit(disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>eta <span class="op">=</span> X.to_numpy() <span class="op">@</span> logit.params.to_numpy()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>eta))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The likelihood, written straight from the definition.</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>ll_hand <span class="op">=</span> (y <span class="op">*</span> np.log(p) <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> y) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p)).<span class="bu">sum</span>()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"log-likelihood by hand  </span><span class="sc">{</span>ll_hand<span class="sc">:&gt;12.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"statsmodels             </span><span class="sc">{</span>logit<span class="sc">.</span>llf<span class="sc">:&gt;12.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># At the optimum the score must vanish: X'(y - p) = 0.</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>score <span class="op">=</span> X.to_numpy().T <span class="op">@</span> (y.to_numpy() <span class="op">-</span> p)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">score X'(y - p) at the optimum, largest element: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(score)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  (zero to numerical tolerance — that is what 'converged' means)"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">null log-likelihood     </span><span class="sc">{</span>logit<span class="sc">.</span>llnull<span class="sc">:&gt;12.4f}</span><span class="ss">"</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"McFadden pseudo-R²      </span><span class="sc">{</span><span class="dv">1</span> <span class="op">-</span> logit<span class="sc">.</span>llf<span class="op">/</span>logit<span class="sc">.</span>llnull<span class="sc">:&gt;12.5f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>log-likelihood by hand  -4068.055780
statsmodels             -4068.055780

score X'(y - p) at the optimum, largest element: 5.09e-11
  (zero to numerical tolerance — that is what 'converged' means)

null log-likelihood       -4212.0203
McFadden pseudo-R²           0.03418</code></pre>
</div>
</div>
<p>The pseudo-<span class="math inline">\(R^2\)</span> is 0.034, and that number deserves a warning. McFadden’s statistic is <em>not</em> a proportion of variance explained and does not behave like <span class="math inline">\(R^2\)</span>; values that would be alarming in a linear model are ordinary here. Comparing it across models fitted to different samples, or treating 0.034 as “3.4% of something”, is a misreading.</p>
</section>
<section id="reading-the-coefficients" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="reading-the-coefficients"><span class="header-section-number">4.4</span> Reading the coefficients</h2>
<p>A logistic coefficient is a change in log-odds per unit of the predictor. Nobody thinks in log-odds. There are three standard translations, in increasing order of usefulness and decreasing order of popularity.</p>
<div class="definition">
<p><span class="term"><strong>Odds ratio</strong></span> — <span class="math inline">\(e^{\beta_j}\)</span>, the multiplicative change in the odds per one-unit increase in <span class="math inline">\(x_j\)</span>, holding the rest of the index fixed. Constant across the range of <span class="math inline">\(x\)</span>, which is its convenience and its trap: constant on the odds scale means <em>not</em> constant on the probability scale.</p>
</div>
<div class="definition">
<p><span class="term"><strong>Marginal effect</strong></span> — <span class="math inline">\(\partial p / \partial x_j = \beta_j\, p(1-p)\)</span>, the change in probability per unit of <span class="math inline">\(x_j\)</span>. It depends on where you are: the same coefficient moves the probability most near <span class="math inline">\(p = 0.5\)</span> and least in the tails. The <em>average marginal effect</em> averages it over the observed sample, which is usually the number a reader wants.</p>
</div>
<div class="definition">
<p><span class="term"><strong>Predicted probability</strong></span> — <span class="math inline">\(\sigma(x^\top\hat\beta)\)</span> evaluated at specified values. The most honest presentation for a non-technical audience, because it makes the nonlinearity visible instead of hiding it in a ratio.</p>
</div>
<div id="check-effects" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Run it: the same coefficient, three ways</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>b_fico <span class="op">=</span> logit.params[<span class="st">"fico"</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"coefficient on fico         </span><span class="sc">{</span>b_fico<span class="sc">:+.6f}</span><span class="ss">  (log-odds per point)"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"odds ratio, per point       </span><span class="sc">{</span>np<span class="sc">.</span>exp(b_fico)<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"odds ratio, per 10 points   </span><span class="sc">{</span>np<span class="sc">.</span>exp(<span class="dv">10</span> <span class="op">*</span> b_fico)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>ame <span class="op">=</span> (b_fico <span class="op">*</span> p <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p)).mean()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">average marginal effect     </span><span class="sc">{</span>ame<span class="sc">:+.8f}</span><span class="ss"> per point"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  = </span><span class="sc">{</span>ame <span class="op">*</span> <span class="dv">10</span> <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.3f}</span><span class="ss"> percentage points per 10 FICO points"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  statsmodels margeff:      </span><span class="sc">{</span>logit<span class="sc">.</span>get_margeff()<span class="sc">.</span>margeff[<span class="dv">0</span>]<span class="sc">:+.8f}</span><span class="ss">"</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The same coefficient, at three different places on the curve.</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">the marginal effect is not one number:"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, pv <span class="kw">in</span> ((<span class="st">"a safe borrower  (p=0.05)"</span>, <span class="fl">0.05</span>),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                  (<span class="st">"a typical one    (p=0.16)"</span>, y.mean()),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                  (<span class="st">"a risky one      (p=0.50)"</span>, <span class="fl">0.50</span>)):</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>b_fico <span class="op">*</span> pv <span class="op">*</span> (<span class="dv">1</span><span class="op">-</span>pv) <span class="op">*</span> <span class="dv">10</span> <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.3f}</span><span class="ss"> pp per 10 points"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>coefficient on fico         -0.005655  (log-odds per point)
odds ratio, per point       0.99436
odds ratio, per 10 points   0.9450

average marginal effect     -0.00073738 per point
  = -0.737 percentage points per 10 FICO points
  statsmodels margeff:      -0.00073738

the marginal effect is not one number:
  a safe borrower  (p=0.05): -0.269 pp per 10 points
  a typical one    (p=0.16): -0.760 pp per 10 points
  a risky one      (p=0.50): -1.414 pp per 10 points</code></pre>
</div>
</div>
<p>The last block is the argument against reporting odds ratios alone. One coefficient, one odds ratio — and a change of 10 FICO points moves the probability three times as much for a borderline borrower as for a safe one. An odds ratio conceals that; a marginal effect or a plot of predicted probabilities shows it.</p>
<p>There is a subtler problem with odds ratios that is widely committed. Logistic coefficients are identified only up to the scale of the unobserved error, and that scale changes when predictors are added — so coefficients from nested logistic models are <strong>not comparable</strong> the way linear coefficients are, and an apparent change on adding a control may be pure rescaling <span class="citation" data-cites="mood2009">(<a href="#ref-mood2009" role="doc-biblioref">Mood 2009</a>)</span>. Compare average marginal effects or predicted probabilities across specifications, not raw coefficients or odds ratios.</p>
</section>
<section id="comparing-models-the-likelihood-ratio-test" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="comparing-models-the-likelihood-ratio-test"><span class="header-section-number">4.5</span> Comparing models: the likelihood-ratio test</h2>
<p>With no sums of squares there is no <span class="math inline">\(F\)</span> test, but the likelihood supplies the analogue. For nested models, twice the difference in log-likelihood is asymptotically <span class="math inline">\(\chi^2\)</span> with degrees of freedom equal to the number of restrictions:</p>
<p><span class="math display">\[
\mathrm{LR} \;=\; 2\big(\ell_{\text{full}} - \ell_{\text{restricted}}\big)
\;\overset{d}{\longrightarrow}\; \chi^2_q .
\]</span></p>
<div id="check-lr" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Run it: is dti earning its place?</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats <span class="im">as</span> st</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>full <span class="op">=</span> logit</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>small <span class="op">=</span> sm.Logit(y, sm.add_constant(loans[[<span class="st">"fico"</span>, <span class="st">"int_rate"</span>, <span class="st">"log_annual_inc"</span>]])).fit(disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (full.llf <span class="op">-</span> small.llf)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>pval <span class="op">=</span> st.chi2.sf(lr, df<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"full model      log-likelihood </span><span class="sc">{</span>full<span class="sc">.</span>llf<span class="sc">:12.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"without dti     log-likelihood </span><span class="sc">{</span>small<span class="sc">.</span>llf<span class="sc">:12.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">LR statistic </span><span class="sc">{</span>lr<span class="sc">:.4f}</span><span class="ss"> on 1 df,  p = </span><span class="sc">{</span>pval<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dti adds nothing detectable here."</span> <span class="cf">if</span> pval <span class="op">&gt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"dti matters."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>full model      log-likelihood   -4068.0558
without dti     log-likelihood   -4068.0850

LR statistic 0.0584 on 1 df,  p = 0.8090
dti adds nothing detectable here.</code></pre>
</div>
</div>
<p>Note the discipline this enforces. Both models must be fitted to <em>the same rows</em> — a predictor with extra missing values silently changes the sample and the comparison becomes meaningless — and the test only applies to nested models. For non-nested candidates, AIC from chapter 3 is the tool.</p>
</section>
<section id="does-the-model-discriminate-and-is-it-calibrated" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="does-the-model-discriminate-and-is-it-calibrated"><span class="header-section-number">4.6</span> Does the model discriminate, and is it calibrated?</h2>
<p>Two different questions, routinely conflated.</p>
<div class="definition">
<p><span class="term"><strong>Discrimination</strong></span> — can the model rank? The area under the ROC curve is exactly the probability that a randomly chosen positive case receives a higher predicted probability than a randomly chosen negative one <span class="citation" data-cites="hanley1982">(<a href="#ref-hanley1982" role="doc-biblioref">Hanley and McNeil 1982</a>)</span>. 0.5 is coin-flipping; 1.0 is perfect separation.</p>
</div>
<div class="definition">
<p><span class="term"><strong>Calibration</strong></span> — are the probabilities <em>true</em>? Among cases assigned 0.30, do about 30% turn out positive? The Brier score, the mean squared difference between predicted probability and outcome, penalises both errors at once <span class="citation" data-cites="brier1950">(<a href="#ref-brier1950" role="doc-biblioref">Brier 1950</a>)</span>.</p>
</div>
<p>A model can discriminate well and be badly calibrated, or the reverse. Which matters depends entirely on the use: a ranking for a limited budget of inspections needs discrimination; a price that must reflect risk needs calibration.</p>
<div id="check-auc" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Run it: AUC from its definition, as a rank statistic</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> rankdata</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score, brier_score_loss</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># AUC = P(score of a random positive &gt; score of a random negative). That is the</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Mann-Whitney U statistic, so it can be computed from ranks alone.</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> rankdata(p)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>n1, n0 <span class="op">=</span> <span class="bu">int</span>(y.<span class="bu">sum</span>()), <span class="bu">int</span>(<span class="bu">len</span>(y) <span class="op">-</span> y.<span class="bu">sum</span>())</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>auc_hand <span class="op">=</span> (r[y <span class="op">==</span> <span class="dv">1</span>].<span class="bu">sum</span>() <span class="op">-</span> n1 <span class="op">*</span> (n1 <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">2</span>) <span class="op">/</span> (n1 <span class="op">*</span> n0)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"AUC by hand (Mann-Whitney)  </span><span class="sc">{</span>auc_hand<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sklearn roc_auc_score       </span><span class="sc">{</span>roc_auc_score(y, p)<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>brier <span class="op">=</span> brier_score_loss(y, p)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> np.mean((y <span class="op">-</span> y.mean()) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Brier score            </span><span class="sc">{</span>brier<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"predicting the base rate </span><span class="sc">{</span>base<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"skill over base rate:  </span><span class="sc">{</span><span class="dv">1</span> <span class="op">-</span> brier<span class="op">/</span>base<span class="sc">:.2%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>AUC by hand (Mann-Whitney)  0.629502
sklearn roc_auc_score       0.629502

Brier score            0.130664
predicting the base rate 0.134437
skill over base rate:  2.81%</code></pre>
</div>
</div>
<p>Both numbers are sobering and should be reported that way. An AUC of 0.63 is weak discrimination — better than chance, far from useful for an individual decision. The Brier score improves on simply predicting the base rate for everyone by under 3%. The model is real, in the sense that its coefficients are estimated precisely and the likelihood-ratio tests are significant, and it is close to useless as a device for deciding about a particular borrower. Those two facts are compatible, and a large <span class="math inline">\(n\)</span> is what makes them compatible: with 9,578 observations, a very weak signal is statistically unmistakable.</p>
</section>
<section id="when-the-outcome-is-ordered" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="when-the-outcome-is-ordered"><span class="header-section-number">4.7</span> When the outcome is ordered</h2>
<p>Some categorical outcomes have an order — unlikely, somewhat likely, very likely. Multinomial logit would ignore the ordering; separate binary models would waste it. The ordinal model uses it, by fitting one slope and several thresholds:</p>
<p><span class="math display">\[
\Pr(y_i \le j) \;=\; \sigma(\tau_j - x_i^\top\beta),
\qquad \tau_1 &lt; \tau_2 &lt; \dots &lt; \tau_{J-1} .
\]</span></p>
<p>Each threshold <span class="math inline">\(\tau_j\)</span> marks a cut on the latent scale; the <em>same</em> <span class="math inline">\(\beta\)</span> shifts every cut together. That is the proportional-odds assumption, and it is a real restriction: the effect of a predictor on moving from “unlikely” to “somewhat likely” is assumed identical to its effect on moving from “somewhat likely” to “very likely”.</p>
<div id="check-ordinal" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Run it: an ordered outcome</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.miscmodels.ordinal_model <span class="im">import</span> OrderedModel</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>grad <span class="op">=</span> qmib.load(<span class="st">"ologit"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>grad[<span class="st">"apply_c"</span>] <span class="op">=</span> pd.Categorical(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    grad[<span class="st">"apply"</span>], categories<span class="op">=</span>[<span class="st">"unlikely"</span>, <span class="st">"somewhat likely"</span>, <span class="st">"very likely"</span>], ordered<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>om <span class="op">=</span> OrderedModel(grad[<span class="st">"apply_c"</span>], grad[[<span class="st">"pared"</span>, <span class="st">"public"</span>, <span class="st">"gpa"</span>]],</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                  distr<span class="op">=</span><span class="st">"logit"</span>).fit(method<span class="op">=</span><span class="st">"bfgs"</span>, disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span><span class="bu">len</span>(grad)<span class="sc">}</span><span class="ss">   outcome: </span><span class="sc">{</span><span class="bu">list</span>(grad[<span class="st">'apply_c'</span>].cat.categories)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'predictor'</span><span class="sc">:12}{</span><span class="st">'coef'</span><span class="sc">:&gt;10}{</span><span class="st">'odds ratio'</span><span class="sc">:&gt;13}</span><span class="ss">"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> [<span class="st">"pared"</span>, <span class="st">"public"</span>, <span class="st">"gpa"</span>]:</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> om.params[name]</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:12}{</span>b<span class="sc">:10.4f}{</span>np<span class="sc">.</span>exp(b)<span class="sc">:13.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">thresholds (latent cutpoints): "</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">', '</span><span class="sc">.</span>join(<span class="ss">f'</span><span class="sc">{</span>v<span class="sc">:.3f}</span><span class="ss">'</span> <span class="cf">for</span> v <span class="kw">in</span> om.params[<span class="op">-</span><span class="dv">2</span>:].values)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">One slope per predictor, two cutpoints — that is the proportional-odds"</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"restriction. Test it before relying on it (Brant 1990); if it fails, a"</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"multinomial model that ignores the ordering is the honest fallback."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n = 400   outcome: ['unlikely', 'somewhat likely', 'very likely']

predictor         coef   odds ratio
pared           1.0476       2.8509
public         -0.0586       0.9431
gpa             0.6158       1.8512

thresholds (latent cutpoints): 2.204, 0.740

One slope per predictor, two cutpoints — that is the proportional-odds
restriction. Test it before relying on it (Brant 1990); if it fails, a
multinomial model that ignores the ordering is the honest fallback.</code></pre>
</div>
</div>
<p>Having a parent with a graduate degree multiplies the odds of being in a higher application category by about 2.85. The assumption that this multiplier is the same at both cutpoints should be tested rather than assumed <span class="citation" data-cites="brant1990">(<a href="#ref-brant1990" role="doc-biblioref">Brant 1990</a>)</span>; when it fails, either a partial-proportional-odds model or the unordered multinomial below is preferable to a restriction the data reject.</p>
</section>
<section id="when-the-categories-have-no-order" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="when-the-categories-have-no-order"><span class="header-section-number">4.8</span> When the categories have no order</h2>
<p>With <span class="math inline">\(J\)</span> unordered categories, one is chosen as the baseline and <span class="math inline">\(J-1\)</span> binary comparisons are estimated jointly:</p>
<p><span class="math display">\[
\log \frac{\Pr(y_i = j)}{\Pr(y_i = \text{baseline})} \;=\; x_i^\top\beta_j ,
\qquad j \ne \text{baseline}.
\]</span></p>
<p>Every coefficient is therefore relative to the baseline, and changing the baseline changes all of them — without changing a single fitted probability. A multinomial result reported without naming the baseline cannot be read.</p>
<div id="check-multinomial" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Run it: three unordered categories</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>hs <span class="op">=</span> qmib.load(<span class="st">"hsbdemo"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>hs[<span class="st">"prog_c"</span>] <span class="op">=</span> pd.Categorical(hs[<span class="st">"prog"</span>], categories<span class="op">=</span>[<span class="st">"academic"</span>, <span class="st">"general"</span>, <span class="st">"vocation"</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ses_code <span class="op">=</span> pd.Categorical(hs[<span class="st">"ses"</span>], categories<span class="op">=</span>[<span class="st">"low"</span>, <span class="st">"middle"</span>, <span class="st">"high"</span>]).codes</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>mn <span class="op">=</span> sm.MNLogit(hs[<span class="st">"prog_c"</span>].cat.codes,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                sm.add_constant(hs[[<span class="st">"write"</span>]].assign(ses<span class="op">=</span>ses_code))).fit(disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span><span class="bu">len</span>(hs)<span class="sc">}</span><span class="ss">   baseline = academic"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">''</span><span class="sc">:10}{</span><span class="st">'general'</span><span class="sc">:&gt;12}{</span><span class="st">'vocation'</span><span class="sc">:&gt;12}</span><span class="ss">"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, name <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">"const"</span>, <span class="st">"write"</span>, <span class="st">"ses"</span>]):</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:10}{</span>mn<span class="sc">.</span>params<span class="sc">.</span>iloc[i,<span class="dv">0</span>]<span class="sc">:12.4f}{</span>mn<span class="sc">.</span>params<span class="sc">.</span>iloc[i,<span class="dv">1</span>]<span class="sc">:12.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">odds ratio for a 1-point writing score:"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  general  vs academic  </span><span class="sc">{</span>np<span class="sc">.</span>exp(mn.params.iloc[<span class="dv">1</span>,<span class="dv">0</span>])<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  vocation vs academic  </span><span class="sc">{</span>np<span class="sc">.</span>exp(mn.params.iloc[<span class="dv">1</span>,<span class="dv">1</span>])<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">McFadden pseudo-R² </span><span class="sc">{</span><span class="dv">1</span> <span class="op">-</span> mn<span class="sc">.</span>llf<span class="op">/</span>mn<span class="sc">.</span>llnull<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n = 200   baseline = academic

               general    vocation
const           2.9426      5.5388
write          -0.0582     -0.1122
ses            -0.6367     -0.4512

odds ratio for a 1-point writing score:
  general  vs academic  0.9435
  vocation vs academic  0.8939

McFadden pseudo-R² 0.1072</code></pre>
</div>
</div>
<p>The multinomial model carries an assumption that the ordinal one does not: <em>independence of irrelevant alternatives</em>. The ratio of probabilities for any two categories must not depend on what other categories exist. When alternatives are close substitutes the assumption fails, and the classic illustration is a transport choice between car, red bus and blue bus — introducing a bus of a different colour should not change the car’s share, and in a multinomial logit it does.</p>
</section>
<section id="the-failure-mode-worth-knowing" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="the-failure-mode-worth-knowing"><span class="header-section-number">4.9</span> The failure mode worth knowing</h2>
<p>Logistic regression has one dramatic failure, and it looks like success.</p>
<div class="definition">
<p><span class="term"><strong>Separation</strong></span> — a predictor, or a combination of them, perfectly predicts the outcome in the sample. The likelihood then has no maximum: pushing the coefficient toward infinity keeps improving the fit, so the optimiser diverges. Estimates come back enormous with enormous standard errors, or the software reports non-convergence <span class="citation" data-cites="albert1984">(<a href="#ref-albert1984" role="doc-biblioref">Albert and Anderson 1984</a>)</span>.</p>
</div>
<div id="check-separation" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Run it: build a perfect predictor and watch it break</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">60033</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">60</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> rng.normal(size<span class="op">=</span>n)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>yy <span class="op">=</span> (x <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">int</span>)          <span class="co"># perfectly separated by construction</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">;  the outcome is exactly 1 when x &gt; 0, with no exceptions."</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    sep <span class="op">=</span> sm.Logit(yy, sm.add_constant(x)).fit(disp<span class="op">=</span><span class="dv">0</span>, maxiter<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">coefficient   </span><span class="sc">{</span>np<span class="sc">.</span>asarray(sep.params)[<span class="dv">1</span>]<span class="sc">:&gt;14,.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"std. error    </span><span class="sc">{</span>np<span class="sc">.</span>asarray(sep.bse)[<span class="dv">1</span>]<span class="sc">:&gt;14,.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"converged     </span><span class="sc">{</span>sep<span class="sc">.</span>mle_retvals[<span class="st">'converged'</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> exc:</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">estimation failed: </span><span class="sc">{</span><span class="bu">type</span>(exc)<span class="sc">.</span><span class="va">__name__</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>exc<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">The fit does not merely become imprecise — it ceases to exist. Pushing"</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"the coefficient toward infinity keeps improving the likelihood, so there"</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"is no maximum to find; the curvature the optimiser needs goes to zero and"</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"the matrix it must invert becomes singular. Whether your software returns"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"an enormous coefficient, a warning, or an exception is an accident of its"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"implementation, not a difference in the underlying problem."</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="co"># The penalised estimator has a finite maximum even under separation.</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.discrete.discrete_model <span class="im">import</span> Logit</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>pen <span class="op">=</span> Logit(yy, sm.add_constant(x)).fit_regularized(alpha<span class="op">=</span><span class="fl">1.0</span>, disp<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">with an L2 penalty, the coefficient is finite: "</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>asarray(pen.params)[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n = 60;  the outcome is exactly 1 when x &gt; 0, with no exceptions.

estimation failed: LinAlgError: Singular matrix

The fit does not merely become imprecise — it ceases to exist. Pushing
the coefficient toward infinity keeps improving the likelihood, so there
is no maximum to find; the curvature the optimiser needs goes to zero and
the matrix it must invert becomes singular. Whether your software returns
an enormous coefficient, a warning, or an exception is an accident of its
implementation, not a difference in the underlying problem.

with an L2 penalty, the coefficient is finite: 5.7571</code></pre>
</div>
</div>
<p>The wrong response is to report the number. The right one is to recognise the diagnosis — check for a predictor that separates the outcome, especially a rare category or a small subgroup — and then either drop the offending variable, merge categories, or use a penalised estimator. Firth’s method adds a penalty that guarantees finite estimates and reduces small-sample bias at the same time <span class="citation" data-cites="firth1993">(<a href="#ref-firth1993" role="doc-biblioref">Firth 1993</a>)</span>.</p>
</section>
<section id="a-short-review-of-the-literature" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="a-short-review-of-the-literature"><span class="header-section-number">4.10</span> A short review of the literature</h2>
<div class="lit">
<p>The curve predates the statistics by a century: <span class="citation" data-cites="berkson1944">Berkson (<a href="#ref-berkson1944" role="doc-biblioref">1944</a>)</span> proposed the logit for bio-assay against the entrenched probit, and <span class="citation" data-cites="cox1958">Cox (<a href="#ref-cox1958" role="doc-biblioref">1958</a>)</span> gave binary regression its modern treatment. The two transformations remain nearly indistinguishable in fit and differ mainly in the interpretability of their coefficients.</p>
<p>Assessment splits along the discrimination–calibration line. <span class="citation" data-cites="hanley1982">Hanley and McNeil (<a href="#ref-hanley1982" role="doc-biblioref">1982</a>)</span> gave the AUC its standard exposition and its rank interpretation — the property that lets it be computed from a Mann-Whitney statistic, as above. <span class="citation" data-cites="brier1950">Brier (<a href="#ref-brier1950" role="doc-biblioref">1950</a>)</span>, published in meteorology and largely ignored by econometrics for decades, is the canonical proper scoring rule for probability forecasts, and remains the right answer when the probabilities themselves matter rather than their ordering.</p>
<p>The comparability problem is the most under-appreciated result in applied use. <span class="citation" data-cites="mood2009">Mood (<a href="#ref-mood2009" role="doc-biblioref">2009</a>)</span> showed that logistic coefficients are confounded with the scale of the unobserved error, so adding controls rescales them and cross-model comparison of coefficients or odds ratios is not valid — a practice that remains routine. Average marginal effects are the standard remedy.</p>
<p>For extensions, <span class="citation" data-cites="brant1990">Brant (<a href="#ref-brant1990" role="doc-biblioref">1990</a>)</span> supplies the test of the proportional-odds restriction that ordinal models assume and rarely check. On the failure of estimation, <span class="citation" data-cites="albert1984">Albert and Anderson (<a href="#ref-albert1984" role="doc-biblioref">1984</a>)</span> characterised exactly when maximum likelihood estimates fail to exist under separation, and <span class="citation" data-cites="firth1993">Firth (<a href="#ref-firth1993" role="doc-biblioref">1993</a>)</span> supplied the penalty that is now the standard fix.</p>
</div>
</section>
<section id="what-to-report" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="what-to-report"><span class="header-section-number">4.11</span> What to report</h2>
<ol type="1">
<li><strong>The base rate.</strong> Every performance number is meaningless without it; 95% accuracy on a 5% outcome is achieved by predicting “no” for everyone.</li>
<li><strong>Coefficients as odds ratios, with marginal effects beside them.</strong> The odds ratio is constant and the probability change is not, and the reader needs both to know what a coefficient means where they intend to use it.</li>
<li><strong>A nested comparison, as a likelihood-ratio test</strong>, fitted to identical rows, with the restriction stated.</li>
<li><strong>Discrimination and calibration, separately.</strong> AUC and Brier, each against its baseline, with a sentence on which one the intended decision needs.</li>
<li><strong>The assumption the extension rests on.</strong> Proportional odds for ordinal; independence of irrelevant alternatives for multinomial. Say that you tested it, or say that you did not.</li>
<li><strong>What the model does not license.</strong> These are associations in a sample of borrowers who were granted loans — a population already selected by the lender’s own approval rule, which is not a random sample of applicants and certainly not of people. Chapter 10 gives that problem its name.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-albert1984" class="csl-entry" role="listitem">
Albert, A., and J. A. Anderson. 1984. <span>“<span>On</span> the Existence of Maximum Likelihood Estimates in Logistic Regression Models.”</span> <em><span>Biometrika</span></em> 71 (1): 1–10. <a href="https://doi.org/10.1093/biomet/71.1.1">https://doi.org/10.1093/biomet/71.1.1</a>.
</div>
<div id="ref-berkson1944" class="csl-entry" role="listitem">
Berkson, Joseph. 1944. <span>“<span>Application</span> of the <span>Logistic</span> <span>Function</span> to <span>Bio</span>-<span>Assay</span>.”</span> <em><span>Journal</span> of the <span>American</span> <span>Statistical</span> <span>Association</span></em> 39 (227): 357–65. <a href="https://doi.org/10.1080/01621459.1944.10500699">https://doi.org/10.1080/01621459.1944.10500699</a>.
</div>
<div id="ref-brant1990" class="csl-entry" role="listitem">
Brant, Rollin. 1990. <span>“<span>Assessing</span> <span>Proportionality</span> in the <span>Proportional</span> <span>Odds</span> <span>Model</span> for <span>Ordinal</span> <span>Logistic</span> <span>Regression</span>.”</span> <em><span>Biometrics</span></em> 46 (4): 1171. <a href="https://doi.org/10.2307/2532457">https://doi.org/10.2307/2532457</a>.
</div>
<div id="ref-brier1950" class="csl-entry" role="listitem">
Brier, GLENN W. 1950. <span>“<span>VERIFICATION</span> <span>OF</span> <span>FORECASTS</span> <span>EXPRESSED</span> <span>IN</span> <span>TERMS</span> <span>OF</span> <span>PROBABILITY</span>.”</span> <em><span>Monthly</span> <span>Weather</span> <span>Review</span></em> 78 (1): 1–3. <a href="https://doi.org/10.1175/1520-0493(1950)078<0001:VOFEIT>2.0.CO;2">https://doi.org/10.1175/1520-0493(1950)078&lt;0001:VOFEIT&gt;2.0.CO;2</a>.
</div>
<div id="ref-cox1958" class="csl-entry" role="listitem">
Cox, D. R. 1958. <span>“<span>The</span> <span>Regression</span> <span>Analysis</span> of <span>Binary</span> <span>Sequences</span>.”</span> <em><span>Journal</span> of the <span>Royal</span> <span>Statistical</span> <span>Society</span> <span>Series</span> B: <span>Statistical</span> <span>Methodology</span></em> 20 (2): 215–32. <a href="https://doi.org/10.1111/j.2517-6161.1958.tb00292.x">https://doi.org/10.1111/j.2517-6161.1958.tb00292.x</a>.
</div>
<div id="ref-firth1993" class="csl-entry" role="listitem">
Firth, DAVID. 1993. <span>“<span>Bias</span> Reduction of Maximum Likelihood Estimates.”</span> <em><span>Biometrika</span></em> 80 (1): 27–38. <a href="https://doi.org/10.1093/biomet/80.1.27">https://doi.org/10.1093/biomet/80.1.27</a>.
</div>
<div id="ref-hanley1982" class="csl-entry" role="listitem">
Hanley, J A, and B J McNeil. 1982. <span>“<span>The</span> Meaning and Use of the Area Under a Receiver Operating Characteristic (<span>ROC</span>) Curve.”</span> <em><span>Radiology</span></em> 143 (1): 29–36. <a href="https://doi.org/10.1148/radiology.143.1.7063747">https://doi.org/10.1148/radiology.143.1.7063747</a>.
</div>
<div id="ref-mood2009" class="csl-entry" role="listitem">
Mood, C. 2009. <span>“<span>Logistic</span> <span>Regression</span>: <span>Why</span> <span>We</span> <span>Cannot</span> <span>Do</span> <span>What</span> <span>We</span> <span>Think</span> <span>We</span> <span>Can</span> <span>Do</span>, and <span>What</span> <span>We</span> <span>Can</span> <span>Do</span> <span>About</span> <span>It</span>.”</span> <em><span>European</span> <span>Sociological</span> <span>Review</span></em> 26 (1): 67–82. <a href="https://doi.org/10.1093/esr/jcp006">https://doi.org/10.1093/esr/jcp006</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./session-03.html" class="pagination-link" aria-label="Regression: Adequacy, Validity, and Robustness">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression: Adequacy, Validity, and Robustness</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./session-05.html" class="pagination-link" aria-label="Regularisation: Ridge, Lasso, and the Elastic Net">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MATH60033A · HEC Montréal</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-04.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built from the course repository</p>
</div>
  </div>
</footer>




</body></html>