<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Causal Inference II: Difference-in-Differences – Quantitative Methods in International Business with Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./session-12.html" rel="next">
<link href="./session-10.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-87cceeb0dc72897ec58809a022325911.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-654b0d63ec6aea178ec964394c84683d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./session-11.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods in International Business with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/warint/quantitative-methods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Quantitative-Methods-in-International-Business-with-Python.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foreword</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis, and the First Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regression: Adequacy, Validity, and Robustness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Logistic Regression: Binary, Ordinal, and Multinomial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regularisation: Ridge, Lasso, and the Elastic Net</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression: Advanced Considerations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Component and Factor Analyses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">K-Nearest Neighbours and the Bias–Variance Trade-off</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Structural Equation Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-11.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./session-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Setting up your tools</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-api.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The data API</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./replications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Replication packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./further-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Further reading</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-would-have-happened-otherwise" id="toc-what-would-have-happened-otherwise" class="nav-link active" data-scroll-target="#what-would-have-happened-otherwise"><span class="header-section-number">11.1</span> What would have happened otherwise</a></li>
  <li><a href="#the-two-differences" id="toc-the-two-differences" class="nav-link" data-scroll-target="#the-two-differences"><span class="header-section-number">11.2</span> The two differences</a></li>
  <li><a href="#as-a-regression" id="toc-as-a-regression" class="nav-link" data-scroll-target="#as-a-regression"><span class="header-section-number">11.3</span> As a regression</a></li>
  <li><a href="#when-treatment-arrives-at-different-times" id="toc-when-treatment-arrives-at-different-times" class="nav-link" data-scroll-target="#when-treatment-arrives-at-different-times"><span class="header-section-number">11.4</span> When treatment arrives at different times</a></li>
  <li><a href="#the-data-and-what-it-will-and-will-not-support" id="toc-the-data-and-what-it-will-and-will-not-support" class="nav-link" data-scroll-target="#the-data-and-what-it-will-and-will-not-support"><span class="header-section-number">11.5</span> The data, and what it will and will not support</a></li>
  <li><a href="#the-estimates" id="toc-the-estimates" class="nav-link" data-scroll-target="#the-estimates"><span class="header-section-number">11.6</span> The estimates</a></li>
  <li><a href="#pre-trends-what-this-data-cannot-tell-you" id="toc-pre-trends-what-this-data-cannot-tell-you" class="nav-link" data-scroll-target="#pre-trends-what-this-data-cannot-tell-you"><span class="header-section-number">11.7</span> Pre-trends: what this data cannot tell you</a></li>
  <li><a href="#what-difference-in-differences-cannot-fix" id="toc-what-difference-in-differences-cannot-fix" class="nav-link" data-scroll-target="#what-difference-in-differences-cannot-fix"><span class="header-section-number">11.8</span> What difference-in-differences cannot fix</a></li>
  <li><a href="#a-short-review-of-the-literature" id="toc-a-short-review-of-the-literature" class="nav-link" data-scroll-target="#a-short-review-of-the-literature"><span class="header-section-number">11.9</span> A short review of the literature</a></li>
  <li><a href="#what-to-report" id="toc-what-to-report" class="nav-link" data-scroll-target="#what-to-report"><span class="header-section-number">11.10</span> What to report</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-11.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Causal Inference II: Difference-in-Differences</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="what-would-have-happened-otherwise" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="what-would-have-happened-otherwise"><span class="header-section-number">11.1</span> What would have happened otherwise</h2>
<p>Chapter 10 recovered a causal effect by assuming that the variables driving treatment were all observed, and then conditioning on them. That assumption is untestable and, in most settings, false — countries do not adopt policies for reasons that are fully captured by three indicators.</p>
<p>This chapter takes the opposite route. Rather than measuring the confounders, it uses <em>timing</em> to remove them: if a country’s unobserved characteristics are stable over a short window, then comparing that country to itself before and after differences them away. The remaining problem — that things change over time for everyone — is handled by a second comparison, against units that did not adopt.</p>
<p>Two differences, hence the name.</p>
<div class="plate">
<p><img src="images/session-11-snow.jpg" class="img-fluid" alt="John Snow** · **1813–1858."></p>
<p><strong>John Snow</strong> · <strong>1813–1858</strong></p>
<p>Mapped cholera deaths in 1854 and read a natural experiment off the water supply — before the statistics existed to justify it.</p>
<p><span class="plate-credit">unknown, Autotype 1856, published in 1887. Public domain, via Wikimedia Commons.</span></p>
</div>
<div class="archive">
<p><span class="archive-label">From the archive · Snow, 1855</span></p>
<p>John Snow is remembered for the Broad Street pump, which is the wrong story. The map of cholera deaths clustered around one pump was suggestive, but a sceptic could reply that the people near the pump were poorer, more crowded, and different in a dozen ways from those further off — the selection problem of chapter 10, in 1854.</p>
<p>His second study answered that objection, and it is the one that matters here. Two companies supplied water to overlapping districts of south London, their pipes running down the same streets so that neighbouring houses drew from different sources. In 1852 one of them, Lambeth, moved its intake upstream of the sewage outflows; the other, Southwark and Vauxhall, did not. Snow could therefore compare cholera mortality in households that differed in water supply but not, in any systematic way, in anything else — and compare the change over time between the two.</p>
<p>He called it “an experiment on the grandest scale”, and was explicit that its force came from the <em>assignment</em>: no one chose their supplier, the pipes had been laid years earlier for commercial reasons unrelated to the disease. That is the argument every difference-in-differences paper is still making. Snow made it before the germ theory of disease existed — he had no mechanism, only a design.</p>
</div>
</section>
<section id="the-two-differences" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="the-two-differences"><span class="header-section-number">11.2</span> The two differences</h2>
<p>Let <span class="math inline">\(\bar Y_{g,t}\)</span> be the average outcome for group <span class="math inline">\(g\)</span> in period <span class="math inline">\(t\)</span>, with <span class="math inline">\(g \in \{\text{treated}, \text{control}\}\)</span> and <span class="math inline">\(t \in \{\text{pre}, \text{post}\}\)</span>. The estimator is</p>
<p><span class="math display">\[
\widehat{\text{DiD}}
=
\underbrace{\big(\bar Y_{\text{tr,post}} - \bar Y_{\text{tr,pre}}\big)}_{\text{change among the treated}}
-
\underbrace{\big(\bar Y_{\text{co,post}} - \bar Y_{\text{co,pre}}\big)}_{\text{change among the controls}} .
\]</span></p>
<p>The first difference removes everything time-invariant about the treated group, observed or not — its wealth, its institutions, its geography. The second estimates what would have happened anyway, and subtracting it removes any shock common to both groups.</p>
<p>What licenses the subtraction is a single assumption, and it is worth stating in its exact form because the loose version is misleading.</p>
<div class="definition">
<p><span class="term"><strong>Parallel trends</strong></span> — in the absence of treatment, the average outcome of the treated group would have followed the same <em>trajectory</em> as the control group. Formally, <span class="math display">\[
\operatorname{E}[Y_{\text{tr,post}}(0) - Y_{\text{tr,pre}}(0)]
=
\operatorname{E}[Y_{\text{co,post}}(0) - Y_{\text{co,pre}}(0)] .
\]</span> It is not an assumption that the groups are <em>similar</em> — they may differ by any amount in level — only that the gap between them would have stayed constant.</p>
</div>
<p>The assumption concerns <span class="math inline">\(Y(0)\)</span> for the treated group in the post period, which is precisely the counterfactual that does not exist. <strong>Parallel trends is therefore untestable</strong>, in the same way and for the same reason as chapter 10’s conditional independence. What can be examined is whether the trends were parallel <em>before</em> treatment, which is evidence about plausibility rather than a test of the assumption itself.</p>
<p>Note also that parallel trends is not invariant to how the outcome is measured. If two groups have parallel trends in levels they generally do not in logs, and vice versa, so the choice of scale is part of the identifying assumption rather than a presentational detail.</p>
</section>
<section id="as-a-regression" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="as-a-regression"><span class="header-section-number">11.3</span> As a regression</h2>
<p>The two-by-two table is easier to work with as a regression, and the regression form is one you have already met. With unit and period fixed effects,</p>
<p><span class="math display">\[
Y_{it} \;=\; \alpha_i + \gamma_t + \delta \, D_{it} + \varepsilon_{it},
\]</span></p>
<p>where <span class="math inline">\(D_{it}\)</span> is 1 when unit <span class="math inline">\(i\)</span> is treated in period <span class="math inline">\(t\)</span>, the coefficient <span class="math inline">\(\delta\)</span> <em>is</em> the difference-in-differences estimate. That is chapter 6’s two-way fixed effects specification with the treatment indicator in place of a continuous regressor: the unit effects absorb the first difference, the period effects the second.</p>
<p>The regression form buys three things — covariates, more than two periods and more than two groups, and standard errors. On the last, chapter 3’s finding returns with force: DiD data are panels, residuals are serially correlated within unit, and treating the country-years as independent understates the standard error badly. Clustering by unit is the minimum, and the classic demonstration of what happens otherwise is Bertrand, Duflo and Mullainathan’s, cited in chapter 3.</p>
</section>
<section id="when-treatment-arrives-at-different-times" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="when-treatment-arrives-at-different-times"><span class="header-section-number">11.4</span> When treatment arrives at different times</h2>
<p>The clean two-by-two case has one treatment date. Real policies arrive in different years for different units — which is exactly what the course fixture contains — and for two decades the profession simply put a treatment dummy into a two-way fixed effects regression and read off the coefficient.</p>
<p>That turns out to be wrong in a way nobody noticed until recently. With staggered timing, the TWFE estimate is a <em>weighted average</em> of all the two-by-two comparisons available in the data, and some of those comparisons use already-treated units as controls for later-treated ones. When effects vary over time — when the policy’s impact grows, say — those comparisons subtract a treatment effect rather than a counterfactual trend, and the implied weights can be <strong>negative</strong> <span class="citation" data-cites="dechaisemartin2020 goodmanbacon2021">(<a href="#ref-dechaisemartin2020" role="doc-biblioref">Chaisemartin and D’Haultfœuille 2020</a>; <a href="#ref-goodmanbacon2021" role="doc-biblioref">Goodman-Bacon 2021</a>)</span>. A weighted average with negative weights can lie outside the range of the things being averaged, so the estimate can have the wrong sign while every underlying effect has the right one.</p>
<p>The remedy is to build the average yourself: estimate each cohort’s effect against clean controls — units not yet treated, or never treated — and aggregate with weights you chose <span class="citation" data-cites="callaway2021 sun2021">(<a href="#ref-callaway2021" role="doc-biblioref">Callaway and Sant’Anna 2021</a>; <a href="#ref-sun2021" role="doc-biblioref">Sun and Abraham 2021</a>)</span>.</p>
</section>
<section id="the-data-and-what-it-will-and-will-not-support" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="the-data-and-what-it-will-and-will-not-support"><span class="header-section-number">11.5</span> The data, and what it will and will not support</h2>
<div id="check-timing" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Run it: the adoption structure</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys, warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>, <span class="st">"../slides"</span>)<span class="op">;</span> sys.path.insert(<span class="dv">0</span>, <span class="st">".."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotstyle <span class="im">import</span> setup, CL</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>plt <span class="op">=</span> setup()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd, statsmodels.api <span class="im">as</span> sm, qmib</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Y, D <span class="op">=</span> <span class="st">"ai_use_any"</span>, <span class="st">"has_ai_strategy"</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>TRUE_EFFECT <span class="op">=</span> <span class="fl">2.4</span>               <span class="co"># from scripts/build_spine/make_fixtures.py</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>wide <span class="op">=</span> qmib.load(<span class="st">"angle_c_country"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Adoption year must come from the FULL treatment series, not from the rows where</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># the outcome happens to be observed. Two countries adopted in 2022 and have a</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># missing 2022 outcome; taking the first year they are *seen* treated would put</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># them in the 2023 cohort and silently misdate the policy.</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>adopted <span class="op">=</span> wide[wide[D] <span class="op">==</span> <span class="dv">1</span>].groupby(<span class="st">"geo"</span>)[<span class="st">"time"</span>].<span class="bu">min</span>()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> wide[(wide[<span class="st">"time"</span>] <span class="op">&gt;=</span> <span class="dv">2021</span>) <span class="op">&amp;</span> wide[Y].notna()].copy()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>panel[<span class="st">"cohort"</span>] <span class="op">=</span> panel[<span class="st">"geo"</span>].<span class="bu">map</span>(adopted).fillna(<span class="dv">9999</span>).astype(<span class="bu">int</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"country-years with the outcome observed: </span><span class="sc">{</span><span class="bu">len</span>(panel)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"the outcome exists only from </span><span class="sc">{</span><span class="bu">int</span>(panel.time.<span class="bu">min</span>())<span class="sc">}</span><span class="ss"> — "</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"the AI module did not exist before it</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'cohort'</span><span class="sc">:&gt;10}{</span><span class="st">'countries'</span><span class="sc">:&gt;11}</span><span class="ss">   pre-periods available"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> <span class="bu">sorted</span>(panel[<span class="st">"cohort"</span>].unique()):</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> panel.loc[panel[<span class="st">"cohort"</span>] <span class="op">==</span> c, <span class="st">"geo"</span>].nunique()</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> c <span class="op">==</span> <span class="dv">9999</span>:</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'never'</span><span class="sc">:&gt;10}{</span>n<span class="sc">:&gt;11}</span><span class="ss">   —"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>        pre <span class="op">=</span> [<span class="bu">int</span>(t) <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">sorted</span>(panel.time.unique()) <span class="cf">if</span> t <span class="op">&lt;</span> c]</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>        shown <span class="op">=</span> <span class="st">", "</span>.join(<span class="bu">str</span>(t) <span class="cf">for</span> t <span class="kw">in</span> pre) <span class="cf">if</span> pre <span class="cf">else</span> <span class="st">"(none)"</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:&gt;10}{</span>n<span class="sc">:&gt;11}</span><span class="ss">   </span><span class="sc">{</span><span class="bu">len</span>(pre)<span class="sc">}</span><span class="ss">  </span><span class="sc">{</span>shown<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>country-years with the outcome observed: 112
the outcome exists only from 2021 — the AI module did not exist before it

    cohort  countries   pre-periods available
      2021          8   0  (none)
      2022          9   1  2021
      2023          1   2  2021, 2022
     never         12   —</code></pre>
</div>
</div>
<p>Three facts from that table decide what is possible, and each is a constraint a real analyst meets constantly.</p>
<p><strong>The 2021 cohort cannot be used at all.</strong> The outcome series begins in 2021 and those countries adopted in 2021, so there is no pre-treatment observation. No before, no difference, no difference-in-differences. Their data are not weak evidence — they are no evidence for this design.</p>
<p><strong>The 2023 cohort is one country.</strong> An estimate from it is a single country’s trajectory, and its standard error would be a fiction.</p>
<p>There is a trap in even getting this table right. Two countries adopted in 2022 and have no 2022 outcome recorded, so if the adoption year is taken from the rows where the outcome is observed — the obvious way to write it — they are assigned to the 2023 cohort and the policy is misdated by a year. The cohort must be read from the treatment series, which is complete, rather than from the analysis sample, which is not.</p>
<p><strong>The 2022 cohort has exactly one pre-period.</strong> That is enough to compute the estimator and <em>not</em> enough to examine pre-trends, which needs at least two pre-periods to have a trend to look at.</p>
</section>
<section id="the-estimates" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="the-estimates"><span class="header-section-number">11.6</span> The estimates</h2>
<div id="check-did" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Run it: TWFE against cohort-by-cohort DiD</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> twoby(cohort, pre, post):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Clean 2x2: one cohort against the never-treated, two periods.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns NaN when either group is unobserved in either period — a small</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">    cohort can simply be absent from a year, and that is not an estimate of zero.</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> panel[panel[<span class="st">"cohort"</span>].isin([cohort, <span class="dv">9999</span>]) <span class="op">&amp;</span> panel[<span class="st">"time"</span>].isin([pre, post])]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    tr <span class="op">=</span> sub[sub[<span class="st">"cohort"</span>] <span class="op">==</span> cohort].groupby(<span class="st">"time"</span>)[Y].mean()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    co <span class="op">=</span> sub[sub[<span class="st">"cohort"</span>] <span class="op">==</span> <span class="dv">9999</span>].groupby(<span class="st">"time"</span>)[Y].mean()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> {pre, post} <span class="op">&lt;=</span> <span class="bu">set</span>(tr.index) <span class="kw">or</span> <span class="kw">not</span> {pre, post} <span class="op">&lt;=</span> <span class="bu">set</span>(co.index):</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">float</span>(<span class="st">"nan"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (tr[post] <span class="op">-</span> tr[pre]) <span class="op">-</span> (co[post] <span class="op">-</span> co[pre])</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># The specification two decades of papers used.</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>design <span class="op">=</span> pd.concat([</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    panel[[Y, D]].reset_index(drop<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    pd.get_dummies(panel[<span class="st">"geo"</span>], drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">float</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    pd.get_dummies(panel[<span class="st">"time"</span>], prefix<span class="op">=</span><span class="st">"yr"</span>, drop_first<span class="op">=</span><span class="va">True</span>, dtype<span class="op">=</span><span class="bu">float</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>twfe <span class="op">=</span> sm.OLS(design[Y], sm.add_constant(design.drop(columns<span class="op">=</span>[Y]))).fit(</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    cov_type<span class="op">=</span><span class="st">"cluster"</span>, cov_kwds<span class="op">=</span>{<span class="st">"groups"</span>: panel[<span class="st">"geo"</span>].reset_index(drop<span class="op">=</span><span class="va">True</span>)})</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'estimator'</span><span class="sc">:44}{</span><span class="st">'estimate'</span><span class="sc">:&gt;10}{</span><span class="st">'bias'</span><span class="sc">:&gt;9}</span><span class="ss">"</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'the truth (from the generator)'</span><span class="sc">:44}{</span>TRUE_EFFECT<span class="sc">:&gt;10.3f}{</span><span class="fl">0.0</span><span class="sc">:&gt;9.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'two-way fixed effects, all cohorts'</span><span class="sc">:44}</span><span class="ss">"</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>twfe<span class="sc">.</span>params[D]<span class="sc">:&gt;10.3f}{</span>twfe<span class="sc">.</span>params[D] <span class="op">-</span> TRUE_EFFECT<span class="sc">:&gt;9.3f}</span><span class="ss">"</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   (SE </span><span class="sc">{</span>twfe<span class="sc">.</span>bse[D]<span class="sc">:.3f}</span><span class="ss">)"</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">clean 2x2 estimates, cohort against never-treated:"</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>clean <span class="op">=</span> []</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cohort, pre <span class="kw">in</span> ((<span class="dv">2022</span>, <span class="dv">2021</span>), (<span class="dv">2023</span>, <span class="dv">2022</span>)):</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> panel.loc[panel[<span class="st">"cohort"</span>] <span class="op">==</span> cohort, <span class="st">"geo"</span>].nunique()</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> post <span class="kw">in</span> <span class="bu">range</span>(cohort, <span class="dv">2025</span>):</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> twoby(cohort, pre, post)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>        label <span class="op">=</span> <span class="ss">f"   cohort </span><span class="sc">{</span>cohort<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>n<span class="sc">}</span><span class="ss"> countr</span><span class="sc">{</span><span class="st">'y'</span> <span class="cf">if</span> n <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">'ies'</span><span class="sc">}</span><span class="ss">), </span><span class="sc">{</span>pre<span class="sc">}</span><span class="ss">→</span><span class="sc">{</span>post<span class="sc">}</span><span class="ss">:"</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.isnan(v):</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> not estimable (a group is unobserved that year)"</span>)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>        clean.append((cohort, post, v, n))</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>v<span class="sc">:+7.3f}</span><span class="ss">   bias </span><span class="sc">{</span>v <span class="op">-</span> TRUE_EFFECT<span class="sc">:+7.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>usable <span class="op">=</span> [v <span class="cf">for</span> c, _, v, n <span class="kw">in</span> clean <span class="cf">if</span> n <span class="op">&gt;</span> <span class="dv">1</span>]</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">averaging only the cohort with more than one country: "</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>mean(usable)<span class="sc">:+.3f}</span><span class="ss">   bias </span><span class="sc">{</span>np<span class="sc">.</span>mean(usable) <span class="op">-</span> TRUE_EFFECT<span class="sc">:+.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>estimator                                     estimate     bias
the truth (from the generator)                   2.400    0.000
two-way fixed effects, all cohorts               2.811    0.411   (SE 0.834)

clean 2x2 estimates, cohort against never-treated:
   cohort 2022 (9 countries), 2021→2022:  +1.701   bias  -0.699
   cohort 2022 (9 countries), 2021→2023:  +2.702   bias  +0.302
   cohort 2022 (9 countries), 2021→2024:  +2.292   bias  -0.108
   cohort 2023 (1 country), 2022→2023:  +1.666   bias  -0.734
   cohort 2023 (1 country), 2022→2024: not estimable (a group is unobserved that year)

averaging only the cohort with more than one country: +2.232   bias -0.168</code></pre>
</div>
</div>
<p>The two-way fixed effects estimate is close to the truth here, and it would be dishonest to stage a dramatic failure that the data do not produce. With four periods and effects that are roughly constant once treatment begins, the negative-weighting problem is mild. The point stands anyway: <strong>the estimate is close for reasons you can only check by decomposing it</strong>, and a paper reporting the TWFE coefficient alone offers no way to know whether its weights were benign.</p>
<p>The cohort estimates show what the decomposition looks like. The 2022 cohort — nine countries with one clean pre-period — gives +1.70, +2.70 and +2.29 in successive years, averaging +2.23 against a truth of +2.40, with the sampling noise you would expect from that many units. The 2023 cohort is a single country; its one estimable comparison happens to land at +1.67, and the second is not estimable at all because that country is absent from the final year. Both are reported rather than quietly dropped, because a cohort of one is a fact about the design and hiding it would make the evidence look stronger than it is.</p>
</section>
<section id="pre-trends-what-this-data-cannot-tell-you" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="pre-trends-what-this-data-cannot-tell-you"><span class="header-section-number">11.7</span> Pre-trends: what this data cannot tell you</h2>
<div id="cell-fig-event-study" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cohort <span class="op">=</span> <span class="dv">2022</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> panel[panel[<span class="st">"cohort"</span>].isin([cohort, <span class="dv">9999</span>])].copy()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sub[<span class="st">"treated"</span>] <span class="op">=</span> (sub[<span class="st">"cohort"</span>] <span class="op">==</span> cohort).astype(<span class="bu">int</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>tr <span class="op">=</span> sub[sub[<span class="st">"treated"</span>] <span class="op">==</span> <span class="dv">1</span>].groupby(<span class="st">"time"</span>)[Y].mean()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>co <span class="op">=</span> sub[sub[<span class="st">"treated"</span>] <span class="op">==</span> <span class="dv">0</span>].groupby(<span class="st">"time"</span>)[Y].mean()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>years <span class="op">=</span> <span class="bu">sorted</span>(sub[<span class="st">"time"</span>].unique())</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>eff <span class="op">=</span> [(t <span class="op">-</span> cohort, (tr[t] <span class="op">-</span> tr[<span class="dv">2021</span>]) <span class="op">-</span> (co[t] <span class="op">-</span> co[<span class="dv">2021</span>])) <span class="cf">for</span> t <span class="kw">in</span> years]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.8</span>, <span class="fl">4.0</span>))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>xs <span class="op">=</span> [e <span class="cf">for</span> e, _ <span class="kw">in</span> eff]<span class="op">;</span> ys <span class="op">=</span> [v <span class="cf">for</span> _, v <span class="kw">in</span> eff]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="dv">0</span>, color<span class="op">=</span>CL.line, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>ax.axhline(TRUE_EFFECT, color<span class="op">=</span>CL.good, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">":"</span>, label<span class="op">=</span><span class="st">"true effect"</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="op">-</span><span class="fl">0.5</span>, color<span class="op">=</span>CL.muted, lw<span class="op">=</span><span class="fl">1.2</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>ax.plot(xs, ys, marker<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">7</span>, lw<span class="op">=</span><span class="fl">1.8</span>, color<span class="op">=</span>CL.accent, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">"reference period</span><span class="ch">\n</span><span class="st">(zero by construction)"</span>, (<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>            textcoords<span class="op">=</span><span class="st">"offset points"</span>, xytext<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">26</span>), fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>CL.muted)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"years since adoption"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"estimated effect (pp)"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(xs)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"lower right"</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'event time'</span><span class="sc">:&gt;12}{</span><span class="st">'estimate'</span><span class="sc">:&gt;11}</span><span class="ss">"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> e, v <span class="kw">in</span> eff:</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    note <span class="op">=</span> <span class="st">"  reference — not evidence"</span> <span class="cf">if</span> e <span class="op">==</span> <span class="op">-</span><span class="dv">1</span> <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>e<span class="sc">:&gt;12}{</span>v<span class="sc">:&gt;11.3f}{</span>note<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">pre-periods available for this cohort: "</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> e, _ <span class="kw">in</span> eff <span class="cf">if</span> e <span class="op">&lt;</span> <span class="dv">0</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  event time   estimate
          -1      0.000  reference — not evidence
           0      1.701
           1      2.702
           2      2.292

pre-periods available for this cohort: 1</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-event-study" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-event-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="session-11_files/figure-html/fig-event-study-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-event-study-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: Event study for the 2022 cohort against the never-treated. Event time 0 is the year of adoption. The point at <span class="math inline">\(-1\)</span> is the reference period and is zero by construction, not by evidence — with a single pre-period there is no pre-trend to examine.
</figcaption>
</figure>
</div>
</div>
</div>
<p>An event study is the standard way to make parallel trends look plausible: plot the estimated effect at each period relative to adoption, and look for a flat line before treatment. Here the pre-treatment portion consists of a single point, which is the reference period and therefore exactly zero by arithmetic.</p>
<p><strong>A flat pre-trend that contains one mechanically-zero point is not evidence of anything.</strong> This is not a defect of the analysis; it is a property of the data, and it means the identifying assumption of this chapter cannot be examined at all in this dataset. The honest report says so, states the estimate as conditional on an assumption that could not be checked, and treats the finding accordingly.</p>
<p>It is worth noticing how much weaker that is than what chapter 10 could do. There the assumption was also untestable, but the covariates could at least be shown to be balanced. Here, there is nothing to show.</p>
</section>
<section id="what-difference-in-differences-cannot-fix" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="what-difference-in-differences-cannot-fix"><span class="header-section-number">11.8</span> What difference-in-differences cannot fix</h2>
<p><strong>Anything that changes at the same time as treatment.</strong> Fixed effects remove what is constant; the second difference removes what is common. A shock hitting only the treated group in the treatment year is indistinguishable from the treatment, and no amount of data separates them. Countries that adopt an AI strategy in a given year may be doing several other things that year.</p>
<p><strong>Anticipation.</strong> If units change behaviour before adoption because they know it is coming, the pre-period is already contaminated and the “before” is not a clean baseline. This shows as a non-zero pre-trend, when there are enough pre-periods to see one.</p>
<p><strong>Composition change.</strong> If the units in the panel change — countries entering or leaving the sample, or a survey changing who it asks — the first difference is comparing different populations rather than the same one over time.</p>
<p><strong>Spillovers.</strong> The control group must be unaffected. If a national strategy in one country shifts behaviour in its neighbours, the controls are partially treated and the estimate is attenuated toward zero.</p>
</section>
<section id="a-short-review-of-the-literature" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="a-short-review-of-the-literature"><span class="header-section-number">11.9</span> A short review of the literature</h2>
<div class="lit">
<p>The design is older than its name: <span class="citation" data-cites="wing2018">Wing, Simon, and Bello-Gomez (<a href="#ref-wing2018" role="doc-biblioref">2018</a>)</span> traces it to Snow’s 1855 water study and sets out the modern practice, including the pre-trend examination and the sensitivity checks a credible paper is expected to show.</p>
<p>The last decade has been dominated by a single discovery about staggered adoption. <span class="citation" data-cites="goodmanbacon2021">Goodman-Bacon (<a href="#ref-goodmanbacon2021" role="doc-biblioref">2021</a>)</span> decomposed the two-way fixed effects estimator into the underlying two-by-two comparisons and showed that some of them use already-treated units as controls; <span class="citation" data-cites="dechaisemartin2020">Chaisemartin and D’Haultfœuille (<a href="#ref-dechaisemartin2020" role="doc-biblioref">2020</a>)</span> showed that the implied weights can be negative, so the estimand may lie outside the range of every underlying effect. Neither paper is a curiosity — between them they called into question a large body of published work.</p>
<p>The constructive replacements estimate cohort-specific effects against clean comparison groups and aggregate them explicitly. <span class="citation" data-cites="callaway2021">Callaway and Sant’Anna (<a href="#ref-callaway2021" role="doc-biblioref">2021</a>)</span> gives the group-time average treatment effects and the aggregation schemes; <span class="citation" data-cites="sun2021">Sun and Abraham (<a href="#ref-sun2021" role="doc-biblioref">2021</a>)</span> does the equivalent for event-study specifications, where the same negative weighting contaminates the coefficients on individual leads and lags.</p>
<p>On inference, the reference remains Bertrand, Duflo and Mullainathan, discussed in chapter 3: DiD data are serially correlated panels, and standard errors that ignore it reject true nulls at many times the nominal rate.</p>
</div>
</section>
<section id="what-to-report" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="what-to-report"><span class="header-section-number">11.10</span> What to report</h2>
<ol type="1">
<li><strong>The adoption structure.</strong> How many units in each cohort, how many periods before and after, and which cohorts are unusable. A table of this is worth more than a paragraph asserting the design is sound.</li>
<li><strong>The parallel-trends argument</strong>, as an argument. Why should the gap have stayed constant? Institutional reasoning, not a citation to the assumption.</li>
<li><strong>An event study</strong>, with the reference period marked as such — and if there are too few pre-periods to see a trend, say that instead of implying the flat line is evidence.</li>
<li><strong>A staggered-robust estimator alongside TWFE.</strong> If they agree, the weights were benign and you have shown it. If they disagree, the decomposition is the finding.</li>
<li><strong>Standard errors clustered by unit</strong>, with the number of clusters. Below about forty, say what you did about it.</li>
<li><strong>The scale.</strong> Levels or logs is part of the assumption, because parallel trends in one is not parallel trends in the other.</li>
<li><strong>What could have moved at the same time.</strong> The most credible DiD papers name the confounding events they considered and explain why each is implausible — which is the modern version of Snow pointing out that nobody chose their water company.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-callaway2021" class="csl-entry" role="listitem">
Callaway, Brantly, and Pedro H. C. Sant’Anna. 2021. <span>“<span>Difference</span>-in-<span>Differences</span> with Multiple Time Periods.”</span> <em><span>Journal</span> of <span>Econometrics</span></em> 225 (2): 200–230. <a href="https://doi.org/10.1016/j.jeconom.2020.12.001">https://doi.org/10.1016/j.jeconom.2020.12.001</a>.
</div>
<div id="ref-dechaisemartin2020" class="csl-entry" role="listitem">
Chaisemartin, Clément de, and Xavier D’Haultfœuille. 2020. <span>“<span>Two</span>-<span>Way</span> <span>Fixed</span> <span>Effects</span> <span>Estimators</span> with <span>Heterogeneous</span> <span>Treatment</span> <span>Effects</span>.”</span> <em><span>American</span> <span>Economic</span> <span>Review</span></em> 110 (9): 2964–96. <a href="https://doi.org/10.1257/aer.20181169">https://doi.org/10.1257/aer.20181169</a>.
</div>
<div id="ref-goodmanbacon2021" class="csl-entry" role="listitem">
Goodman-Bacon, Andrew. 2021. <span>“<span>Difference</span>-in-Differences with Variation in Treatment Timing.”</span> <em><span>Journal</span> of <span>Econometrics</span></em> 225 (2): 254–77. <a href="https://doi.org/10.1016/j.jeconom.2021.03.014">https://doi.org/10.1016/j.jeconom.2021.03.014</a>.
</div>
<div id="ref-sun2021" class="csl-entry" role="listitem">
Sun, Liyang, and Sarah Abraham. 2021. <span>“<span>Estimating</span> Dynamic Treatment Effects in Event Studies with Heterogeneous Treatment Effects.”</span> <em><span>Journal</span> of <span>Econometrics</span></em> 225 (2): 175–99. <a href="https://doi.org/10.1016/j.jeconom.2020.09.006">https://doi.org/10.1016/j.jeconom.2020.09.006</a>.
</div>
<div id="ref-wing2018" class="csl-entry" role="listitem">
Wing, Coady, Kosali Simon, and Ricardo A. Bello-Gomez. 2018. <span>“<span>Designing</span> <span>Difference</span> in <span>Difference</span> <span>Studies</span>: <span>Best</span> <span>Practices</span> for <span>Public</span> <span>Health</span> <span>Policy</span> <span>Research</span>.”</span> <em><span>Annual</span> <span>Review</span> of <span>Public</span> <span>Health</span></em> 39 (1): 453–69. <a href="https://doi.org/10.1146/annurev-publhealth-040617-013507">https://doi.org/10.1146/annurev-publhealth-040617-013507</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./session-10.html" class="pagination-link" aria-label="Causal Inference I: Counterfactuals, Randomisation, Matching">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Causal Inference I: Counterfactuals, Randomisation, Matching</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./session-12.html" class="pagination-link" aria-label="Conclusion">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MATH60033A · HEC Montréal</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/warint/quantitative-methods/blob/main/session-11.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/warint/quantitative-methods/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built from the course repository</p>
</div>
  </div>
</footer>




</body></html>