"""Write the two solution slides for each paper of the session 07 deck.

    python 07-replication-workshop/01-lecture/build_solution_slides.py

For every starter script in ../02-practice/starter/ this writes an include file,
_solutions-rN.qmd, holding two slides:

  * "The script, to copy" — the whole file in one block, so a student can paste
    it into a new file in VS Codium and run it;
  * "The solutions, step by step" — one tab per `# Step N ·` block of the script,
    executed when the deck renders, so the code and the results on the slides
    are the script's own.

The deck pulls them in with {{< include _solutions-rN.qmd >}}. Re-run this after
editing a starter script, then re-render the deck. Never edit the include files
by hand: they are regenerated from the scripts.
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
STARTER = HERE.parent / "02-practice" / "starter"

PAPERS = [
    ("r1", "r1_fraiberger_2021.py"),
    ("r2", "r2_amsili_2024.py"),
    ("r3", "r3_saganowski_2019.py"),
    ("r4", "r4_blonigen_piger_2014.py"),
    ("r5", "r5_topalova_khandelwal_2011.py"),
]

STEP = re.compile(r"^# Step (\d+) · (.*)$", re.M)


def split(script):
    """The set-up (docstring dropped) and the numbered steps of one script."""
    body = re.sub(r'\A""".*?"""\n+', "", script, flags=re.S)
    marks = list(STEP.finditer(body))
    setup = body[:marks[0].start()].strip()
    steps = []
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
        steps.append((m.group(1), m.group(2).strip(), body[m.start():end].strip()))
    return setup, steps


def cell(code):
    return f"```{{python}}\n#| echo: true\n{code}\n```"


def slides(key, fn):
    script = (STARTER / fn).read_text(encoding="utf-8")
    setup, steps = split(script)
    tabs = [f"### Set-up\n\nThe lines that open every script: find the repository, import what the "
            f"steps use.\n\n{cell(setup)}"]
    for n, title, code in steps:
        tabs.append(f"### {n}\n\n**Step {n} · {title}**\n\n{cell(code)}")
    tabset = "\n\n".join(tabs)
    return f"""<!-- Generated by build_solution_slides.py from ../02-practice/starter/{fn}.
     Do not edit: change the script, then re-run the builder. -->

## The script, to copy {{.scrollable}}

In VS Codium: **File → New File…** → *Python File*, paste, **save it inside the
`quantitative-methods` folder** (for example as `{key}.py`), and press **Run** ▷. It is the same
file as `02-practice/starter/{fn}`.

```python
{script.strip()}
```

## The solutions, step by step {{.scrollable}}

Each tab is one step, run when these slides were built: the code, then what it prints. Compare
your own output with it line by line.

:::::::: panel-tabset
{tabset}
::::::::
"""


def main():
    for key, fn in PAPERS:
        out = HERE / f"_solutions-{key}.qmd"
        out.write_text(slides(key, fn), encoding="utf-8")
        print(f"  {out.name}  <- {fn}")


if __name__ == "__main__":
    main()
