{
  "hash": "506c098a420f9f5b3fc1a4fecb57406c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Causal Inference II: Difference-in-Differences\"\n---\n\n## What would have happened otherwise\n\nChapter 10 recovered a causal effect by assuming that the variables driving\ntreatment were all observed, and then conditioning on them. That assumption is\nuntestable and, in most settings, false — countries do not adopt policies for\nreasons that are fully captured by three indicators.\n\nThis chapter takes the opposite route. Rather than measuring the confounders, it\nuses *timing* to remove them: if a country's unobserved characteristics are\nstable over a short window, then comparing that country to itself before and\nafter differences them away. The remaining problem — that things change over\ntime for everyone — is handled by a second comparison, against units that did\nnot adopt.\n\nTwo differences, hence the name.\n\n::: {.plate}\n![](images/session-11-snow.jpg){fig-alt=\"John Snow** · **1813–1858.\"}\n\n**John Snow** · **1813–1858**\n\nMapped cholera deaths in 1854 and read a natural experiment off the water supply — before the statistics existed to justify it.\n\n[unknown, Autotype 1856, published in 1887. Public domain, via Wikimedia Commons.]{.plate-credit}\n:::\n\n\n::: {.archive}\n[From the archive · Snow, 1855]{.archive-label}\n\nJohn Snow is remembered for the Broad Street pump, which is the wrong story. The\nmap of cholera deaths clustered around one pump was suggestive, but a sceptic\ncould reply that the people near the pump were poorer, more crowded, and\ndifferent in a dozen ways from those further off — the selection problem of\nchapter 10, in 1854.\n\nHis second study answered that objection, and it is the one that matters here.\nTwo companies supplied water to overlapping districts of south London, their\npipes running down the same streets so that neighbouring houses drew from\ndifferent sources. In 1852 one of them, Lambeth, moved its intake upstream of\nthe sewage outflows; the other, Southwark and Vauxhall, did not. Snow could\ntherefore compare cholera mortality in households that differed in water supply\nbut not, in any systematic way, in anything else — and compare the change over\ntime between the two.\n\nHe called it \"an experiment on the grandest scale\", and was explicit that its\nforce came from the *assignment*: no one chose their supplier, the pipes had been\nlaid years earlier for commercial reasons unrelated to the disease. That is the\nargument every difference-in-differences paper is still making. Snow made it\nbefore the germ theory of disease existed — he had no mechanism, only a design.\n:::\n\n## The two differences\n\nLet $\\bar Y_{g,t}$ be the average outcome for group $g$ in period $t$, with\n$g \\in \\{\\text{treated}, \\text{control}\\}$ and $t \\in \\{\\text{pre}, \\text{post}\\}$.\nThe estimator is\n\n$$\n\\widehat{\\text{DiD}}\n=\n\\underbrace{\\big(\\bar Y_{\\text{tr,post}} - \\bar Y_{\\text{tr,pre}}\\big)}_{\\text{change among the treated}}\n-\n\\underbrace{\\big(\\bar Y_{\\text{co,post}} - \\bar Y_{\\text{co,pre}}\\big)}_{\\text{change among the controls}} .\n$$\n\nThe first difference removes everything time-invariant about the treated group,\nobserved or not — its wealth, its institutions, its geography. The second\nestimates what would have happened anyway, and subtracting it removes any shock\ncommon to both groups.\n\nWhat licenses the subtraction is a single assumption, and it is worth stating in\nits exact form because the loose version is misleading.\n\n::: {.definition}\n[**Parallel trends**]{.term} — in the absence of treatment, the average outcome\nof the treated group would have followed the same *trajectory* as the control\ngroup. Formally,\n$$\n\\operatorname{E}[Y_{\\text{tr,post}}(0) - Y_{\\text{tr,pre}}(0)]\n=\n\\operatorname{E}[Y_{\\text{co,post}}(0) - Y_{\\text{co,pre}}(0)] .\n$$\nIt is not an assumption that the groups are *similar* — they may differ by any\namount in level — only that the gap between them would have stayed constant.\n:::\n\nThe assumption concerns $Y(0)$ for the treated group in the post period, which\nis precisely the counterfactual that does not exist. **Parallel trends is\ntherefore untestable**, in the same way and for the same reason as chapter 10's\nconditional independence. What can be examined is whether the trends were\nparallel *before* treatment, which is evidence about plausibility rather than a\ntest of the assumption itself.\n\nNote also that parallel trends is not invariant to how the outcome is measured.\nIf two groups have parallel trends in levels they generally do not in logs, and\nvice versa, so the choice of scale is part of the identifying assumption rather\nthan a presentational detail.\n\n## As a regression\n\nThe two-by-two table is easier to work with as a regression, and the regression\nform is one you have already met. With unit and period fixed effects,\n\n$$\nY_{it} \\;=\\; \\alpha_i + \\gamma_t + \\delta \\, D_{it} + \\varepsilon_{it},\n$$\n\nwhere $D_{it}$ is 1 when unit $i$ is treated in period $t$, the coefficient\n$\\delta$ *is* the difference-in-differences estimate. That is chapter 6's two-way\nfixed effects specification with the treatment indicator in place of a continuous\nregressor: the unit effects absorb the first difference, the period effects the\nsecond.\n\nThe regression form buys three things — covariates, more than two periods and\nmore than two groups, and standard errors. On the last, chapter 3's finding\nreturns with force: DiD data are panels, residuals are serially correlated within\nunit, and treating the country-years as independent understates the standard\nerror badly. Clustering by unit is the minimum, and the classic demonstration of\nwhat happens otherwise is Bertrand, Duflo and Mullainathan's, cited in chapter 3.\n\n## When treatment arrives at different times\n\nThe clean two-by-two case has one treatment date. Real policies arrive in\ndifferent years for different units — which is exactly what the course fixture\ncontains — and for two decades the profession simply put a treatment dummy into\na two-way fixed effects regression and read off the coefficient.\n\nThat turns out to be wrong in a way nobody noticed until recently. With staggered\ntiming, the TWFE estimate is a *weighted average* of all the two-by-two\ncomparisons available in the data, and some of those comparisons use\nalready-treated units as controls for later-treated ones. When effects vary over\ntime — when the policy's impact grows, say — those comparisons subtract a\ntreatment effect rather than a counterfactual trend, and the implied weights can\nbe **negative** [@dechaisemartin2020; @goodmanbacon2021]. A weighted average with\nnegative weights can lie outside the range of the things being averaged, so the\nestimate can have the wrong sign while every underlying effect has the right one.\n\nThe remedy is to build the average yourself: estimate each cohort's effect\nagainst clean controls — units not yet treated, or never treated — and aggregate\nwith weights you chose [@callaway2021; @sun2021].\n\n## The data, and what it will and will not support\n\n::: {#check-timing .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Run it: the adoption structure\"}\nimport sys, warnings\nsys.path.insert(0, \"../slides\"); sys.path.insert(0, \"..\")\nwarnings.filterwarnings(\"ignore\")\nfrom plotstyle import setup, CL\nplt = setup()\n\nimport numpy as np, pandas as pd, statsmodels.api as sm, qmib\n\nY, D = \"ai_use_any\", \"has_ai_strategy\"\nTRUE_EFFECT = 2.4               # from scripts/build_spine/make_fixtures.py\n\nwide = qmib.load(\"angle_c_country\")\n\n# Adoption year must come from the FULL treatment series, not from the rows where\n# the outcome happens to be observed. Two countries adopted in 2022 and have a\n# missing 2022 outcome; taking the first year they are *seen* treated would put\n# them in the 2023 cohort and silently misdate the policy.\nadopted = wide[wide[D] == 1].groupby(\"geo\")[\"time\"].min()\n\npanel = wide[(wide[\"time\"] >= 2021) & wide[Y].notna()].copy()\npanel[\"cohort\"] = panel[\"geo\"].map(adopted).fillna(9999).astype(int)\n\nprint(f\"country-years with the outcome observed: {len(panel)}\")\nprint(f\"the outcome exists only from {int(panel.time.min())} — \"\n      f\"the AI module did not exist before it\\n\")\nprint(f\"{'cohort':>10}{'countries':>11}   pre-periods available\")\nfor c in sorted(panel[\"cohort\"].unique()):\n    n = panel.loc[panel[\"cohort\"] == c, \"geo\"].nunique()\n    if c == 9999:\n        print(f\"{'never':>10}{n:>11}   —\")\n    else:\n        pre = [int(t) for t in sorted(panel.time.unique()) if t < c]\n        shown = \", \".join(str(t) for t in pre) if pre else \"(none)\"\n        print(f\"{c:>10}{n:>11}   {len(pre)}  {shown}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncountry-years with the outcome observed: 112\nthe outcome exists only from 2021 — the AI module did not exist before it\n\n    cohort  countries   pre-periods available\n      2021          8   0  (none)\n      2022          9   1  2021\n      2023          1   2  2021, 2022\n     never         12   —\n```\n:::\n:::\n\n\nThree facts from that table decide what is possible, and each is a constraint a\nreal analyst meets constantly.\n\n**The 2021 cohort cannot be used at all.** The outcome series begins in 2021 and\nthose countries adopted in 2021, so there is no pre-treatment observation. No\nbefore, no difference, no difference-in-differences. Their data are not weak\nevidence — they are no evidence for this design.\n\n**The 2023 cohort is one country.** An estimate from it is a single country's\ntrajectory, and its standard error would be a fiction.\n\nThere is a trap in even getting this table right. Two countries adopted in 2022\nand have no 2022 outcome recorded, so if the adoption year is taken from the rows\nwhere the outcome is observed — the obvious way to write it — they are assigned to\nthe 2023 cohort and the policy is misdated by a year. The cohort must be read from\nthe treatment series, which is complete, rather than from the analysis sample,\nwhich is not.\n\n**The 2022 cohort has exactly one pre-period.** That is enough to compute the\nestimator and *not* enough to examine pre-trends, which needs at least two\npre-periods to have a trend to look at.\n\n## The estimates\n\n::: {#check-did .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Run it: TWFE against cohort-by-cohort DiD\"}\ndef twoby(cohort, pre, post):\n    \"\"\"Clean 2x2: one cohort against the never-treated, two periods.\n\n    Returns NaN when either group is unobserved in either period — a small\n    cohort can simply be absent from a year, and that is not an estimate of zero.\n    \"\"\"\n    sub = panel[panel[\"cohort\"].isin([cohort, 9999]) & panel[\"time\"].isin([pre, post])]\n    tr = sub[sub[\"cohort\"] == cohort].groupby(\"time\")[Y].mean()\n    co = sub[sub[\"cohort\"] == 9999].groupby(\"time\")[Y].mean()\n    if not {pre, post} <= set(tr.index) or not {pre, post} <= set(co.index):\n        return float(\"nan\")\n    return (tr[post] - tr[pre]) - (co[post] - co[pre])\n\n# The specification two decades of papers used.\ndesign = pd.concat([\n    panel[[Y, D]].reset_index(drop=True),\n    pd.get_dummies(panel[\"geo\"], drop_first=True, dtype=float).reset_index(drop=True),\n    pd.get_dummies(panel[\"time\"], prefix=\"yr\", drop_first=True, dtype=float).reset_index(drop=True),\n], axis=1)\ntwfe = sm.OLS(design[Y], sm.add_constant(design.drop(columns=[Y]))).fit(\n    cov_type=\"cluster\", cov_kwds={\"groups\": panel[\"geo\"].reset_index(drop=True)})\n\nprint(f\"{'estimator':44}{'estimate':>10}{'bias':>9}\")\nprint(f\"{'the truth (from the generator)':44}{TRUE_EFFECT:>10.3f}{0.0:>9.3f}\")\nprint(f\"{'two-way fixed effects, all cohorts':44}\"\n      f\"{twfe.params[D]:>10.3f}{twfe.params[D] - TRUE_EFFECT:>9.3f}\"\n      f\"   (SE {twfe.bse[D]:.3f})\")\n\nprint(f\"\\nclean 2x2 estimates, cohort against never-treated:\")\nclean = []\nfor cohort, pre in ((2022, 2021), (2023, 2022)):\n    n = panel.loc[panel[\"cohort\"] == cohort, \"geo\"].nunique()\n    for post in range(cohort, 2025):\n        v = twoby(cohort, pre, post)\n        label = f\"   cohort {cohort} ({n} countr{'y' if n == 1 else 'ies'}), {pre}→{post}:\"\n        if np.isnan(v):\n            print(f\"{label} not estimable (a group is unobserved that year)\")\n            continue\n        clean.append((cohort, post, v, n))\n        print(f\"{label} {v:+7.3f}   bias {v - TRUE_EFFECT:+7.3f}\")\n\nusable = [v for c, _, v, n in clean if n > 1]\nprint(f\"\\naveraging only the cohort with more than one country: \"\n      f\"{np.mean(usable):+.3f}   bias {np.mean(usable) - TRUE_EFFECT:+.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nestimator                                     estimate     bias\nthe truth (from the generator)                   2.400    0.000\ntwo-way fixed effects, all cohorts               2.811    0.411   (SE 0.834)\n\nclean 2x2 estimates, cohort against never-treated:\n   cohort 2022 (9 countries), 2021→2022:  +1.701   bias  -0.699\n   cohort 2022 (9 countries), 2021→2023:  +2.702   bias  +0.302\n   cohort 2022 (9 countries), 2021→2024:  +2.292   bias  -0.108\n   cohort 2023 (1 country), 2022→2023:  +1.666   bias  -0.734\n   cohort 2023 (1 country), 2022→2024: not estimable (a group is unobserved that year)\n\naveraging only the cohort with more than one country: +2.232   bias -0.168\n```\n:::\n:::\n\n\nThe two-way fixed effects estimate is close to the truth here, and it would be\ndishonest to stage a dramatic failure that the data do not produce. With four\nperiods and effects that are roughly constant once treatment begins, the\nnegative-weighting problem is mild. The point stands anyway: **the estimate is\nclose for reasons you can only check by decomposing it**, and a paper reporting\nthe TWFE coefficient alone offers no way to know whether its weights were benign.\n\nThe cohort estimates show what the decomposition looks like. The 2022 cohort —\nnine countries with one clean pre-period — gives +1.70, +2.70 and +2.29 in\nsuccessive years, averaging +2.23 against a truth of +2.40, with the sampling\nnoise you would expect from that many units. The 2023 cohort is a single country;\nits one estimable comparison happens to land at +1.67, and the second is not\nestimable at all because that country is absent from the final year. Both are\nreported rather than quietly dropped, because a cohort of one is a fact about the\ndesign and hiding it would make the evidence look stronger than it is.\n\n## The estimator has a name\n\nThe loop in that cell is not an improvisation. Estimating each cohort against a\nclean comparison group and aggregating with weights you chose is precisely the\nprocedure of @callaway2021, and there is a Python implementation of it,\n`diff-diff`. It is a young package and the reference implementation is still\nR's `did`, so the first thing to do with it is what this section does: run it\nbeside a calculation you already understand, and find out where the two\ndisagree.\n\nThat is worth doing here for three reasons. It states out loud which cells it\nrefuses to estimate. It attaches standard errors to the cohort estimates, which\nthe hand-rolled loop had no way to produce. And it does disagree — in a way that\nturns out to be the hand-rolled version's fault.\n\n::: {#check-cs .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Run it: Callaway–Sant'Anna on the same panel\"}\nimport diff_diff as dd\n\n# The estimator wants one column holding the adoption year, and 0 — not a\n# sentinel it would read as a year — for the never-treated.\npanel[\"g\"] = panel[\"cohort\"].replace(9999, 0)\n\ncs = dd.CallawaySantAnna(cluster=\"geo\").fit(\n    panel, outcome=Y, unit=\"geo\", time=\"time\", first_treat=\"g\")\ngt = cs.to_dataframe()\n\nprint(f\"{'cohort':>7}{'year':>6}{'ATT(g,t)':>10}{'SE':>7}\")\nfor _, r in gt.iterrows():\n    g, t = int(r.group), int(r.time)\n    if pd.isna(r.effect):\n        print(f\"{g:>7}{t:>6}{'—':>10}{'—':>7}   dropped: {r.skip_reason}\")\n    else:\n        tag = \"  ← pre-treatment, not an effect\" if t < g else \"\"\n        print(f\"{g:>7}{t:>6}{r.effect:>10.3f}{r.se:>7.3f}{tag}\")\n\nprint(f\"\\n{'overall ATT':>18}{cs.overall_att:>10.3f}{cs.overall_se:>7.3f}\"\n      f\"   bias {cs.overall_att - TRUE_EFFECT:+.3f}, {cs.n_clusters} clusters\")\nfor _, r in cs.aggregate(\"group\").to_dataframe().iterrows():\n    n = panel.loc[panel[\"cohort\"] == int(r.label), \"geo\"].nunique()\n    print(f\"{'cohort ' + str(r.label):>18}{r.att:>10.3f}{r.se:>7.3f}\"\n          f\"   {n} countr{'y' if n == 1 else 'ies'}\")\n\n# The hand-rolled estimates and these ones differ. Recomputing each 2x2 over\n# only the countries observed in *both* of its two years isolates why.\nprint(\"\\nthe hand-rolled numbers, and what was wrong with them:\")\nprint(f\"{'g,t':>9}{'as written':>12}{'same units':>12}{'ATT(g,t)':>10}\")\nfor g, t in ((2022, 2022), (2022, 2023), (2022, 2024), (2023, 2023)):\n    sub = panel[panel[\"cohort\"].isin([g, 9999]) & panel[\"time\"].isin([g - 1, t])]\n    seen = sub.groupby(\"geo\")[\"time\"].nunique()\n    bal = sub[sub[\"geo\"].isin(seen[seen == 2].index)]\n    tr = bal[bal[\"cohort\"] == g].groupby(\"time\")[Y].mean()\n    co = bal[bal[\"cohort\"] == 9999].groupby(\"time\")[Y].mean()\n    fixed = (tr[t] - tr[g - 1]) - (co[t] - co[g - 1])\n    att = gt.loc[(gt.group == g) & (gt.time == t), \"effect\"].iloc[0]\n    print(f\"{f'{g},{t}':>9}{twoby(g, g - 1, t):>12.3f}{fixed:>12.3f}{att:>10.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n cohort  year  ATT(g,t)     SE\n   2021  2021         —      —   dropped: missing_period\n   2021  2022         —      —   dropped: missing_period\n   2021  2023         —      —   dropped: missing_period\n   2021  2024         —      —   dropped: missing_period\n   2022  2022     1.739  1.135\n   2022  2023     2.751  0.843\n   2022  2024     2.138  0.977\n   2023  2022    -1.126  0.440  ← pre-treatment, not an effect\n   2023  2023     1.842  0.553\n   2023  2024         —      —   dropped: zero_treated_control\n\n       overall ATT     2.196  0.782   bias -0.204, 30 clusters\n       cohort 2022     2.209  0.809   9 countries\n       cohort 2023     1.842  0.553   1 country\n\nthe hand-rolled numbers, and what was wrong with them:\n      g,t  as written  same units  ATT(g,t)\n2022,2022       1.701       1.739     1.739\n2022,2023       2.702       2.751     2.751\n2022,2024       2.292       2.138     2.138\n2023,2023       1.666       1.842     1.842\n```\n:::\n:::\n\n\nThe first table is this chapter's own reasoning, produced by the estimator\nrather than argued for in advance. The 2021 cohort is dropped as\n`missing_period` — no pre-treatment observation exists, which is the conclusion\nreached two sections ago by reading the adoption structure. ATT(2023, 2024) is\ndropped as `zero_treated_control`, the same absent country the hand-rolled\nversion returned `NaN` for. Neither refusal is buried inside a coefficient.\n\nThe standard errors are new. They come from the influence function of each\ngroup-time effect, clustered by country, and they carry through to the\naggregate: an overall ATT of +2.20 with a standard error of 0.78, against a\ntruth of 2.40. The interval covers it, which is the honest summary of what\nthirty countries over four years can establish about an effect of this size.\n\n::: {.warn}\n**Read the cohort lines again.** The nine-country cohort reports a standard\nerror of 0.81. The one-country cohort reports 0.55. One country's trajectory is\nnot measured more precisely than nine countries' — the smaller number is what\ncomes out when there is no between-country variation left to estimate, and the\nsoftware has no way to know that a cohort of one should not be reported at all.\nThe estimator computes whatever you ask it for. Deciding what is worth asking\nfor is still yours.\n:::\n\nThe last table is the uncomfortable one. The hand-rolled estimates and\nCallaway–Sant'Anna's differ — +1.70 against +1.74, +2.29 against +2.14 — and\nthe middle column says why. `twoby` averaged whichever countries happened to be\npresent in each year, and this panel is not balanced: Malta and Estonia have no\n2022 observation, Luxembourg no 2021, Spain no 2023, Croatia neither. The \"before\"\nmean and the \"after\" mean were therefore computed over different sets of\ncountries, and part of what looked like an effect was the change in who was\nbeing averaged. Hold the units fixed and the estimator is reproduced to three\ndecimals.\n\nThat failure is on this chapter's own list — it is the **composition change**\nwarning further down, committed in code written to demonstrate the method,\non a dataset small enough to audit by hand. Which is the argument for using the\npackage rather than the argument against it: not that it is cleverer, but that\nthe choices the hand-rolled version made silently are ones it is forced to make\nout loud.\n\n## Pre-trends: what this data cannot tell you\n\n::: {.cell execution_count=4}\n``` {.python .cell-code code-summary=\"Show the code\"}\ncohort = 2022\nsub = panel[panel[\"cohort\"].isin([cohort, 9999])].copy()\nsub[\"treated\"] = (sub[\"cohort\"] == cohort).astype(int)\n\ntr = sub[sub[\"treated\"] == 1].groupby(\"time\")[Y].mean()\nco = sub[sub[\"treated\"] == 0].groupby(\"time\")[Y].mean()\nyears = sorted(sub[\"time\"].unique())\neff = [(t - cohort, (tr[t] - tr[2021]) - (co[t] - co[2021])) for t in years]\n\nfig, ax = plt.subplots(figsize=(6.8, 4.0))\nxs = [e for e, _ in eff]; ys = [v for _, v in eff]\nax.axhline(0, color=CL.line, lw=1)\nax.axhline(TRUE_EFFECT, color=CL.good, lw=1.4, ls=\":\", label=\"true effect\")\nax.axvline(-0.5, color=CL.muted, lw=1.2, ls=\"--\")\nax.plot(xs, ys, marker=\"o\", ms=7, lw=1.8, color=CL.accent, zorder=3)\nax.annotate(\"reference period\\n(zero by construction)\", (-1, 0),\n            textcoords=\"offset points\", xytext=(6, 26), fontsize=8, color=CL.muted)\nax.set_xlabel(\"years since adoption\"); ax.set_ylabel(\"estimated effect (pp)\")\nax.set_xticks(xs)\nax.legend(frameon=False, fontsize=8.5, loc=\"lower right\")\nfig.tight_layout()\n\nprint(f\"{'event time':>12}{'estimate':>11}\")\nfor e, v in eff:\n    note = \"  reference — not evidence\" if e == -1 else \"\"\n    print(f\"{e:>12}{v:>11.3f}{note}\")\nprint(f\"\\npre-periods available for this cohort: \"\n      f\"{sum(1 for e, _ in eff if e < 0)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  event time   estimate\n          -1      0.000  reference — not evidence\n           0      1.701\n           1      2.702\n           2      2.292\n\npre-periods available for this cohort: 1\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Event study for the 2022 cohort against the never-treated. Event time 0 is the year of adoption. The point at $-1$ is the reference period and is zero by construction, not by evidence — with a single pre-period there is no pre-trend to examine.](session-11_files/figure-pdf/fig-event-study-output-2.png){#fig-event-study}\n:::\n:::\n\n\nAn event study is the standard way to make parallel trends look plausible: plot\nthe estimated effect at each period relative to adoption, and look for a flat\nline before treatment. Here the pre-treatment portion consists of a single point,\nwhich is the reference period and therefore exactly zero by arithmetic.\n\n**A flat pre-trend that contains one mechanically-zero point is not evidence of\nanything.** This is not a defect of the analysis; it is a property of the data,\nand it means the identifying assumption of this chapter cannot be examined at all\nin this dataset. The honest report says so, states the estimate as conditional on\nan assumption that could not be checked, and treats the finding accordingly.\n\nIt is worth noticing how much weaker that is than what chapter 10 could do. There\nthe assumption was also untestable, but the covariates could at least be shown to\nbe balanced. Here, there is nothing to show.\n\n## How large a violation would it take?\n\n\"The assumption cannot be checked\" is where this dataset leaves you. It is not\nwhere the literature leaves you. @rambachan2023 changes the question: rather\nthan testing parallel trends, ask how large a violation of it would have to be\nbefore the finding stops holding, and report *that* number. The output is a\nfamily of intervals indexed by how much post-treatment departure from parallel\ntrends you are prepared to allow — measured, in the relative-magnitudes version,\nas a multiple $M$ of the largest departure actually visible before treatment.\n\n::: {#check-honest .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Run it: how much violation does the result survive?\"}\nes = cs.aggregate(\"event_study\")\n\nprint(\"the whole of the pre-treatment evidence in this dataset:\")\nfor _, r in es.to_dataframe().query(\"event_time < 0\").iterrows():\n    print(f\"   event time {int(r.event_time):>3}: {r.att:+.3f}  \"\n          f\"(SE {r.se:.3f}, p {r.p_value:.3f}), from {int(r.n)} cohort\")\n\nprint(f\"\\n{'M':>5}{'identified set':>22}{'95% robust CI':>22}   rules out zero\")\nfor M in (0.0, 0.25, 0.5, 1.0, 2.0):\n    h = dd.HonestDiD(method=\"relative_magnitude\", M=M).fit(es)\n    print(f\"{M:>5.2f}   [{h.lb:>7.3f},{h.ub:>7.3f}]     \"\n          f\"[{h.ci_lb:>7.3f},{h.ci_ub:>7.3f}]   \"\n          f\"{'yes' if h.is_significant else 'no'}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nthe whole of the pre-treatment evidence in this dataset:\n   event time  -1: -1.126  (SE 0.440, p 0.016), from 1 cohort\n\n    M        identified set         95% robust CI   rules out zero\n 0.00   [  2.212,  2.212]     [  0.613,  3.812]   yes\n 0.25   [  1.649,  2.776]     [  0.050,  4.375]   yes\n 0.50   [  1.086,  3.339]     [ -0.513,  4.938]   no\n 1.00   [ -0.040,  4.465]     [ -1.640,  6.064]   no\n 2.00   [ -2.293,  6.718]     [ -3.892,  8.317]   no\n```\n:::\n:::\n\n\nTwo things to read off that, and the second matters more.\n\nThe pre-treatment evidence is a single number, from a single cohort, and that\ncohort is a single country. Germany adopted in 2023, so it is the only unit\nwhose pre-period is something other than its own reference year, and its\n2021→2022 change ran 1.13 points below the never-treated countries'. Everything\nin the table below rests on that one comparison. The 2022 cohort, nine countries\nstrong, contributes nothing here at all — its only pre-period *is* the reference.\n\nThe sensitivity table then says: the result survives at $M = 0.25$ and not at\n$M = 0.5$. In words, if post-treatment departures from parallel trends could be\nas much as half the size of the one pre-treatment departure visible in the data,\nthe interval already contains zero. That is a low breakdown point, and it ought\nto be — it is what an estimate resting on one country's single pre-period is\nworth.\n\n::: {.warn}\n**This is not a test, and nothing here has been tested.** The honest sentence is\n\"the finding requires post-treatment violations of parallel trends no larger\nthan about a quarter of the single pre-treatment deviation we can observe, and\nwe have one country from which to judge that.\" A sensitivity analysis converts\nan untestable assumption into a statement about how much of it the result needs.\nThat is real progress over asserting the assumption, and it is not the same\nthing as evidence for it.\n:::\n\n## What difference-in-differences cannot fix\n\n**Anything that changes at the same time as treatment.** Fixed effects remove\nwhat is constant; the second difference removes what is common. A shock hitting\nonly the treated group in the treatment year is indistinguishable from the\ntreatment, and no amount of data separates them. Countries that adopt an AI\nstrategy in a given year may be doing several other things that year.\n\n**Anticipation.** If units change behaviour before adoption because they know it\nis coming, the pre-period is already contaminated and the \"before\" is not a\nclean baseline. This shows as a non-zero pre-trend, when there are enough\npre-periods to see one.\n\n**Composition change.** If the units in the panel change — countries entering or\nleaving the sample, or a survey changing who it asks — the first difference is\ncomparing different populations rather than the same one over time.\n\n**Spillovers.** The control group must be unaffected. If a national strategy in\none country shifts behaviour in its neighbours, the controls are partially\ntreated and the estimate is attenuated toward zero.\n\n## A short review of the literature\n\n::: {.lit}\nThe design is older than its name: @wing2018 traces it to Snow's 1855 water study\nand sets out the modern practice, including the pre-trend examination and the\nsensitivity checks a credible paper is expected to show.\n\nThe last decade has been dominated by a single discovery about staggered\nadoption. @goodmanbacon2021 decomposed the two-way fixed effects estimator into\nthe underlying two-by-two comparisons and showed that some of them use\nalready-treated units as controls; @dechaisemartin2020 showed that the implied\nweights can be negative, so the estimand may lie outside the range of every\nunderlying effect. Neither paper is a curiosity — between them they called into\nquestion a large body of published work.\n\nThe constructive replacements estimate cohort-specific effects against clean\ncomparison groups and aggregate them explicitly. @callaway2021 gives the\ngroup-time average treatment effects and the aggregation schemes; @sun2021\ndoes the equivalent for event-study specifications, where the same negative\nweighting contaminates the coefficients on individual leads and lags.\n\nWhere the pre-trend evidence is thin — and outside a handful of long panels it\nusually is — @rambachan2023 replaces the ritual pre-trend test with a\nsensitivity analysis. Report the range of estimates consistent with violations\nof parallel trends up to a stated size, and the reader can see how much of the\nassumption the finding actually needs rather than being told it holds.\n\nOn inference, the reference remains Bertrand, Duflo and Mullainathan, discussed\nin chapter 3: DiD data are serially correlated panels, and standard errors that\nignore it reject true nulls at many times the nominal rate.\n:::\n\n## What to report\n\n1. **The adoption structure.** How many units in each cohort, how many periods\n   before and after, and which cohorts are unusable. A table of this is worth\n   more than a paragraph asserting the design is sound.\n2. **The parallel-trends argument**, as an argument. Why should the gap have\n   stayed constant? Institutional reasoning, not a citation to the assumption.\n3. **An event study**, with the reference period marked as such — and if there\n   are too few pre-periods to see a trend, say that instead of implying the flat\n   line is evidence.\n4. **A staggered-robust estimator alongside TWFE.** If they agree, the weights\n   were benign and you have shown it. If they disagree, the decomposition is the\n   finding. `diff-diff`'s `CallawaySantAnna` is the Python route; the `did`\n   package is the R one.\n5. **Standard errors clustered by unit**, with the number of clusters. Below\n   about forty, say what you did about it.\n6. **The scale.** Levels or logs is part of the assumption, because parallel\n   trends in one is not parallel trends in the other.\n7. **What could have moved at the same time.** The most credible DiD papers name\n   the confounding events they considered and explain why each is implausible —\n   which is the modern version of Snow pointing out that nobody chose their water\n   company.\n8. **How much violation the result survives.** A breakdown value — the size of\n   departure from parallel trends at which the finding stops holding — is worth\n   more than a pre-trend $p$-value, and unlike the $p$-value it can be reported\n   even when there is nothing to test.\n\n",
    "supporting": [
      "session-11_files/figure-pdf"
    ],
    "filters": []
  }
}